# SPDX-FileCopyrightText: 2026 Virantis
# SPDX-License-Identifier: LicenseRef-Vooda-Community-1.0

"""
PR Pipeline Engine — end-to-end: apply patch → create branch → commit → open PR.

Takes an approved RemediationPatch, applies it to the repository,
and opens a pull request with finding details in the description.
"""

import os
import re
import tempfile
import structlog
from typing import Optional
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from services.git_integration.base import GitProvider, PRRequest, FileChange, PRResult
from services.git_integration.factory import create_git_provider

logger = structlog.get_logger()


def _generate_branch_name(finding_id: str, category: str) -> str:
    """Generate a clean branch name for the fix."""
    short_id = finding_id[:8]
    slug = re.sub(r"[^a-z0-9]+", "-", category.lower())[:30].strip("-")
    return f"vooda/fix/{slug}-{short_id}"


def _build_pr_description(
    finding: dict,
    plan: dict,
    patch: dict,
) -> str:
    """Build a rich PR description with finding details and fix rationale."""
    severity_emoji = {
        "critical": "\U0001f534",  # red circle
        "high": "\U0001f7e0",      # orange circle
        "medium": "\U0001f7e1",    # yellow circle
        "low": "\U0001f7e2",       # green circle
    }
    sev = finding.get("severity", "medium")
    emoji = severity_emoji.get(sev, "\u26aa")

    description = f"""## {emoji} Security Fix: {finding.get('title', 'Vulnerability Fix')}

**Severity:** {sev.upper()}
**CWE:** {finding.get('cwe', 'N/A')}
**Category:** {finding.get('vulnerability_category', 'N/A')}
**File:** `{finding.get('file_path', 'N/A')}:{finding.get('line_start', '')}`

---

### Root Cause
{plan.get('root_cause', 'See finding details.')}

### Fix Rationale
{plan.get('fix_rationale', 'See patch diff.')}

### Risk of Breakage
**{patch.get('risk_of_breakage', plan.get('risk_of_breakage', 'unknown')).upper()}**

### Developer Notes
"""
    for note in plan.get("developer_notes", []):
        description += f"- {note}\n"

    description += "\n### Validation Steps\n"
    for step in plan.get("validation_steps", []):
        description += f"- [ ] {step}\n"

    if patch.get("safety_score") is not None:
        description += f"\n### Vooda AI Confidence\n"
        description += f"- Patch confidence: **{(patch.get('confidence_score', 0) * 100):.0f}%**\n"
        description += f"- Safety score: **{(patch.get('safety_score', 0) * 100):.0f}%**\n"

    description += "\n---\n*Generated by [Vooda AI](https://vooda.ai) Security Engine*"
    return description


def _apply_unified_diff(original_content: str, diff: str) -> Optional[str]:
    """
    Apply a unified diff to file content.
    Returns the patched content, or None if the diff can't be applied.
    """
    if not diff or not original_content:
        return None

    lines = original_content.split("\n")
    result_lines = list(lines)

    # Parse the diff to extract changes
    # This is a simplified diff applicator for single-file patches
    current_line = 0
    offset = 0

    for diff_line in diff.split("\n"):
        if diff_line.startswith("@@"):
            # Parse hunk header: @@ -old_start,old_count +new_start,new_count @@
            m = re.match(r"@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@", diff_line)
            if m:
                current_line = int(m.group(1)) - 1 + offset
        elif diff_line.startswith("-") and not diff_line.startswith("---"):
            # Line removed
            if 0 <= current_line < len(result_lines):
                result_lines.pop(current_line)
                offset -= 1
            # Don't advance current_line
        elif diff_line.startswith("+") and not diff_line.startswith("+++"):
            # Line added
            new_line = diff_line[1:]
            result_lines.insert(current_line, new_line)
            current_line += 1
            offset += 1
        elif diff_line.startswith(" "):
            # Context line — advance
            current_line += 1
        # Skip diff headers (---, +++)

    return "\n".join(result_lines)


class PRPipelineEngine:
    """
    Orchestrates the full PR creation flow:
    1. Get git credentials for the repo
    2. Create fix branch
    3. Apply patch to affected files
    4. Commit changes
    5. Open PR with finding details
    """

    async def create_fix_pr(
        self,
        db: AsyncSession,
        finding_id: UUID,
    ) -> PRResult:
        """
        Create a pull request with the fix for a finding.

        Args:
            db: Database session
            finding_id: ID of the finding to fix

        Returns:
            PRResult with PR URL and metadata
        """
        from apps.api.app.models.finding import NormalizedFinding
        from apps.api.app.models.remediation import RemediationPlan, RemediationPatch
        from apps.api.app.models.repository import Repository
        from apps.api.app.models.integration import IntegrationConfig

        # Load finding
        f_result = await db.execute(
            select(NormalizedFinding).where(NormalizedFinding.id == finding_id)
        )
        finding = f_result.scalar_one_or_none()
        if not finding:
            return PRResult(success=False, error="Finding not found")

        # Load remediation plan and patch
        plan_result = await db.execute(
            select(RemediationPlan)
            .where(RemediationPlan.finding_id == finding_id)
            .order_by(RemediationPlan.created_at.desc())
            .limit(1)
        )
        plan = plan_result.scalar_one_or_none()
        if not plan:
            return PRResult(success=False, error="No remediation plan found")

        patch_result = await db.execute(
            select(RemediationPatch)
            .where(RemediationPatch.plan_id == plan.id)
            .order_by(RemediationPatch.created_at.desc())
            .limit(1)
        )
        patch = patch_result.scalar_one_or_none()
        if not patch or not patch.patch_diff:
            return PRResult(success=False, error="No patch available")

        # Load repository
        repo_result = await db.execute(
            select(Repository).where(Repository.id == finding.repository_id)
        )
        repo = repo_result.scalar_one_or_none()
        if not repo or not repo.url:
            return PRResult(success=False, error="Repository URL not configured")

        # Get git credentials from SCM integration
        cred_result = await db.execute(
            select(IntegrationConfig).where(
                IntegrationConfig.tenant_id == finding.tenant_id,
                IntegrationConfig.integration_type == "scm",
                IntegrationConfig.is_active == True,
            )
        )
        scm_integration = cred_result.scalar_one_or_none()
        credentials = scm_integration.config if scm_integration else {}

        # Also try repo metadata for token
        if not credentials.get("token"):
            repo_meta = repo.metadata_ or {}
            if repo_meta.get("auth_token"):
                credentials["token"] = repo_meta["auth_token"]

        # Create git provider
        provider = create_git_provider(repo.url, credentials)
        if not provider:
            return PRResult(success=False, error="Cannot create git provider — configure SCM integration first")

        # Generate branch name
        branch_name = _generate_branch_name(str(finding.id), finding.vulnerability_category)
        target_branch = repo.default_branch or "main"

        # Create branch
        branch_ok = await provider.create_branch(branch_name, target_branch)
        if not branch_ok:
            return PRResult(success=False, error=f"Failed to create branch {branch_name}")

        # Get current file content and apply patch
        files_to_commit = []
        for file_path in (patch.files_changed or [finding.file_path]):
            original = await provider.get_file_content(file_path, target_branch)
            if original is None:
                logger.warning("file_not_found_in_repo", file=file_path)
                continue

            patched = _apply_unified_diff(original, patch.patch_diff)
            if patched and patched != original:
                files_to_commit.append(FileChange(
                    file_path=file_path,
                    content=patched,
                ))

        if not files_to_commit:
            return PRResult(success=False, error="Patch could not be applied to any files")

        # Commit
        commit_msg = (
            f"fix: {finding.vulnerability_category} in {finding.file_path}\n\n"
            f"Remediation for {finding.title[:80]}\n"
            f"CWE: {finding.cwe or 'N/A'}\n\n"
            f"Generated by Vooda AI Security Engine"
        )
        commit_ok = await provider.commit_files(branch_name, files_to_commit, commit_msg)
        if not commit_ok:
            return PRResult(success=False, error="Failed to commit changes")

        # Build PR description
        finding_data = {
            "title": finding.title,
            "severity": finding.severity.value if hasattr(finding.severity, "value") else str(finding.severity),
            "cwe": finding.cwe,
            "vulnerability_category": finding.vulnerability_category,
            "file_path": finding.file_path,
            "line_start": finding.line_start,
        }
        plan_data = {
            "root_cause": plan.root_cause,
            "fix_rationale": plan.fix_rationale,
            "developer_notes": plan.developer_notes or [],
            "validation_steps": plan.validation_steps or [],
            "risk_of_breakage": plan.risk_of_breakage,
        }
        patch_data = {
            "confidence_score": patch.confidence_score,
            "safety_score": patch.safety_score,
            "risk_of_breakage": plan.risk_of_breakage,
        }

        pr_title = f"fix: {finding.vulnerability_category} — {finding.file_path}"
        if len(pr_title) > 70:
            pr_title = pr_title[:67] + "..."

        pr_desc = _build_pr_description(finding_data, plan_data, patch_data)

        # Create PR
        pr_request = PRRequest(
            title=pr_title,
            description=pr_desc,
            source_branch=branch_name,
            target_branch=target_branch,
            labels=["security", "vooda-ai", finding.severity.value if hasattr(finding.severity, "value") else str(finding.severity)],
        )
        pr_result = await provider.create_pull_request(pr_request)

        # Update patch record with PR info
        if pr_result.success:
            patch.pr_url = pr_result.pr_url
            patch.status = "applied"
            patch.metadata_ = {
                **(patch.metadata_ or {}),
                "pr_number": pr_result.pr_number,
                "pr_branch": branch_name,
            }
            finding.remediation_status = "applied"
            await db.flush()

        logger.info(
            "pr_pipeline_complete",
            finding_id=str(finding_id),
            success=pr_result.success,
            pr_url=pr_result.pr_url,
            branch=branch_name,
        )

        return pr_result
