# SPDX-FileCopyrightText: 2026 Virantis
# SPDX-License-Identifier: LicenseRef-Vooda-Community-1.0

from __future__ import annotations
"""Gitleaks-sourced detectors batch 5: Remaining platforms + environment variable patterns.
Final batch to reach 400+ total detectors."""

from services.secret_scan.detectors.base import SecretRule

RULES: list[SecretRule] = [
    # ── Environment Variable Patterns (high-value, context-based) ──
    SecretRule(rule_id="VOODA-SEC-ENV-001", title="AWS Access Key in Env", secret_type="env_aws_key", severity="critical",
        pattern=r'(?:AWS_ACCESS_KEY_ID|AWS_ACCESS_KEY)\s*[=:]\s*["\']?(AKIA[0-9A-Z]{16})["\']?', keywords=["AWS_ACCESS_KEY"], confidence=0.98,
        description="AWS access key ID in environment variable assignment.", fix_hint="Use IAM Roles instead. Remove from .env and rotate key."),
    SecretRule(rule_id="VOODA-SEC-ENV-002", title="AWS Secret Key in Env", secret_type="env_aws_secret", severity="critical",
        pattern=r'(?:AWS_SECRET_ACCESS_KEY|AWS_SECRET_KEY)\s*[=:]\s*["\']?([A-Za-z0-9/+=]{40})["\']?', keywords=["AWS_SECRET_ACCESS_KEY", "AWS_SECRET_KEY"], confidence=0.95,
        description="AWS secret access key in environment variable.", fix_hint="Use IAM Roles. Rotate key immediately."),
    SecretRule(rule_id="VOODA-SEC-ENV-003", title="GitHub Token in Env", secret_type="env_github_token", severity="critical",
        pattern=r'(?:GITHUB_TOKEN|GH_TOKEN|GITHUB_PAT)\s*[=:]\s*["\']?(ghp_[A-Za-z0-9_]{36,}|github_pat_[A-Za-z0-9_]{22,})["\']?', keywords=["GITHUB_TOKEN", "GH_TOKEN", "GITHUB_PAT"], confidence=0.98,
        description="GitHub token in environment variable.", fix_hint="Use GitHub App tokens with minimum scopes."),
    SecretRule(rule_id="VOODA-SEC-ENV-004", title="Stripe Key in Env", secret_type="env_stripe_key", severity="critical",
        pattern=r'(?:STRIPE_SECRET_KEY|STRIPE_KEY|STRIPE_API_KEY)\s*[=:]\s*["\']?(sk_live_[A-Za-z0-9]{24,})["\']?', keywords=["STRIPE_SECRET_KEY", "STRIPE_KEY", "STRIPE_API_KEY"], confidence=0.98,
        description="Stripe live secret key in environment variable.", fix_hint="Use restricted keys. Rotate immediately."),
    SecretRule(rule_id="VOODA-SEC-ENV-005", title="Database URL in Env", secret_type="env_database_url", severity="critical",
        pattern=r'(?:DATABASE_URL|DB_URL|MONGO_URI|REDIS_URL|POSTGRES_URL|MYSQL_URL)\s*[=:]\s*["\']?([a-z]+://[^:\s]+:[^@\s]+@[^\s"\']+)["\']?', keywords=["DATABASE_URL", "DB_URL", "MONGO_URI", "REDIS_URL", "POSTGRES_URL", "MYSQL_URL"], confidence=0.95,
        description="Database connection URL with credentials in environment variable.", fix_hint="Use a secret manager for database credentials."),
    SecretRule(rule_id="VOODA-SEC-ENV-006", title="Slack Token in Env", secret_type="env_slack_token", severity="high",
        pattern=r'(?:SLACK_TOKEN|SLACK_BOT_TOKEN|SLACK_API_TOKEN)\s*[=:]\s*["\']?(xox[bpsa]-[A-Za-z0-9\-]+)["\']?', keywords=["SLACK_TOKEN", "SLACK_BOT_TOKEN", "SLACK_API_TOKEN"], confidence=0.95,
        description="Slack token in environment variable.", fix_hint="Use Slack's OAuth 2.0 flow. Rotate immediately."),
    SecretRule(rule_id="VOODA-SEC-ENV-007", title="SendGrid Key in Env", secret_type="env_sendgrid_key", severity="high",
        pattern=r'(?:SENDGRID_API_KEY|SENDGRID_KEY)\s*[=:]\s*["\']?(SG\.[A-Za-z0-9\-_]{22}\.[A-Za-z0-9\-_]{43})["\']?', keywords=["SENDGRID_API_KEY", "SENDGRID_KEY"], confidence=0.98,
        description="SendGrid API key in environment variable.", fix_hint="Regenerate at SendGrid → Settings → API Keys."),
    SecretRule(rule_id="VOODA-SEC-ENV-008", title="Twilio Credentials in Env", secret_type="env_twilio_creds", severity="high",
        pattern=r'(?:TWILIO_AUTH_TOKEN|TWILIO_TOKEN)\s*[=:]\s*["\']?([a-f0-9]{32})["\']?', keywords=["TWILIO_AUTH_TOKEN", "TWILIO_TOKEN"], confidence=0.90,
        description="Twilio auth token in environment variable.", fix_hint="Use Twilio API keys instead of master auth tokens."),
    SecretRule(rule_id="VOODA-SEC-ENV-009", title="OpenAI Key in Env", secret_type="env_openai_key", severity="high",
        pattern=r'(?:OPENAI_API_KEY|OPENAI_KEY)\s*[=:]\s*["\']?(sk-[A-Za-z0-9]{20,})["\']?', keywords=["OPENAI_API_KEY", "OPENAI_KEY"], confidence=0.95,
        description="OpenAI API key in environment variable.", fix_hint="Rotate at platform.openai.com. Use project-scoped keys."),
    SecretRule(rule_id="VOODA-SEC-ENV-010", title="Anthropic Key in Env", secret_type="env_anthropic_key", severity="high",
        pattern=r'(?:ANTHROPIC_API_KEY|ANTHROPIC_KEY)\s*[=:]\s*["\']?(sk-ant-[A-Za-z0-9\-_]{40,})["\']?', keywords=["ANTHROPIC_API_KEY", "ANTHROPIC_KEY"], confidence=0.98,
        description="Anthropic Claude API key in environment variable.", fix_hint="Regenerate at console.anthropic.com → API keys."),
    # ── Additional Token Formats ──
    SecretRule(rule_id="VOODA-SEC-VERCEL-002", title="Vercel Access Token", secret_type="vercel_token_v2", severity="high",
        pattern=r'(?:^|[^A-Za-z0-9])([a-zA-Z0-9]{24})', keywords=["VERCEL_TOKEN", "vercel_token"], confidence=0.50,
        description="Vercel deployment access token.", fix_hint="Regenerate at Vercel → Settings → Tokens."),
    SecretRule(rule_id="VOODA-SEC-GITPOD-001", title="Gitpod Access Token", secret_type="gitpod_token", severity="medium",
        pattern=r'(?:gitpod)[\w\s=:"\'-]*([a-zA-Z0-9\-_]{40,})', keywords=["gitpod", "GITPOD"], confidence=0.70,
        description="Gitpod access token.", fix_hint="Regenerate at Gitpod → Settings → Access Tokens."),
    SecretRule(rule_id="VOODA-SEC-REPLIT-001", title="Replit API Token", secret_type="replit_token", severity="medium",
        pattern=r'(?:replit|REPL_)[\w\s=:"\'-]*([a-zA-Z0-9\-_]{30,})', keywords=["replit", "REPL_ID"], confidence=0.60,
        description="Replit API or identity token.", fix_hint="Regenerate at Replit → Settings."),
    SecretRule(rule_id="VOODA-SEC-CODEMAGIC-002", title="Codemagic API Token", secret_type="codemagic_token", severity="high",
        pattern=r'(?:codemagic)[\w\s=:"\'-]*([a-zA-Z0-9\-_]{40,})', keywords=["codemagic", "CODEMAGIC"], confidence=0.70,
        description="Codemagic CI/CD API token.", fix_hint="Regenerate at Codemagic → Account → API Tokens."),
    SecretRule(rule_id="VOODA-SEC-APPWRITE-001", title="Appwrite API Key", secret_type="appwrite_key", severity="high",
        pattern=r'(?:appwrite)[\w\s=:"\'-]*([a-f0-9]{32,})', keywords=["appwrite", "APPWRITE"], confidence=0.70,
        description="Appwrite backend API key.", fix_hint="Regenerate at Appwrite → Project → API Keys."),
    SecretRule(rule_id="VOODA-SEC-POCKETBASE-001", title="PocketBase Admin Token", secret_type="pocketbase_token", severity="high",
        pattern=r'(?:pocketbase|PB_)[\w\s=:"\'-]*(eyJ[a-zA-Z0-9\-_]+\.eyJ[a-zA-Z0-9\-_]+\.[a-zA-Z0-9\-_]+)', keywords=["pocketbase", "PB_"], confidence=0.70,
        description="PocketBase admin JWT token.", fix_hint="Regenerate admin token via PocketBase admin UI."),
    SecretRule(rule_id="VOODA-SEC-DIRECTUS-001", title="Directus Admin Token", secret_type="directus_token", severity="high",
        # \b anchors "directus" to a word boundary so it can't match as a
        # SUBSTRING of "Redirect"/"redirectUser…" (rules are case-insensitive by
        # default): `safeRedirectUsesMapped…` -> `directUs` used to fire on any
        # auth/redirect identifier. Real tokens (DIRECTUS_ADMIN_TOKEN=…,
        # directus_token: …) sit at a boundary and still match.
        pattern=r'\b(?:directus|DIRECTUS)[\w\s=:"\'-]*([a-zA-Z0-9\-_]{20,})', keywords=["directus", "DIRECTUS_ADMIN_TOKEN"], confidence=0.65,
        description="Directus headless CMS admin token.", fix_hint="Regenerate at Directus → Admin → Users → Edit Token."),
    SecretRule(rule_id="VOODA-SEC-MEDUSA-002", title="Medusa API Token", secret_type="medusa_token", severity="high",
        pattern=r'(?:medusa)[\w\s=:"\'-]*([a-zA-Z0-9\-_]{30,})', keywords=["medusa", "MEDUSA_ADMIN"], confidence=0.65,
        description="Medusa e-commerce API token.", fix_hint="Regenerate at Medusa Admin → Settings → API Keys."),
    SecretRule(rule_id="VOODA-SEC-PAYLOAD-001", title="Payload CMS Secret", secret_type="payload_secret", severity="high",
        pattern=r'(?:PAYLOAD_SECRET|payload_secret)\s*[=:]\s*["\']?([A-Za-z0-9\-_+/=]{20,})["\']?', keywords=["PAYLOAD_SECRET", "payload_secret"], confidence=0.80,
        description="Payload CMS secret key.", fix_hint="Regenerate and store in environment variables."),
    # ── Docker / Container ──
    SecretRule(rule_id="VOODA-SEC-DOCKER-002", title="Docker Registry Password in Config", secret_type="docker_config_auth", severity="critical",
        pattern=r'"auth"\s*:\s*"([A-Za-z0-9+/=]{20,})"', keywords=["auth", "docker", "registry"], confidence=0.70,
        description="Docker registry auth credentials (base64-encoded) in config.json.", fix_hint="Use credential helpers (docker-credential-ecr-login, etc.) instead of storing plaintext."),
    SecretRule(rule_id="VOODA-SEC-GHCR-001", title="GitHub Container Registry Token", secret_type="ghcr_token", severity="high",
        pattern=r'(?:ghcr|GHCR|github_container|GITHUB_CR)[\w\s=:"\'-]*(ghp_[A-Za-z0-9_]{36,})', keywords=["ghcr", "GHCR", "github_container"], confidence=0.90,
        description="GitHub Container Registry access token.", fix_hint="Use fine-grained PATs with packages:read scope only."),
    # ── CDN / Edge ──
    SecretRule(rule_id="VOODA-SEC-BUNNY-001", title="BunnyCDN API Key", secret_type="bunnycdn_key", severity="medium",
        pattern=r'(?:bunny|BUNNY)[\w\s=:"\'-]*([a-f0-9\-]{36})', keywords=["bunny", "BUNNY_API"], confidence=0.75,
        description="BunnyCDN API key.", fix_hint="Regenerate at BunnyCDN → Account → API Key."),
    SecretRule(rule_id="VOODA-SEC-KEYCDN-001", title="KeyCDN API Key", secret_type="keycdn_key", severity="medium",
        pattern=r'(?:keycdn|KEYCDN)[\w\s=:"\'-]*([a-zA-Z0-9]{20,})', keywords=["keycdn", "KEYCDN"], confidence=0.70,
        description="KeyCDN API key.", fix_hint="Regenerate at KeyCDN → Account → API Key."),
    # ── Blockchain / Web3 ──
    SecretRule(rule_id="VOODA-SEC-INFURA-001", title="Infura API Key", secret_type="infura_key", severity="high",
        pattern=r'(?:infura)[\w\s=:"\'-]*([a-f0-9]{32})', keywords=["infura", "INFURA"], confidence=0.80,
        description="Infura Ethereum node API key.", fix_hint="Regenerate at Infura → Dashboard → Settings."),
    SecretRule(rule_id="VOODA-SEC-ALCHEMY-002", title="Alchemy API Key", secret_type="alchemy_key", severity="high",
        pattern=r'(?:alchemy)[\w\s=:"\'-]*([a-zA-Z0-9\-_]{32})', keywords=["alchemy", "ALCHEMY"], confidence=0.75,
        description="Alchemy Web3 RPC API key.", fix_hint="Regenerate at Alchemy → Dashboard → Apps → View Key."),
    SecretRule(rule_id="VOODA-SEC-MORALIS-002", title="Moralis API Key", secret_type="moralis_key", severity="high",
        pattern=r'(?:moralis)[\w\s=:"\'-]*([a-zA-Z0-9]{40,})', keywords=["moralis", "MORALIS"], confidence=0.70,
        description="Moralis Web3 API key.", fix_hint="Regenerate at Moralis → Account → API Keys."),
    SecretRule(rule_id="VOODA-SEC-ETHERSCAN-002", title="Etherscan API Key", secret_type="etherscan_key", severity="medium",
        pattern=r'(?:etherscan)[\w\s=:"\'-]*([A-Z0-9]{34})', keywords=["etherscan", "ETHERSCAN"], confidence=0.80,
        description="Etherscan blockchain explorer API key.", fix_hint="Regenerate at etherscan.io → MyAccount → API Keys."),
    # ── Monitoring ──
    SecretRule(rule_id="VOODA-SEC-PAGERDUTY-001", title="PagerDuty API Key", secret_type="pagerduty_key", severity="high",
        pattern=r'(?:pagerduty|PAGERDUTY)[\w\s=:"\'-]*([a-zA-Z0-9+/]{20,})', keywords=["pagerduty", "PAGERDUTY"], confidence=0.70,
        description="PagerDuty REST API key.", fix_hint="Revoke at PagerDuty → Integrations → API Access Keys."),
    SecretRule(rule_id="VOODA-SEC-OPSGENIE-002", title="OpsGenie API Key", secret_type="opsgenie_key", severity="high",
        pattern=r'(?:opsgenie|OPSGENIE)[\w\s=:"\'-]*([a-f0-9\-]{36})', keywords=["opsgenie", "OPSGENIE"], confidence=0.75,
        description="OpsGenie alert management API key.", fix_hint="Regenerate at OpsGenie → Settings → API Key Management."),
    SecretRule(rule_id="VOODA-SEC-STATUSPAGE-001", title="Statuspage API Key", secret_type="statuspage_key", severity="medium",
        pattern=r'(?:statuspage|STATUSPAGE)[\w\s=:"\'-]*([a-f0-9\-]{36})', keywords=["statuspage", "STATUSPAGE"], confidence=0.70,
        description="Atlassian Statuspage API key.", fix_hint="Regenerate at Statuspage → Account → API."),
    SecretRule(rule_id="VOODA-SEC-UPTIMEROBOT-002", title="UptimeRobot API Key", secret_type="uptimerobot_key", severity="medium",
        pattern=r'(u[0-9]+-[a-f0-9]{40,})', keywords=["uptimerobot", "UPTIMEROBOT"], confidence=0.70,
        description="UptimeRobot monitoring API key.", fix_hint="Regenerate at UptimeRobot → My Settings → API Settings."),
    # ── Payment Extended ──
    SecretRule(rule_id="VOODA-SEC-RAZORPAY-001", title="Razorpay API Key", secret_type="razorpay_key", severity="critical",
        pattern=r'(rzp_(?:live|test)_[a-zA-Z0-9]{14})', keywords=["rzp_"], confidence=0.98,
        description="Razorpay payment gateway API key.", fix_hint="Regenerate at Razorpay → Settings → API Keys."),
    SecretRule(rule_id="VOODA-SEC-RAZORPAY-002", title="Razorpay Secret Key", secret_type="razorpay_secret", severity="critical",
        pattern=r'(?:razorpay_secret|RAZORPAY_SECRET|razorpay_key_secret)\s*[=:]\s*["\']?([a-zA-Z0-9]{20,})["\']?', keywords=["razorpay_secret", "RAZORPAY_SECRET"], confidence=0.85,
        description="Razorpay secret key.", fix_hint="Regenerate at Razorpay → Settings → API Keys."),
    SecretRule(rule_id="VOODA-SEC-PAYU-001", title="PayU API Key", secret_type="payu_key", severity="critical",
        pattern=r'(?:payu|PAYU)[\w\s=:"\'-]*([a-zA-Z0-9]{20,})', keywords=["payu_key", "PAYU_KEY", "PAYU_SALT"], confidence=0.70,
        description="PayU payment gateway API key.", fix_hint="Regenerate at PayU Dashboard → Settings → API."),
    SecretRule(rule_id="VOODA-SEC-PHONEPE-001", title="PhonePe API Key", secret_type="phonepe_key", severity="high",
        pattern=r'(?:phonepe|PHONEPE)[\w\s=:"\'-]*([a-f0-9\-]{36})', keywords=["phonepe", "PHONEPE"], confidence=0.70,
        description="PhonePe payment gateway API key.", fix_hint="Regenerate at PhonePe Business Dashboard."),
    # ── Email Services ──
    SecretRule(rule_id="VOODA-SEC-SES-001", title="AWS SES SMTP Password", secret_type="aws_ses_password", severity="high",
        pattern=r'(?:SMTP_PASSWORD|SES_SMTP_PASSWORD|EMAIL_PASSWORD)\s*[=:]\s*["\']?([A-Za-z0-9+/]{40,})["\']?', keywords=["SMTP_PASSWORD", "SES_SMTP_PASSWORD", "EMAIL_PASSWORD"], confidence=0.75,
        description="AWS SES or SMTP email password.", fix_hint="Rotate SMTP credentials via AWS SES console."),
    SecretRule(rule_id="VOODA-SEC-MAILTRAP-001", title="Mailtrap API Token", secret_type="mailtrap_token", severity="medium",
        pattern=r'(?:mailtrap|MAILTRAP)[\w\s=:"\'-]*([a-f0-9]{32})', keywords=["mailtrap", "MAILTRAP"], confidence=0.75,
        description="Mailtrap email testing API token.", fix_hint="Regenerate at Mailtrap → Settings → API Tokens."),
]
