# SPDX-FileCopyrightText: 2026 Virantis
# SPDX-License-Identifier: LicenseRef-Vooda-Community-1.0

from __future__ import annotations
"""Miscellaneous detectors to reach 200+ coverage."""

from services.secret_scan.detectors.base import SecretRule

RULES: list[SecretRule] = [
    SecretRule(rule_id="VOODA-SEC-RETOOL-001", title="Retool API Key", secret_type="retool_key", severity="high",
        pattern=r'(?:retool[_-]?api[_-]?key|RETOOL_API_KEY)\s*[=:]\s*["\']?([A-Za-z0-9\-_]{30,})["\']?',
        keywords=["retool", "RETOOL"], confidence=0.75, description="Retool internal tool platform API key.", fix_hint="Regenerate at Retool → Settings → API."),
    SecretRule(rule_id="VOODA-SEC-ZAPIER-001", title="Zapier Webhook URL", secret_type="zapier_webhook", severity="medium",
        pattern=r'(https://hooks\.zapier\.com/hooks/catch/[0-9]+/[A-Za-z0-9]+)',
        keywords=["hooks.zapier.com"], confidence=0.95, description="Zapier webhook catch URL.", fix_hint="Delete and recreate the Zap trigger."),
    SecretRule(rule_id="VOODA-SEC-OPENAI-003", title="OpenAI Organization Key", secret_type="openai_org", severity="medium",
        pattern=r'(?:^|[^A-Za-z0-9])(org-[A-Za-z0-9]{24,})(?:[^A-Za-z0-9]|$)',
        keywords=["org-"], confidence=0.60, description="OpenAI organization ID.", fix_hint="Not a secret per se, but should be in environment variables."),
    SecretRule(rule_id="VOODA-SEC-RAPID-001", title="RapidAPI Key", secret_type="rapidapi_key", severity="medium",
        pattern=r'(?:rapidapi[_-]?key|RAPIDAPI_KEY|X-RapidAPI-Key)\s*[=:]\s*["\']?([a-f0-9]{50})["\']?',
        keywords=["rapidapi", "RAPIDAPI", "X-RapidAPI"], confidence=0.80, description="RapidAPI marketplace API key.", fix_hint="Rotate at RapidAPI Dashboard → Security."),
    SecretRule(rule_id="VOODA-SEC-LARK-001", title="Lark/Feishu App Secret", secret_type="lark_secret", severity="high",
        pattern=r'(?:lark[_-]?(?:app[_-]?)?secret|LARK_APP_SECRET|FEISHU_APP_SECRET)\s*[=:]\s*["\']?([A-Za-z0-9]{32,})["\']?',
        keywords=["lark_app", "LARK_APP", "feishu", "FEISHU"], confidence=0.75, description="Lark/Feishu app secret.", fix_hint="Regenerate at Lark Developer Console."),
    SecretRule(rule_id="VOODA-SEC-TELEGRAM-001", title="Telegram Bot Token", secret_type="telegram_bot_token", severity="high",
        pattern=r'(?:^|[^A-Za-z0-9])([0-9]{8,10}:[A-Za-z0-9_-]{35})(?:[^A-Za-z0-9]|$)',
        keywords=["telegram", "TELEGRAM", "bot_token"], confidence=0.70, description="Telegram Bot API token.", fix_hint="Revoke via BotFather /revoke command."),
    SecretRule(rule_id="VOODA-SEC-WEBEX-001", title="Webex Bot Token", secret_type="webex_token", severity="high",
        pattern=r'(?:webex[_-]?(?:bot[_-]?)?token|WEBEX_TOKEN)\s*[=:]\s*["\']?([A-Za-z0-9\-_]{64,})["\']?',
        keywords=["webex", "WEBEX"], confidence=0.75, description="Cisco Webex bot or integration token.", fix_hint="Regenerate at developer.webex.com."),
    SecretRule(rule_id="VOODA-SEC-MATTERMOST-001", title="Mattermost Token", secret_type="mattermost_token", severity="high",
        pattern=r'(?:mattermost[_-]?(?:access[_-]?)?token|MATTERMOST_TOKEN)\s*[=:]\s*["\']?([a-z0-9]{26})["\']?',
        keywords=["mattermost", "MATTERMOST"], confidence=0.75, description="Mattermost personal access token.", fix_hint="Revoke at Mattermost → Account Settings → Security → Personal Access Tokens."),
    SecretRule(rule_id="VOODA-SEC-GITLAB-DEPLOY-001", title="GitLab Deploy Token", secret_type="gitlab_deploy_token", severity="high",
        pattern=r'(?:^|[^A-Za-z0-9])(gldt-[A-Za-z0-9\-_]{20,})(?:[^A-Za-z0-9]|$)',
        keywords=["gldt-"], confidence=0.98, description="GitLab deploy token.", fix_hint="Revoke at GitLab → Project → Settings → Repository → Deploy Tokens."),
    SecretRule(rule_id="VOODA-SEC-SNYK-003", title="Snyk API Token", secret_type="snyk_token", severity="high",
        pattern=r'(?:snyk[_-]?(?:api[_-]?)?token|SNYK_TOKEN)\s*[=:]\s*["\']?([a-f0-9\-]{36})["\']?',
        keywords=["snyk_token", "SNYK_TOKEN"], confidence=0.80, description="Snyk security scanner API token.", fix_hint="Revoke at Snyk → Account Settings → Auth Token."),
    SecretRule(rule_id="VOODA-SEC-NGROK-001", title="ngrok Auth Token", secret_type="ngrok_token", severity="medium",
        pattern=r'(?:^|[^A-Za-z0-9])([0-9a-zA-Z]{24}_[0-9a-zA-Z]{24,})(?:[^A-Za-z0-9]|$)',
        keywords=["ngrok", "NGROK"], confidence=0.60, description="ngrok tunnel authentication token.", fix_hint="Rotate at ngrok Dashboard → Your Authtoken."),
    SecretRule(rule_id="VOODA-SEC-DOPPLER-004", title="Doppler Service Token", secret_type="doppler_token", severity="high",
        pattern=r'(?:^|[^A-Za-z0-9])(dp\.st\.[a-zA-Z0-9\-_]{40,})(?:[^A-Za-z0-9]|$)',
        keywords=["dp.st."], confidence=0.98, description="Doppler secrets management service token.", fix_hint="Revoke at Doppler Dashboard → Access → Service Tokens."),
    SecretRule(rule_id="VOODA-SEC-DOPPLER-002", title="Doppler CLI Token", secret_type="doppler_cli_token", severity="high",
        pattern=r'(?:^|[^A-Za-z0-9])(dp\.ct\.[a-zA-Z0-9\-_]{40,})(?:[^A-Za-z0-9]|$)',
        keywords=["dp.ct."], confidence=0.98, description="Doppler CLI personal token.", fix_hint="Revoke at Doppler Dashboard → Access."),
    SecretRule(rule_id="VOODA-SEC-INFISICAL-002", title="Infisical Token", secret_type="infisical_token", severity="high",
        pattern=r'(?:^|[^A-Za-z0-9])(st\.[a-zA-Z0-9\-_]{30,}\.[a-zA-Z0-9\-_]{10,})(?:[^A-Za-z0-9]|$)',
        keywords=["st."], confidence=0.70, description="Infisical secrets management token.", fix_hint="Revoke at Infisical Dashboard."),
    SecretRule(rule_id="VOODA-SEC-1PASS-001", title="1Password Connect Token", secret_type="onepassword_token", severity="critical",
        pattern=r'(?:^|[^A-Za-z0-9])(ops_[A-Za-z0-9]{43,})(?:[^A-Za-z0-9]|$)',
        keywords=["ops_"], confidence=0.95, description="1Password Connect server token.", fix_hint="Revoke at 1Password → Integrations → Connect."),
    SecretRule(rule_id="VOODA-SEC-PREFECT-001", title="Prefect Cloud API Key", secret_type="prefect_key", severity="high",
        pattern=r'(?:^|[^A-Za-z0-9])(pnu_[A-Za-z0-9]{36,})(?:[^A-Za-z0-9]|$)',
        keywords=["pnu_"], confidence=0.95, description="Prefect Cloud API key.", fix_hint="Revoke at Prefect Cloud → API Keys."),
    SecretRule(rule_id="VOODA-SEC-DAGSTER-001", title="Dagster Cloud Token", secret_type="dagster_token", severity="high",
        pattern=r'(?:dagster[_-]?cloud[_-]?(?:agent[_-]?)?token|DAGSTER_CLOUD_AGENT_TOKEN)\s*[=:]\s*["\']?([A-Za-z0-9\-_:]{30,})["\']?',
        keywords=["dagster", "DAGSTER"], confidence=0.75, description="Dagster Cloud agent token.", fix_hint="Regenerate at Dagster Cloud → Settings."),
    SecretRule(rule_id="VOODA-SEC-DBTCLOUD-001", title="dbt Cloud API Token", secret_type="dbt_cloud_token", severity="high",
        pattern=r'(?:dbt[_-]?cloud[_-]?(?:api[_-]?)?token|DBT_CLOUD_TOKEN|DBT_API_KEY)\s*[=:]\s*["\']?([a-f0-9]{40})["\']?',
        keywords=["dbt_cloud", "DBT_CLOUD", "DBT_API"], confidence=0.80, description="dbt Cloud API token.", fix_hint="Regenerate at dbt Cloud → Account Settings → API Access."),
    SecretRule(rule_id="VOODA-SEC-AIRBYTE-001", title="Airbyte API Token", secret_type="airbyte_token", severity="high",
        pattern=r'(?:airbyte[_-]?(?:api[_-]?)?(?:token|key)|AIRBYTE_(?:API_)?(?:TOKEN|KEY))\s*[=:]\s*["\']?([A-Za-z0-9\-_]{30,})["\']?',
        keywords=["airbyte", "AIRBYTE"], confidence=0.70, description="Airbyte data integration platform token.", fix_hint="Regenerate at Airbyte Cloud → Settings."),
    SecretRule(rule_id="VOODA-SEC-FIVETRAN-002", title="Fivetran API Key", secret_type="fivetran_key", severity="high",
        pattern=r'(?:fivetran[_-]?(?:api[_-]?)?key|FIVETRAN_API_KEY)\s*[=:]\s*["\']?([A-Za-z0-9]{20,})["\']?',
        keywords=["fivetran", "FIVETRAN"], confidence=0.75, description="Fivetran data connector API key.", fix_hint="Regenerate at Fivetran → Account Settings → API Config."),
]
