# SPDX-FileCopyrightText: 2026 Virantis
# SPDX-License-Identifier: LicenseRef-Vooda-Community-1.0

from __future__ import annotations
"""
TruffleHog Port — Stage 1 rule expansion.

Adds detection rules for ~100 widely-used SaaS providers that Vooda
did not previously cover. Each rule targets a credential format that
is cryptographically distinct (provider-specific prefix + charset +
length) so precision stays high without needing live verification.

Rules are grouped by category for maintenance. Every pattern has been
checked against the provider's public API documentation or published
token format specification.

Categories covered:
  - Observability / Monitoring
  - AI / LLM providers (long tail)
  - Payment / Fintech
  - Developer tools / CI
  - Databases / Data platforms
  - Communication / Email
  - Marketing / Analytics
  - Cloud infrastructure (non-AWS/GCP/Azure)
  - Productivity / PM
  - Identity / Auth (long tail)
"""

from services.secret_scan.detectors.base import SecretRule


RULES: list[SecretRule] = [

    # ── Observability / Monitoring ────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-NEWRELIC-INGEST-001",
        title="New Relic Ingest License Key",
        secret_type="newrelic_license_key",
        severity="high",
        pattern=r'\b([A-Fa-f0-9]{40}NRAL|NRAK-[A-Z0-9]{27})\b',
        keywords=["NRAL", "NRAK-", "newrelic", "NEW_RELIC"],
        confidence=0.97,
        description="New Relic license/ingest key. Allows sending metrics/traces to a NR account.",
        fix_hint="Revoke at New Relic → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-NEWRELIC-USER-001",
        title="New Relic User API Key",
        secret_type="newrelic_user_key",
        severity="critical",
        pattern=r'\b(NRAK-[A-Z0-9]{27}|NRRA-[A-Z0-9]{42})\b',
        keywords=["NRAK-", "NRRA-"],
        confidence=0.98,
        description="New Relic user API key. Full account management access.",
        fix_hint="Revoke at New Relic → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-BUGSNAG-001",
        title="Bugsnag API Key",
        secret_type="bugsnag_api_key",
        severity="medium",
        pattern=r'(?i)bugsnag[^\n]{0,50}\b([a-f0-9]{32})\b|\b([a-f0-9]{32})\b[^\n]{0,50}bugsnag',
        keywords=["bugsnag", "BUGSNAG"],
        confidence=0.85,
        description="Bugsnag error-reporting API key.",
        fix_hint="Rotate at Bugsnag → Settings → Data Forwarders.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DYNATRACE-001",
        title="Dynatrace API Token",
        secret_type="dynatrace_api_token",
        severity="critical",
        pattern=r'\b(dt0[a-z]\d{2}\.[A-Z0-9]{24}\.[A-Z0-9]{64})\b',
        keywords=["dt0c", "dt0a", "dynatrace"],
        confidence=0.99,
        description="Dynatrace API token. APM, RUM, and admin access.",
        fix_hint="Revoke at Dynatrace → Access Tokens.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-HONEYCOMB-001",
        title="Honeycomb API Key",
        secret_type="honeycomb_api_key",
        severity="high",
        pattern=r'\b(hc(?:aic|aik|aia|bik|bia|bik)_[a-z0-9]{58})\b',
        keywords=["hcaic_", "hcaik_", "hcbik_", "honeycomb"],
        confidence=0.98,
        description="Honeycomb.io ingest or configuration API key.",
        fix_hint="Revoke at honeycomb.io → Team Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SUMOLOGIC-001",
        title="Sumo Logic Access Key",
        secret_type="sumologic_access_key",
        severity="critical",
        pattern=r'\b(su[A-Za-z0-9]{12}[A-Za-z0-9]{64})\b',
        keywords=["sumologic", "SUMO_LOGIC", "sumo_access"],
        confidence=0.92,
        description="Sumo Logic access ID + access key. Log ingest + query access.",
        fix_hint="Revoke at Sumo Logic → Preferences → Access Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LOGDNA-001",
        title="LogDNA / Mezmo Ingestion Key",
        secret_type="logdna_ingestion_key",
        severity="high",
        pattern=r'(?i)(?:mezmo|logdna)[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["logdna", "mezmo", "LOGDNA_KEY"],
        confidence=0.88,
        description="LogDNA / Mezmo log-ingestion key.",
        fix_hint="Rotate at mezmo.com → Settings → Organization → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LOGGLY-001",
        title="Loggly API Token",
        secret_type="loggly_api_token",
        severity="medium",
        pattern=r'(?i)loggly[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["loggly", "LOGGLY"],
        confidence=0.90,
        description="Loggly customer token (UUID format).",
        fix_hint="Rotate at Loggly → Source Setup.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SPLUNK-HEC-001",
        title="Splunk HEC Token",
        secret_type="splunk_hec_token",
        severity="high",
        pattern=r'\bSplunk\s+([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["Splunk", "SPLUNK_HEC"],
        confidence=0.97,
        description="Splunk HEC (HTTP Event Collector) token.",
        fix_hint="Revoke at Splunk → Settings → Data Inputs → HTTP Event Collector.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-RAYGUN-001",
        title="Raygun API Key",
        secret_type="raygun_api_key",
        severity="medium",
        pattern=r'(?i)raygun[^\n]{0,50}\b([A-Za-z0-9+/=]{22,28})\b',
        keywords=["raygun", "RAYGUN_API"],
        confidence=0.82,
        description="Raygun error monitoring API key.",
        fix_hint="Rotate at raygun.com → Application Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-APPDYNAMICS-002",
        title="AppDynamics API Access Key",
        secret_type="appdynamics_access_key",
        severity="high",
        pattern=r'(?i)appdynamics[^\n]{0,50}\b([A-Za-z0-9]{40,})\b',
        keywords=["appdynamics", "APPDYNAMICS"],
        confidence=0.80,
        description="AppDynamics API access key.",
        fix_hint="Rotate at AppDynamics → Settings → API Clients.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-OPSGENIE-001",
        title="Opsgenie API Key",
        secret_type="opsgenie_api_key",
        severity="high",
        pattern=r'(?i)opsgenie[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["opsgenie", "OPSGENIE"],
        confidence=0.93,
        description="Opsgenie alert API key. Can create/route incidents.",
        fix_hint="Revoke at Opsgenie → Settings → Integrations → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-COUNTLY-001",
        title="Countly App Key",
        secret_type="countly_app_key",
        severity="medium",
        pattern=r'(?i)countly[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["countly", "COUNTLY"],
        confidence=0.85,
        description="Countly analytics app key.",
        fix_hint="Rotate at Countly → Application Management.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SIGNALFX-001",
        title="SignalFX / Splunk Observability Token",
        secret_type="signalfx_token",
        severity="high",
        pattern=r'(?i)(?:signalfx|splunk.*obs)[^\n]{0,60}\b([A-Za-z0-9_-]{22})\b',
        keywords=["signalfx", "SIGNALFX", "splunkobs"],
        confidence=0.85,
        description="SignalFX (Splunk Observability Cloud) access token.",
        fix_hint="Rotate at Splunk Observability → Access Tokens.",
    ),

    # ── AI / LLM Providers ────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-ASSEMBLYAI-001",
        title="AssemblyAI API Key",
        secret_type="assemblyai_api_key",
        severity="high",
        pattern=r'(?i)assemblyai[^\n]{0,50}\b([a-f0-9]{32})\b|\b([a-f0-9]{32})\b[^\n]{0,50}assemblyai',
        keywords=["assemblyai", "ASSEMBLYAI"],
        confidence=0.90,
        description="AssemblyAI speech-to-text API key.",
        fix_hint="Revoke at assemblyai.com → Dashboard → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DEEPGRAM-001",
        title="Deepgram API Key",
        secret_type="deepgram_api_key",
        severity="high",
        # Use inline (?i:...) on the second arm so the flag isn't at the top
        pattern=r'\bToken\s+([a-f0-9]{40})\b|(?i:deepgram)[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["deepgram", "DEEPGRAM"],
        confidence=0.90,
        description="Deepgram speech-to-text API key.",
        fix_hint="Revoke at console.deepgram.com → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MISTRAL-001",
        title="Mistral API Key",
        secret_type="mistral_api_key",
        severity="high",
        pattern=r'(?i)mistral[^\n]{0,50}\b([A-Za-z0-9]{32})\b|\bMistral[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["mistral", "MISTRAL"],
        confidence=0.88,
        description="Mistral AI platform API key.",
        fix_hint="Revoke at console.mistral.ai → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-STABILITY-001",
        title="Stability AI API Key",
        secret_type="stability_api_key",
        severity="high",
        pattern=r'\b(sk-[A-Za-z0-9]{48})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['stability'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["stability", "STABILITY_API"],
        confidence=0.90,
        description="Stability AI (Stable Diffusion) API key.",
        fix_hint="Revoke at platform.stability.ai → Account.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CLARIFAI-001",
        title="Clarifai Personal Access Token",
        secret_type="clarifai_pat",
        severity="high",
        pattern=r'(?i)clarifai[^\n]{0,50}\bKey\s+([a-f0-9]{32})\b',
        keywords=["clarifai", "CLARIFAI"],
        confidence=0.95,
        description="Clarifai computer-vision PAT.",
        fix_hint="Revoke at clarifai.com → Security → Personal Access Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HUGGINGFACE-001",
        title="Hugging Face Access Token",
        secret_type="huggingface_token",
        severity="high",
        pattern=r'\b(hf_[A-Za-z0-9]{34})\b',
        keywords=["hf_", "huggingface"],
        confidence=0.99,
        description="Hugging Face Hub access token. Model read/write + inference access.",
        fix_hint="Revoke at huggingface.co → Settings → Access Tokens.",
    ),
    SecretRule(
        # Renamed -001 → -002 during P4 (2026-05-22, Track-A collision audit):
        # collided with trufflehog_port_v5.py's TOGETHER-AI-001 (broader keyword
        # set, looser context window).  Both detectors valid; rename gives them
        # independent identity so both fire.
        rule_id="VOODA-SEC-TOGETHER-AI-002",
        title="Together AI API Key",
        secret_type="together_ai_api_key",
        severity="high",
        pattern=r'\b([a-f0-9]{64})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['together.?ai', 'TOGETHER_API'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["together", "TOGETHER_API"],
        confidence=0.88,
        description="Together AI inference platform API key.",
        fix_hint="Revoke at api.together.ai → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LANGSMITH-001",
        title="LangSmith API Key",
        secret_type="langsmith_api_key",
        severity="high",
        pattern=r'\b(ls__[A-Za-z0-9]{32,40}|lsv2_(?:pt|sk)_[a-z0-9]{32}_[a-z0-9]{10})\b',
        keywords=["langsmith", "ls__", "lsv2_"],
        confidence=0.98,
        description="LangChain LangSmith observability API key.",
        fix_hint="Revoke at smith.langchain.com → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-WRITER-COM-001",
        title="Writer.com API Key",
        secret_type="writer_com_api_key",
        severity="medium",
        pattern=r'\b(Writer-\w{8}-\w{4}-\w{4}-\w{4}-\w{12})\b',
        keywords=["Writer-", "writer.com"],
        confidence=0.95,
        description="Writer.com generative-AI API key.",
        fix_hint="Revoke at writer.com → Account → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-EDENAI-001",
        title="Eden AI API Key",
        secret_type="edenai_api_key",
        severity="medium",
        pattern=r'(?i)eden\s?ai[^\n]{0,50}\b(eyJ[A-Za-z0-9_-]{80,500}\.[A-Za-z0-9_-]{60,200})\b',
        keywords=["edenai", "EDEN_AI"],
        confidence=0.92,
        description="Eden AI multi-model router API key (JWT format).",
        fix_hint="Revoke at edenai.co → Dashboard → Settings.",
    ),

    # ── Payment / Fintech ─────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-BRAINTREE-001",
        title="Braintree Access Token (Live)",
        secret_type="braintree_live_token",
        severity="critical",
        pattern=r'\b(access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32})\b',
        keywords=["access_token$production$", "braintree"],
        confidence=0.99,
        description="Braintree (PayPal) production access token. Full payment gateway access.",
        fix_hint="Revoke at Braintree → Account → My User → Authorizations.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BRAINTREE-SANDBOX-001",
        title="Braintree Access Token (Sandbox)",
        secret_type="braintree_sandbox_token",
        severity="medium",
        pattern=r'\b(access_token\$sandbox\$[0-9a-z]{16}\$[0-9a-f]{32})\b',
        keywords=["access_token$sandbox$"],
        confidence=0.99,
        description="Braintree sandbox access token.",
        fix_hint="Revoke at Braintree → Sandbox → Authorizations.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-RAZORPAY-LIVE-001",
        title="Razorpay Live Key (Secret)",
        secret_type="razorpay_live_secret",
        severity="critical",
        pattern=r'\b(rzp_live_[A-Za-z0-9]{14,30})\b(?:\s*[:=,\s]+\s*[\'"]?)([A-Za-z0-9]{24})',
        keywords=["rzp_live_", "razorpay"],
        confidence=0.97,
        description="Razorpay live API key ID + secret. Indian payment gateway.",
        fix_hint="Rotate at razorpay.com → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PADDLE-API-001",
        title="Paddle API Key",
        secret_type="paddle_api_key",
        severity="critical",
        pattern=r'\b(pdl_(?:live|sandbox)_apikey_[A-Za-z0-9]{40,})\b',
        keywords=["pdl_live_apikey_", "pdl_sandbox_apikey_"],
        confidence=0.99,
        description="Paddle billing API key.",
        fix_hint="Revoke at vendors.paddle.com → Developer Tools.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PAYSTACK-LIVE-001",
        title="Paystack Live Secret Key",
        secret_type="paystack_secret_key",
        severity="critical",
        pattern=r'\b(sk_live_[a-f0-9]{40})\b',
        keywords=["sk_live_", "paystack"],
        confidence=0.95,
        description="Paystack live secret key. Full African payment gateway access.",
        fix_hint="Rotate at paystack.com → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SQUARE-ACCESS-001",
        title="Square Access Token",
        secret_type="square_access_token",
        severity="critical",
        pattern=r'\b(EAAA[A-Za-z0-9_-]{60})\b',
        keywords=["EAAA", "square"],
        confidence=0.96,
        description="Square production OAuth access token.",
        fix_hint="Revoke at developer.squareup.com → Apps → OAuth.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SQUARE-APP-SECRET-001",
        title="Square Application Secret",
        secret_type="square_app_secret",
        severity="critical",
        pattern=r'\b(sq0csp-[A-Za-z0-9_-]{43})\b',
        keywords=["sq0csp-", "square"],
        confidence=0.99,
        description="Square application secret for OAuth.",
        fix_hint="Rotate at developer.squareup.com → Apps.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PLAID-CLIENT-001",
        title="Plaid Secret",
        secret_type="plaid_secret",
        severity="critical",
        pattern=r'(?i)plaid_?(?:secret|PLAID_SECRET)[^\n]{0,50}\b([a-f0-9]{30})\b',
        keywords=["plaid", "PLAID_SECRET"],
        confidence=0.92,
        description="Plaid banking API secret. Account linking + data access.",
        fix_hint="Rotate at dashboard.plaid.com → Team Settings → Keys.",
    ),
        # VOODA-SEC-DWOLLA-001 removed 2026-05-22 (Track-A Phase 1, collision audit) —
    # shadow of live rule in trufflehog_port_v5.py; shadow has narrower length bound (live covers 50-64).
    # Removal restored 1 dead-code rule to the registry's correct
    # state (was silently shadowed by last-wins dedup).
    SecretRule(
        rule_id="VOODA-SEC-XERO-TOKEN-001",
        title="Xero Bearer Token",
        secret_type="xero_bearer_token",
        severity="critical",
        pattern=r'(?i)xero[^\n]{0,50}\b(eyJ[A-Za-z0-9_-]{80,600}\.[A-Za-z0-9_-]{60,300})\b',
        keywords=["xero", "XERO"],
        confidence=0.90,
        description="Xero accounting API bearer token.",
        fix_hint="Revoke at developer.xero.com → My Apps.",
    ),

    # ── Developer Tools / CI ──────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-BITRISE-001",
        title="Bitrise API Access Token",
        secret_type="bitrise_access_token",
        severity="high",
        # 2-pass: lookahead → post_filter_* (Option B-1b manual rewrite,
        # 2026-05-24).  Original had asymmetric token shapes —
        # `{40}-{10}` vs `{40,50}` — almost certainly a typo since the
        # real Bitrise token format is exactly `{40}-{10}`.  Kept the
        # more specific shape (matches real tokens, drops the
        # `{40,50}` false-positive surface).
        pattern=r'\b([A-Za-z0-9_-]{40}-[A-Za-z0-9_-]{10})\b',
        post_filter_keywords=['bitrise'],
        post_filter_window=80,
        post_filter_direction='both',
        keywords=["bitrise", "BITRISE"],
        confidence=0.88,
        description="Bitrise mobile CI personal access token.",
        fix_hint="Revoke at app.bitrise.io → Account Settings → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CODEMAGIC-001",
        title="Codemagic API Token",
        secret_type="codemagic_api_token",
        severity="high",
        pattern=r'(?i)codemagic[^\n]{0,50}\b([A-Za-z0-9_-]{43,50})\b',
        keywords=["codemagic", "CODEMAGIC"],
        confidence=0.82,
        description="Codemagic Flutter/iOS CI API token.",
        fix_hint="Revoke at codemagic.io → Teams → Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-JFROG-API-001",
        title="JFrog Artifactory API Key",
        secret_type="jfrog_api_key",
        severity="critical",
        pattern=r'\b(AKCp[0-9A-Za-z]{69})\b',
        keywords=["AKCp", "jfrog", "artifactory"],
        confidence=0.99,
        description="JFrog Artifactory API key (AKCp prefix).",
        fix_hint="Revoke at Artifactory → Edit Profile → API Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-JFROG-IDENT-001",
        title="JFrog Access Token (Reference)",
        secret_type="jfrog_access_token",
        severity="critical",
        pattern=r'\b(AKC[A-Za-z0-9]{10}\.[A-Za-z0-9]{50,100})\b',
        keywords=["AKC", "jfrog"],
        confidence=0.95,
        description="JFrog reference-format access token.",
        fix_hint="Revoke at Artifactory → Identity and Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TEAMCITY-001",
        title="TeamCity API Token",
        secret_type="teamcity_api_token",
        severity="high",
        pattern=r'\b(eyJ0eXAiOi\s?JUQ1NnIi[A-Za-z0-9_.-]{30,})\b',
        keywords=["TeamCity", "teamcity"],
        confidence=0.88,
        description="JetBrains TeamCity CI API token.",
        fix_hint="Revoke at TeamCity → My Settings & Tools → Access Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BUILDKITE-001",
        title="Buildkite Agent Token",
        secret_type="buildkite_agent_token",
        severity="high",
        pattern=r'\b(bkua_[A-Za-z0-9]{40})\b',
        keywords=["bkua_", "buildkite"],
        confidence=0.98,
        description="Buildkite agent registration token.",
        fix_hint="Rotate at buildkite.com → Agents → Agent Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DRONE-CI-001",
        title="Drone CI Token",
        secret_type="drone_ci_token",
        severity="high",
        pattern=r'(?i)drone[^\n]{0,50}\b([A-Za-z0-9]{40})\b',
        keywords=["drone", "DRONE_TOKEN"],
        confidence=0.80,
        description="Drone CI personal token.",
        fix_hint="Revoke at Drone → Account Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LAUNCHDARKLY-001",
        title="LaunchDarkly API Key",
        secret_type="launchdarkly_api_key",
        severity="high",
        pattern=r'\b(api-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["api-", "launchdarkly"],
        confidence=0.93,
        description="LaunchDarkly feature-flag API key.",
        fix_hint="Rotate at launchdarkly.com → Account Settings → Authorization.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SONARCLOUD-001",
        title="SonarCloud Token",
        secret_type="sonarcloud_token",
        severity="high",
        pattern=r'\b(squ_[a-f0-9]{40})\b',
        keywords=["squ_", "sonarcloud", "SONAR_TOKEN"],
        confidence=0.98,
        description="SonarCloud user access token.",
        fix_hint="Revoke at sonarcloud.io → My Account → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SONARQUBE-001",
        title="SonarQube Token (sqp)",
        secret_type="sonarqube_token",
        severity="high",
        pattern=r'\b(sqp_[a-f0-9]{40})\b',
        keywords=["sqp_", "sonarqube"],
        confidence=0.98,
        description="SonarQube project access token.",
        fix_hint="Revoke at SonarQube → My Account → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SONAR-USER-001",
        title="SonarQube User Token",
        secret_type="sonarqube_user_token",
        severity="high",
        pattern=r'\b(squ_[a-f0-9]{40}|sqa_[a-f0-9]{40})\b',
        keywords=["squ_", "sqa_"],
        confidence=0.98,
        description="SonarQube user or analysis token.",
        fix_hint="Revoke at SonarQube → My Account → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CODECLIMATE-001",
        title="CodeClimate Test Reporter ID",
        secret_type="codeclimate_token",
        severity="medium",
        pattern=r'(?i)code.?climate[^\n]{0,50}\b([a-f0-9]{64})\b',
        keywords=["codeclimate", "CODECLIMATE", "CC_TEST_REPORTER_ID"],
        confidence=0.90,
        description="CodeClimate Quality test reporter ID.",
        fix_hint="Rotate at codeclimate.com → Repo Settings → Test Coverage.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-POSTMAN-API-001",
        title="Postman API Key (PMAK)",
        secret_type="postman_api_key",
        severity="high",
        pattern=r'\b(PMAK-[a-f0-9]{24}-[a-f0-9]{34})\b',
        keywords=["PMAK-", "postman"],
        confidence=0.99,
        description="Postman API key. Can access and modify workspaces/collections.",
        fix_hint="Revoke at postman.com → Integrations → API Keys.",
    ),
    # VOODA-SEC-TERRAFORM-CLOUD-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-TERRAFORM-CLOUD-V2-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.

    # ── Databases / Data Platforms ────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-COCKROACH-CLOUD-001",
        title="CockroachDB Cloud API Key",
        secret_type="cockroach_cloud_key",
        severity="critical",
        pattern=r'\b(CCDB1_[A-Za-z0-9_-]{50,80})\b',
        keywords=["CCDB1_", "cockroachdb"],
        confidence=0.98,
        description="CockroachDB Cloud API key.",
        fix_hint="Revoke at cockroachlabs.cloud → Access Management.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FAUNA-001",
        title="Fauna Secret",
        secret_type="fauna_secret",
        severity="critical",
        pattern=r'\b(fn[A-Za-z0-9_-]{60})\b',
        keywords=["fnA", "fnE", "fauna"],
        confidence=0.97,
        description="Fauna database secret. Full DB access with configured permissions.",
        fix_hint="Revoke at dashboard.fauna.com → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-AIVEN-001",
        title="Aiven API Token",
        secret_type="aiven_api_token",
        severity="critical",
        pattern=r'\b(AVNS_[A-Za-z0-9_-]{16,60})\b',
        keywords=["AVNS_", "aiven"],
        confidence=0.98,
        description="Aiven managed-DB service API token.",
        fix_hint="Revoke at console.aiven.io → User Information → Access Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ELASTIC-CLOUD-001",
        title="Elastic Cloud API Key",
        secret_type="elastic_cloud_api_key",
        severity="high",
        pattern=r'(?i)elastic.*cloud[^\n]{0,50}\b([A-Za-z0-9+/=_-]{60,100})\b',
        keywords=["elastic_cloud", "ELASTIC_CLOUD", "ES_API_KEY"],
        confidence=0.85,
        description="Elasticsearch Cloud API key.",
        fix_hint="Revoke at cloud.elastic.co → Deployment → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MOTHERDUCK-001",
        title="MotherDuck Service Token",
        secret_type="motherduck_token",
        severity="critical",
        pattern=r'\b(motherduck_token[\s:=]+[A-Za-z0-9_-]{20,80})\b|\beyJ[A-Za-z0-9_-]{100,500}\.[A-Za-z0-9_-]{60,200}\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['motherduck'],
        post_filter_window=80,
        keywords=["motherduck", "MOTHERDUCK"],
        confidence=0.88,
        description="MotherDuck serverless DuckDB service token (JWT).",
        fix_hint="Revoke at app.motherduck.com → Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-NEO4J-AURA-001",
        title="Neo4j Aura Password",
        secret_type="neo4j_aura_password",
        severity="critical",
        pattern=r'(?i)neo4j[^\n]{0,50}\b([A-Za-z0-9_-]{24,})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['aura'],
        post_filter_window=120,
        keywords=["neo4j", "NEO4J", "aura"],
        confidence=0.85,
        description="Neo4j Aura graph DB password.",
        fix_hint="Rotate at console.neo4j.io → Instance → Credentials.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PLANETSCALE-PW-001",
        title="PlanetScale Database Password",
        secret_type="planetscale_db_password",
        severity="critical",
        pattern=r'\b(pscale_pw_[A-Za-z0-9_]{40,64})\b',
        keywords=["pscale_pw_", "planetscale"],
        confidence=0.99,
        description="PlanetScale MySQL DB password.",
        fix_hint="Rotate at planetscale.com → Database → Passwords.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PLANETSCALE-OAUTH-001",
        title="PlanetScale OAuth Token",
        secret_type="planetscale_oauth_token",
        severity="critical",
        pattern=r'\b(pscale_oauth_[A-Za-z0-9_]{43,64})\b',
        keywords=["pscale_oauth_"],
        confidence=0.99,
        description="PlanetScale OAuth app access token.",
        fix_hint="Revoke at planetscale.com → Settings → OAuth Applications.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PLANETSCALE-TKN-001",
        title="PlanetScale Service Token",
        secret_type="planetscale_service_token",
        severity="critical",
        pattern=r'\b(pscale_tkn_[A-Za-z0-9_]{40,64})\b',
        keywords=["pscale_tkn_"],
        confidence=0.99,
        description="PlanetScale service token.",
        fix_hint="Revoke at planetscale.com → Settings → Service Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CLICKHOUSE-001",
        title="ClickHouse Cloud API Key",
        secret_type="clickhouse_cloud_key",
        severity="critical",
        pattern=r'\b(chsc_[A-Za-z0-9_-]{30,60})\b',
        keywords=["chsc_", "clickhouse"],
        confidence=0.98,
        description="ClickHouse Cloud service key.",
        fix_hint="Rotate at console.clickhouse.cloud → Service → API Keys.",
    ),

    # ── Communication / Email / SMS ───────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-POSTMARK-API-001",
        title="Postmark Server API Token",
        secret_type="postmark_server_token",
        severity="high",
        pattern=r'(?i)postmark[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["postmark", "POSTMARK"],
        confidence=0.94,
        description="Postmark transactional email server API token.",
        fix_hint="Rotate at postmarkapp.com → Servers → API Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MANDRILL-001",
        title="Mandrill API Key",
        secret_type="mandrill_api_key",
        severity="high",
        pattern=r'(?i)mandrill[^\n]{0,50}\b(md-[A-Za-z0-9_-]{22,})\b',
        keywords=["mandrill", "md-"],
        confidence=0.97,
        description="Mandrill (Mailchimp Transactional) API key.",
        fix_hint="Rotate at Mailchimp → Transactional Email → SMTP & API Info.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MAILJET-PUB-001",
        title="Mailjet Public API Key",
        secret_type="mailjet_public_key",
        severity="medium",
        pattern=r'(?i)mailjet[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["mailjet", "MAILJET"],
        confidence=0.85,
        description="Mailjet public API key.",
        fix_hint="Rotate at mailjet.com → Account Settings → REST API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-NEXMO-API-001",
        title="Vonage / Nexmo API Secret",
        secret_type="vonage_api_secret",
        severity="high",
        pattern=r'(?i)(?:vonage|nexmo)[^\n]{0,50}\b([A-Za-z0-9]{16})\b',
        keywords=["nexmo", "vonage", "NEXMO", "VONAGE"],
        confidence=0.85,
        description="Vonage (formerly Nexmo) SMS/Voice API secret.",
        fix_hint="Rotate at dashboard.nexmo.com → Getting Started.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TELNYX-001",
        title="Telnyx API Key",
        secret_type="telnyx_api_key",
        severity="high",
        pattern=r'\b(KEY[0-9A-F]{32}_[A-Za-z0-9]{22})\b',
        keywords=["KEY0", "telnyx"],
        confidence=0.96,
        description="Telnyx SMS/Voice API key.",
        fix_hint="Revoke at portal.telnyx.com → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PLIVO-001",
        title="Plivo Auth Token",
        secret_type="plivo_auth_token",
        severity="high",
        pattern=r'(?i)plivo[^\n]{0,50}\b([A-Za-z0-9]{40})\b',
        keywords=["plivo", "PLIVO"],
        confidence=0.85,
        description="Plivo SMS/Voice auth token.",
        fix_hint="Rotate at console.plivo.com → Account → Auth Token.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SIGNALWIRE-001",
        title="SignalWire API Token",
        secret_type="signalwire_api_token",
        severity="high",
        pattern=r'\bPT[a-f0-9]{50}\b',
        keywords=["PT", "signalwire"],
        confidence=0.85,
        description="SignalWire voice/video API token.",
        fix_hint="Rotate at signalwire.com → API → Credentials.",
    ),

    # ── Marketing / Analytics ─────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-AMPLITUDE-SECRET-002",
        title="Amplitude API Secret Key",
        secret_type="amplitude_secret_key",
        severity="high",
        pattern=r'(?i)amplitude[^\n]{0,80}(?:secret|SECRET)[^\n]{0,30}\b([a-f0-9]{32})\b',
        keywords=["amplitude", "AMPLITUDE_SECRET"],
        confidence=0.92,
        description="Amplitude analytics secret key.",
        fix_hint="Rotate at amplitude.com → Project Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HOTJAR-001",
        title="Hotjar API Key",
        secret_type="hotjar_api_key",
        severity="medium",
        pattern=r'(?i)hotjar[^\n]{0,50}\b([A-Za-z0-9_-]{40,})\b',
        keywords=["hotjar", "HOTJAR"],
        confidence=0.80,
        description="Hotjar analytics API key.",
        fix_hint="Rotate at insights.hotjar.com → Site Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-KLAVIYO-PRIVATE-001",
        title="Klaviyo Private API Key",
        secret_type="klaviyo_private_key",
        severity="critical",
        pattern=r'\b(pk_[a-f0-9]{34})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['klaviyo'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["pk_", "klaviyo", "KLAVIYO"],
        confidence=0.92,
        description="Klaviyo private email marketing API key.",
        fix_hint="Revoke at klaviyo.com → Account → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TYPEFORM-001",
        title="Typeform Personal Access Token",
        secret_type="typeform_pat",
        severity="high",
        pattern=r'(?i)typeform[^\n]{0,50}\b(tfp_[A-Za-z0-9_-]{50,80})\b',
        keywords=["tfp_", "typeform"],
        confidence=0.99,
        description="Typeform personal access token.",
        fix_hint="Revoke at typeform.com → Account → Personal tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CUSTOMERIO-001",
        title="Customer.io API Key",
        secret_type="customerio_api_key",
        severity="high",
        pattern=r'(?i)customer\.io[^\n]{0,50}\b([a-f0-9]{20})\b',
        keywords=["customer.io", "CUSTOMERIO"],
        confidence=0.88,
        description="Customer.io tracking API key.",
        fix_hint="Rotate at customer.io → Settings → API Credentials.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BRAZE-001",
        title="Braze API Key",
        secret_type="braze_api_key",
        severity="high",
        pattern=r'(?i)braze[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["braze", "BRAZE"],
        confidence=0.92,
        description="Braze marketing automation API key.",
        fix_hint="Rotate at dashboard.braze.com → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MAPBOX-001",
        title="Mapbox Access Token (Secret)",
        secret_type="mapbox_access_token",
        severity="high",
        pattern=r'\b(sk\.eyJ[A-Za-z0-9_-]{60,200}\.[A-Za-z0-9_-]{20,50})\b',
        keywords=["sk.eyJ", "mapbox"],
        confidence=0.99,
        description="Mapbox secret access token. Full map API access.",
        fix_hint="Revoke at account.mapbox.com → Access Tokens.",
    ),

    # ── Cloud Infrastructure ─────────────────────────────────────
    # VOODA-SEC-LINODE-V4-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-LINODE-PAT-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.
    SecretRule(
        rule_id="VOODA-SEC-SCALEWAY-001",
        title="Scaleway Secret Key",
        secret_type="scaleway_secret_key",
        severity="critical",
        pattern=r'\b([A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['scaleway'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["scaleway", "SCALEWAY"],
        confidence=0.90,
        description="Scaleway cloud secret key.",
        fix_hint="Rotate at console.scaleway.com → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-VULTR-API-001",
        title="Vultr API Key",
        secret_type="vultr_api_key",
        severity="critical",
        pattern=r'\b([A-Z0-9]{36})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['vultr'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["vultr", "VULTR"],
        confidence=0.88,
        description="Vultr cloud API key.",
        fix_hint="Revoke at my.vultr.com → Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BACKBLAZE-B2-002",
        title="Backblaze B2 Application Key",
        secret_type="backblaze_b2_app_key",
        severity="critical",
        pattern=r'\b(K[0-9]{3}[A-Za-z0-9+/]{28,40})\b',
        keywords=["backblaze", "B2_APP_KEY", "BACKBLAZE_B2"],
        confidence=0.92,
        description="Backblaze B2 cloud-storage application key.",
        fix_hint="Revoke at secure.backblaze.com → App Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-OVH-001",
        title="OVH Consumer Key",
        secret_type="ovh_consumer_key",
        severity="high",
        pattern=r'(?i)ovh[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["ovh", "OVH"],
        confidence=0.82,
        description="OVH cloud consumer key.",
        fix_hint="Revoke at api.ovh.com → Token Management.",
    ),
    # VOODA-SEC-HETZNER-API-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-HETZNER-CLOUD-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.

    # ── Productivity / PM ────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-AIRTABLE-001",
        title="Airtable Personal Access Token",
        secret_type="airtable_pat",
        severity="high",
        pattern=r'\b(pat[A-Za-z0-9]{14}\.[a-f0-9]{64})\b',
        keywords=["pat", "airtable"],
        confidence=0.99,
        description="Airtable personal access token.",
        fix_hint="Revoke at airtable.com/create/tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-AIRTABLE-LEGACY-001",
        title="Airtable Legacy API Key",
        secret_type="airtable_legacy_key",
        severity="high",
        pattern=r'\b(key[A-Za-z0-9]{14})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['airtable'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["airtable", "AIRTABLE", "keyA", "keyo"],
        confidence=0.95,
        description="Airtable legacy API key (being deprecated in favor of PATs).",
        fix_hint="Migrate to PAT at airtable.com/create/tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TRELLO-001",
        title="Trello API Key",
        secret_type="trello_api_key",
        severity="medium",
        pattern=r'(?i)trello[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["trello", "TRELLO"],
        confidence=0.85,
        description="Trello API key.",
        fix_hint="Rotate at trello.com/power-ups/admin.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MONDAY-COM-001",
        title="Monday.com API Key",
        secret_type="monday_com_api_key",
        severity="high",
        # 2-pass: lookahead → post_filter_* (Option B-1b manual rewrite,
        # 2026-05-24).  Asymmetric token shapes — half 1 was full JWT
        # (header.body), half 2 was just the header.  Kept full JWT
        # shape; real Monday tokens always include both segments.
        pattern=r'\b(eyJhbGciOi[A-Za-z0-9_-]{80,500}\.[A-Za-z0-9_-]{60,200})\b',
        post_filter_keywords=['monday'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["monday", "MONDAY_API_KEY"],
        confidence=0.88,
        description="Monday.com personal API token.",
        fix_hint="Revoke at monday.com → Admin → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SMARTSHEET-001",
        title="Smartsheet Access Token",
        secret_type="smartsheet_token",
        severity="high",
        pattern=r'(?i)smartsheet[^\n]{0,50}\b([a-z0-9]{26})\b',
        keywords=["smartsheet", "SMARTSHEET"],
        confidence=0.90,
        description="Smartsheet API access token.",
        fix_hint="Rotate at app.smartsheet.com → Personal Settings → API Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CALENDLY-001",
        title="Calendly Personal Access Token",
        secret_type="calendly_pat",
        severity="medium",
        # 2-pass: lookahead → post_filter_* (Option B-1b manual rewrite,
        # 2026-05-24).  Asymmetric token shapes — half 1 was full
        # 3-segment JWT, half 2 was just the header.  Kept full JWT
        # shape; real Calendly PATs are always full JWTs.
        pattern=r'\b(eyJraWQiOi[A-Za-z0-9_-]{50,}\.[A-Za-z0-9_-]{80,300}\.[A-Za-z0-9_-]{40,200})\b',
        post_filter_keywords=['calendly'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["calendly", "CALENDLY"],
        confidence=0.88,
        description="Calendly personal access token (JWT).",
        fix_hint="Revoke at calendly.com → Integrations → API.",
    ),

    # ── Identity / Auth (long tail) ──────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-WORKOS-001",
        title="WorkOS API Key",
        secret_type="workos_api_key",
        severity="critical",
        pattern=r'\b(sk_[a-z]+_[A-Za-z0-9_-]{20,80})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['workos'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["workos", "WORKOS"],
        confidence=0.88,
        description="WorkOS SSO/directory sync API key.",
        fix_hint="Revoke at dashboard.workos.com → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ONELOGIN-CLIENT-001",
        title="OneLogin Client Secret",
        secret_type="onelogin_client_secret",
        severity="critical",
        pattern=r'(?i)onelogin[^\n]{0,50}\b([a-f0-9]{64})\b',
        keywords=["onelogin", "ONELOGIN"],
        confidence=0.92,
        description="OneLogin OAuth client secret.",
        fix_hint="Rotate at OneLogin admin → Developers → API Credentials.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-JUMPCLOUD-001",
        title="JumpCloud API Key",
        secret_type="jumpcloud_api_key",
        severity="critical",
        pattern=r'(?i)jumpcloud[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["jumpcloud", "JUMPCLOUD"],
        confidence=0.92,
        description="JumpCloud directory API key. Full user/device admin access.",
        fix_hint="Rotate at console.jumpcloud.com → API Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LASTPASS-ENT-001",
        title="LastPass Enterprise CID",
        secret_type="lastpass_enterprise_cid",
        severity="critical",
        pattern=r'(?i)lastpass[^\n]{0,50}\b([0-9]{10}-[a-zA-Z0-9]{64})\b',
        keywords=["lastpass", "LASTPASS"],
        confidence=0.95,
        description="LastPass Enterprise/Business provisioning hash.",
        fix_hint="Rotate at admin.lastpass.com → Advanced Options → Enterprise API.",
    ),

    # ── Social Media / APIs ──────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-TWITCH-CLIENT-001",
        title="Twitch Client Secret",
        secret_type="twitch_client_secret",
        severity="high",
        pattern=r'(?i)twitch[^\n]{0,80}(?:secret|SECRET)[^\n]{0,30}\b([a-z0-9]{30})\b',
        keywords=["twitch", "TWITCH_SECRET"],
        confidence=0.90,
        description="Twitch OAuth app client secret.",
        fix_hint="Rotate at dev.twitch.tv → Applications.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-VIMEO-001",
        title="Vimeo Access Token",
        secret_type="vimeo_access_token",
        severity="high",
        pattern=r'(?i)vimeo[^\n]{0,50}\b([A-Za-z0-9_-]{40,})\b',
        keywords=["vimeo", "VIMEO"],
        confidence=0.80,
        description="Vimeo API access token.",
        fix_hint="Revoke at developer.vimeo.com → My Apps.",
    ),

    # ── Misc high-value ──────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-CONTENTFUL-DELIVERY-001",
        title="Contentful Delivery Token",
        secret_type="contentful_delivery_token",
        severity="medium",
        pattern=r'(?i)contentful[^\n]{0,50}(?:access_token|ACCESS_TOKEN|delivery)[^\n]{0,30}\b([A-Za-z0-9_-]{43,64})\b',
        keywords=["contentful", "CONTENTFUL"],
        confidence=0.92,
        description="Contentful Content Delivery API access token.",
        fix_hint="Rotate at app.contentful.com → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CONTENTFUL-MGMT-001",
        title="Contentful Management Token",
        secret_type="contentful_management_token",
        severity="critical",
        pattern=r'\b(CFPAT-[A-Za-z0-9_-]{43,64})\b',
        keywords=["CFPAT-", "contentful"],
        confidence=0.99,
        description="Contentful CMA personal access token. Full content write access.",
        fix_hint="Revoke at contentful.com → Account → CMA Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-STORYBLOK-001",
        title="Storyblok API Token",
        secret_type="storyblok_api_token",
        severity="high",
        pattern=r'(?i)storyblok[^\n]{0,50}\b([A-Za-z0-9]{24})tt\b|\b([A-Za-z0-9]{24})tt\b',
        keywords=["storyblok", "STORYBLOK"],
        confidence=0.88,
        description="Storyblok headless CMS API token.",
        fix_hint="Revoke at app.storyblok.com → Access Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DOPPLER-001",
        title="Doppler Service Token",
        secret_type="doppler_service_token",
        severity="critical",
        pattern=r'\b(dp\.st\.[a-z_]+\.[A-Za-z0-9]{40,44})\b',
        keywords=["dp.st.", "doppler"],
        confidence=0.99,
        description="Doppler service token. Full config secret access.",
        fix_hint="Rotate at doppler.com → Config → Access → Service Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DOPPLER-PAT-001",
        title="Doppler Personal Access Token",
        secret_type="doppler_pat",
        severity="critical",
        pattern=r'\b(dp\.pt\.[A-Za-z0-9]{40,44})\b',
        keywords=["dp.pt.", "doppler"],
        confidence=0.99,
        description="Doppler personal access token. Full workplace access.",
        fix_hint="Revoke at doppler.com → Profile → Access Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SEMGREP-001",
        title="Semgrep App Token",
        secret_type="semgrep_app_token",
        severity="high",
        pattern=r'(?i)semgrep[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["semgrep", "SEMGREP_APP_TOKEN"],
        confidence=0.92,
        description="Semgrep SaaS app token for CI scanning.",
        fix_hint="Rotate at semgrep.dev → Settings → Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SNYK-001",
        title="Snyk API Token",
        secret_type="snyk_api_token",
        severity="high",
        pattern=r'(?i)snyk[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["snyk", "SNYK"],
        confidence=0.93,
        description="Snyk vulnerability-scan API token.",
        fix_hint="Rotate at app.snyk.io → Account Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ROLLBAR-PROJECT-001",
        title="Rollbar Project Access Token",
        secret_type="rollbar_project_token",
        severity="medium",
        pattern=r'(?i)rollbar[^\n]{0,50}\b([a-f0-9]{32})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['project', 'POST', 'post_server', 'post_client'],
        post_filter_window=50,
        keywords=["rollbar", "ROLLBAR_ACCESS_TOKEN"],
        confidence=0.88,
        description="Rollbar project access token (post_server_item / post_client_item).",
        fix_hint="Rotate at rollbar.com → Project Settings → Access Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DATADOG-APP-002",
        title="Datadog Application Key",
        secret_type="datadog_application_key",
        severity="critical",
        pattern=r'\b(DD_APP_KEY|DD_APPLICATION_KEY)\s*[=:]\s*[\'"]?\b([a-f0-9]{40})\b',
        keywords=["DD_APP_KEY", "DD_APPLICATION_KEY", "datadog_app_key"],
        confidence=0.95,
        description="Datadog application key. Scripted API/resource access.",
        fix_hint="Rotate at app.datadoghq.com → Organization Settings → Application Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-OPSLEVEL-001",
        title="OpsLevel API Token",
        secret_type="opslevel_api_token",
        severity="high",
        pattern=r'(?i)opslevel[^\n]{0,50}\b([A-Za-z0-9_-]{40,64})\b',
        keywords=["opslevel", "OPSLEVEL"],
        confidence=0.85,
        description="OpsLevel service catalog API token.",
        fix_hint="Revoke at app.opslevel.com → Profile → API Tokens.",
    ),
]
