# SPDX-FileCopyrightText: 2026 Virantis
# SPDX-License-Identifier: LicenseRef-Vooda-Community-1.0

from __future__ import annotations
"""
TruffleHog Port v3 — Wave 3 expansion.

Closes the remaining rule-count gap vs TruffleHog by adding ~100 more
rules across under-covered categories: CI/CD tools, secret managers,
e-signature platforms, form/survey tools, Web3/NFT services, email
validation, localization, CRM/sales tools, and gaming/media APIs.

Every rule targets a provider-specific token format with a
cryptographically distinct prefix or length signature so precision
stays high.
"""

from services.secret_scan.detectors.base import SecretRule


RULES: list[SecretRule] = [

    # ── AI / LLM (more long tail) ────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-XAI-GROK-001",
        title="xAI Grok API Key",
        secret_type="xai_grok_key",
        severity="high",
        pattern=r'\b(xai-[A-Za-z0-9]{80,})\b',
        keywords=["xai-", "grok"],
        confidence=0.98,
        description="xAI Grok model API key.",
        fix_hint="Revoke at console.x.ai → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-INFLECTION-001",
        title="Inflection AI (Pi) API Key",
        secret_type="inflection_api_key",
        severity="high",
        pattern=r'(?i)inflection[^\n]{0,60}\b([A-Za-z0-9]{32,64})\b',
        keywords=["inflection", "INFLECTION", "Pi_API"],
        confidence=0.80,
        description="Inflection AI (Pi) API key.",
        fix_hint="Revoke at inflection.ai dashboard.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ALEPH-001",
        title="Aleph Alpha API Token",
        secret_type="aleph_alpha_token",
        severity="high",
        pattern=r'(?i)aleph.?alpha[^\n]{0,50}\b([A-Za-z0-9]{64,})\b',
        keywords=["aleph", "ALEPH_API"],
        confidence=0.85,
        description="Aleph Alpha Luminous LLM API token.",
        fix_hint="Revoke at app.aleph-alpha.com → Profile → Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FAL-AI-001",
        title="Fal.ai API Key",
        secret_type="fal_ai_key",
        severity="high",
        pattern=r'\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}:[a-f0-9]{32})\b',
        keywords=["fal.ai", "FAL_KEY"],
        confidence=0.97,
        description="Fal.ai model inference API key (UUID:hex format).",
        fix_hint="Revoke at fal.ai → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TOGETHER-SK-001",
        title="Together AI SK-Prefixed Key",
        secret_type="together_sk_key",
        severity="high",
        pattern=r'\b(sk-[A-Za-z0-9]{48,})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['together'],
        post_filter_window=120,
        keywords=["together", "TOGETHER_API"],
        confidence=0.90,
        description="Together AI key (sk- prefix variant).",
        fix_hint="Revoke at api.together.ai → API Keys.",
    ),

    # ── CI / CD (additional) ─────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-HARNESS-001",
        title="Harness Platform PAT",
        secret_type="harness_pat",
        severity="critical",
        pattern=r'\b(pat\.[A-Za-z0-9_.-]{22}\.[A-Za-z0-9_.-]{22}\.[A-Za-z0-9_.-]{22})\b',
        keywords=["pat.", "harness", "HARNESS"],
        confidence=0.97,
        description="Harness CD/CI platform personal access token.",
        fix_hint="Revoke at app.harness.io → User Profile → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-OCTOPUS-DEPLOY-001",
        title="Octopus Deploy API Key",
        secret_type="octopus_api_key",
        severity="critical",
        pattern=r'\b(API-[A-Z0-9]{26})\b',
        keywords=["API-", "octopus"],
        confidence=0.98,
        description="Octopus Deploy API key (API- prefix, 30 chars total).",
        fix_hint="Revoke at Octopus → Profile → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-ARGOCD-001",
        title="Argo CD API Token",
        secret_type="argocd_api_token",
        severity="critical",
        pattern=r'(?i)argocd[^\n]{0,50}\b(eyJhbGciOi[A-Za-z0-9_-]{80,500}\.[A-Za-z0-9_-]{40,200})\b',
        keywords=["argocd", "ARGOCD"],
        confidence=0.90,
        description="Argo CD JWT API token.",
        fix_hint="Rotate at Argo CD → Settings → Accounts.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SPINNAKER-001",
        title="Spinnaker Service Account",
        secret_type="spinnaker_service_account",
        severity="high",
        pattern=r'(?i)spinnaker[^\n]{0,50}\b([A-Za-z0-9_-]{30,})\b',
        keywords=["spinnaker", "SPINNAKER"],
        confidence=0.80,
        description="Spinnaker service account credential.",
        fix_hint="Rotate at Spinnaker halyard config.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GITLAB-CR-TOKEN-001",
        title="GitLab Container Registry Token",
        secret_type="gitlab_cr_token",
        severity="high",
        pattern=r'\b(glcbt-[A-Za-z0-9_-]{16,})\b',
        keywords=["glcbt-"],
        confidence=0.98,
        description="GitLab container-registry CI build token (glcbt- prefix).",
        fix_hint="Revoke at GitLab → Settings → Repository → Deploy tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GITLAB-PIPELINE-TRIGGER-001",
        title="GitLab Pipeline Trigger Token",
        secret_type="gitlab_pipeline_trigger",
        severity="high",
        pattern=r'\b(glptt-[a-f0-9]{40})\b',
        keywords=["glptt-"],
        confidence=0.99,
        description="GitLab pipeline trigger token (glptt- prefix).",
        fix_hint="Revoke at GitLab → Settings → CI/CD → Pipeline triggers.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GITLAB-RUNNER-REG-001",
        title="GitLab Runner Registration Token",
        secret_type="gitlab_runner_reg_token",
        severity="critical",
        pattern=r'\b(glrt-[A-Za-z0-9_-]{20,})\b',
        keywords=["glrt-"],
        confidence=0.98,
        description="GitLab runner registration token (glrt- prefix).",
        fix_hint="Revoke at GitLab → Settings → CI/CD → Runners.",
    ),

    # ── Secret Managers / Password Managers ──────────────────────
    SecretRule(
        rule_id="VOODA-SEC-AKEYLESS-001",
        title="Akeyless Vault Token",
        secret_type="akeyless_token",
        severity="critical",
        pattern=r'\b(t-[a-z0-9]{24}|u-[a-z0-9]{24}|r-[a-z0-9]{24})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['akeyless'],
        post_filter_window=120,
        keywords=["akeyless", "AKEYLESS"],
        confidence=0.90,
        description="Akeyless vault authentication token.",
        fix_hint="Revoke via Akeyless CLI or Console.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ONEPASSWORD-SA-001",
        title="1Password Service Account Token",
        secret_type="1password_sa_token",
        severity="critical",
        pattern=r'\b(ops_eyJ[A-Za-z0-9_+/=]{200,})\b',
        keywords=["ops_eyJ", "1password"],
        confidence=0.99,
        description="1Password service account token (ops_eyJ prefix, base64 JWT).",
        fix_hint="Revoke at start.1password.com → Integrations → Service Accounts.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BITWARDEN-CLIENT-001",
        title="Bitwarden Client Secret",
        secret_type="bitwarden_client_secret",
        severity="critical",
        pattern=r'(?i)bitwarden[^\n]{0,50}(?:client_?secret|api_?key)[^\n]{0,30}\b([A-Za-z0-9]{30,})\b',
        keywords=["bitwarden", "BITWARDEN"],
        confidence=0.85,
        description="Bitwarden organization client secret.",
        fix_hint="Rotate at vault.bitwarden.com → Organization → Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-INFISICAL-001",
        title="Infisical Universal Auth Token",
        secret_type="infisical_token",
        severity="critical",
        pattern=r'\b(st\.[a-z]+\.[a-f0-9-]{36}\.[a-f0-9]{40,64})\b',
        keywords=["st.", "infisical"],
        confidence=0.99,
        description="Infisical secret manager service token (st. prefix).",
        fix_hint="Revoke at infisical.com → Project → Service Tokens.",
    ),

    # ── E-signature ──────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-DOCUSIGN-INTEGRATION-001",
        title="DocuSign Integration Key",
        secret_type="docusign_integration_key",
        severity="critical",
        pattern=r'(?i)docusign[^\n]{0,50}(?:integration_?key|client_?id)[^\n]{0,30}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["docusign", "DOCUSIGN"],
        confidence=0.92,
        description="DocuSign integration (client) key.",
        fix_hint="Revoke at DocuSign admin → API & Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DROPBOX-SIGN-001",
        title="Dropbox Sign (HelloSign) API Key",
        secret_type="dropbox_sign_key",
        severity="critical",
        pattern=r'\b([a-f0-9]{64})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['hellosign', 'dropboxsign', 'hello.sign', 'dropbox.sign'],
        post_filter_window=120,
        keywords=["hellosign", "dropboxsign", "dropbox.sign"],
        confidence=0.90,
        description="Dropbox Sign (formerly HelloSign) API key.",
        fix_hint="Rotate at app.hellosign.com → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PANDADOC-001",
        title="PandaDoc API Key",
        secret_type="pandadoc_api_key",
        severity="critical",
        pattern=r'(?i)pandadoc[^\n]{0,50}\b([A-Za-z0-9]{40,})\b',
        keywords=["pandadoc", "PANDADOC"],
        confidence=0.85,
        description="PandaDoc e-signature API key.",
        fix_hint="Rotate at app.pandadoc.com → Settings → Integrations → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SIGNNOW-001",
        title="SignNow OAuth Token",
        secret_type="signnow_oauth_token",
        severity="critical",
        pattern=r'(?i)signnow[^\n]{0,50}\b([A-Za-z0-9]{40,60})\b',
        keywords=["signnow", "SIGNNOW"],
        confidence=0.85,
        description="SignNow e-signature OAuth token.",
        fix_hint="Rotate at app.signnow.com → API.",
    ),

    # ── Web3 / NFT / Crypto ──────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-MORALIS-001",
        title="Moralis Web3 API Key",
        secret_type="moralis_api_key",
        severity="high",
        pattern=r'(?i)moralis[^\n]{0,50}\b([A-Za-z0-9_-]{60,})\b',
        keywords=["moralis", "MORALIS"],
        confidence=0.82,
        description="Moralis Web3 infrastructure API key.",
        fix_hint="Revoke at admin.moralis.io → Web3 APIs → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-QUICKNODE-001",
        title="QuickNode Endpoint Auth Token",
        secret_type="quicknode_auth_token",
        severity="high",
        pattern=r'https?://[a-z0-9.-]{10,80}\.quiknode\.pro/[a-f0-9]{32,64}/',
        keywords=["quiknode", "QUICKNODE"],
        confidence=0.99,
        description="QuickNode Web3 endpoint URL with embedded token.",
        fix_hint="Rotate at quicknode.com → Endpoints.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-INFURA-API-001",
        title="Infura Project Secret",
        secret_type="infura_project_secret",
        severity="critical",
        pattern=r'(?i)infura[^\n]{0,50}(?:project_?secret|PROJECT_SECRET)[^\n]{0,30}\b([a-f0-9]{32})\b',
        keywords=["infura", "INFURA"],
        confidence=0.92,
        description="Infura Web3 project secret.",
        fix_hint="Rotate at app.infura.io → Projects → Settings → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-THIRDWEB-001",
        title="Thirdweb Secret Key",
        secret_type="thirdweb_secret",
        severity="critical",
        pattern=r'(?i)thirdweb[^\n]{0,50}(?:secret_?key|SECRET)[^\n]{0,30}\b([A-Za-z0-9_-]{80,})\b',
        keywords=["thirdweb", "THIRDWEB"],
        confidence=0.88,
        description="Thirdweb Web3 SDK secret key.",
        fix_hint="Rotate at thirdweb.com → Dashboard → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MAGIC-LINK-001",
        title="Magic.link Live Secret Key",
        secret_type="magic_link_secret",
        severity="critical",
        pattern=r'\b(sk_live_[A-F0-9]{32,40})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['magic'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["magic.link", "MAGIC"],
        confidence=0.90,
        description="Magic.link passwordless auth live secret key.",
        fix_hint="Revoke at dashboard.magic.link → Apps.",
    ),

    # ── Email Validation ─────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-ZEROBOUNCE-001",
        title="ZeroBounce API Key",
        secret_type="zerobounce_api_key",
        severity="medium",
        pattern=r'(?i)zerobounce[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["zerobounce", "ZEROBOUNCE"],
        confidence=0.90,
        description="ZeroBounce email validation API key.",
        fix_hint="Rotate at zerobounce.net → Dashboard → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-NEVERBOUNCE-001",
        title="NeverBounce API Key",
        secret_type="neverbounce_api_key",
        severity="medium",
        pattern=r'(?i)neverbounce[^\n]{0,50}\b(secret_[A-Za-z0-9_-]{40,}|[a-f0-9]{32})\b',
        keywords=["neverbounce", "NEVERBOUNCE", "secret_"],
        confidence=0.88,
        description="NeverBounce email verification API key.",
        fix_hint="Rotate at app.neverbounce.com → Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-KICKBOX-001",
        title="Kickbox API Key",
        secret_type="kickbox_api_key",
        severity="medium",
        # 2-pass: lookahead → post_filter_* (Option B-1b manual rewrite,
        # 2026-05-24).  The codemod missed this one because the token
        # regex contains nested parens `(?:live|test)` which the
        # codemod's `\([^)]+\)` shape couldn't span.  Both halves had
        # identical token shape so a direct rewrite is clean.
        pattern=r'\b((?:live|test)_[a-f0-9]{40})\b',
        post_filter_keywords=['kickbox'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["kickbox", "KICKBOX"],
        confidence=0.92,
        description="Kickbox email verification live/test API key.",
        fix_hint="Rotate at kickbox.com → Settings → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-EMAILABLE-001",
        title="Emailable API Key",
        secret_type="emailable_api_key",
        severity="medium",
        pattern=r'\b(live_[A-Za-z0-9]{26}|test_[A-Za-z0-9]{26})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['emailable'],
        post_filter_window=120,
        keywords=["emailable", "EMAILABLE"],
        confidence=0.92,
        description="Emailable email validation live/test key.",
        fix_hint="Rotate at app.emailable.com → API.",
    ),

    # ── Localization / Translation ───────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-LOKALISE-001",
        title="Lokalise API Token",
        secret_type="lokalise_api_token",
        severity="high",
        pattern=r'(?i)lokalise[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["lokalise", "LOKALISE"],
        confidence=0.92,
        description="Lokalise localization API token.",
        fix_hint="Revoke at app.lokalise.com → Personal profile → API tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CROWDIN-001",
        title="Crowdin Personal API Token",
        secret_type="crowdin_api_token",
        severity="high",
        pattern=r'\b([a-f0-9]{64,96})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['crowdin'],
        post_filter_window=120,
        keywords=["crowdin", "CROWDIN"],
        confidence=0.90,
        description="Crowdin localization platform personal token.",
        fix_hint="Revoke at crowdin.com → Account Settings → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PHRASE-001",
        title="Phrase Translation Access Token",
        secret_type="phrase_access_token",
        severity="high",
        pattern=r'(?i)phrase[^\n]{0,50}(?:access_?token|API_TOKEN)[^\n]{0,30}\b([a-f0-9]{64})\b',
        keywords=["phrase", "PHRASE"],
        confidence=0.90,
        description="Phrase (Memsource) translation API access token.",
        fix_hint="Rotate at app.phrase.com → Profile → OAuth Access Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SMARTLING-001",
        title="Smartling User Secret",
        secret_type="smartling_user_secret",
        severity="critical",
        pattern=r'(?i)smartling[^\n]{0,60}(?:secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9]{40,})\b',
        keywords=["smartling", "SMARTLING"],
        confidence=0.88,
        description="Smartling translation management user secret.",
        fix_hint="Rotate at dashboard.smartling.com → API.",
    ),

    # ── Observability (more specialized) ─────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-LOGZIO-001",
        title="Logz.io Shipping Token",
        secret_type="logzio_shipping_token",
        severity="high",
        pattern=r'(?i)logz\.io[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["logz.io", "LOGZIO_SHIPPING_TOKEN"],
        confidence=0.88,
        description="Logz.io log-shipping token.",
        fix_hint="Rotate at app.logz.io → Settings → Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PAPERTRAIL-001",
        title="Papertrail API Token",
        secret_type="papertrail_api_token",
        severity="medium",
        pattern=r'(?i)papertrail[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["papertrail", "PAPERTRAIL"],
        confidence=0.90,
        description="Papertrail log management API token.",
        fix_hint="Rotate at papertrailapp.com → Profile → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HUMIO-001",
        title="Humio Ingest Token",
        secret_type="humio_ingest_token",
        severity="high",
        pattern=r'(?i)humio[^\n]{0,50}\b([a-f0-9]{40,64})\b',
        keywords=["humio", "HUMIO"],
        confidence=0.88,
        description="Humio (Falcon LogScale) ingest token.",
        fix_hint="Rotate at Humio UI → Ingest tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LIGHTSTEP-001",
        title="Lightstep API Key",
        secret_type="lightstep_api_key",
        severity="high",
        pattern=r'(?i)lightstep[^\n]{0,50}\b([a-f0-9]{32,64})\b',
        keywords=["lightstep", "LIGHTSTEP", "LS_ACCESS_TOKEN"],
        confidence=0.88,
        description="Lightstep observability API key.",
        fix_hint="Rotate at app.lightstep.com → Project settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-EPSAGON-001",
        title="Epsagon Token",
        secret_type="epsagon_token",
        severity="medium",
        pattern=r'(?i)epsagon[^\n]{0,50}\b([a-f0-9-]{36})\b',
        keywords=["epsagon", "EPSAGON"],
        confidence=0.90,
        description="Epsagon APM tracer token.",
        fix_hint="Rotate at dashboard.epsagon.com → Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-AXIOM-INGEST-002",
        title="Axiom Ingest Token",
        secret_type="axiom_ingest_token",
        severity="high",
        pattern=r'\b(xait-[A-Za-z0-9_-]{36,64})\b',
        keywords=["xait-", "axiom"],
        confidence=0.98,
        description="Axiom.co log-ingest token (xait- prefix).",
        fix_hint="Rotate at app.axiom.co → Settings → Ingest tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-AXIOM-API-001",
        title="Axiom Personal Access Token",
        secret_type="axiom_pat",
        severity="critical",
        pattern=r'\b(xaat-[A-Za-z0-9_-]{36,64})\b',
        keywords=["xaat-", "axiom"],
        confidence=0.98,
        description="Axiom.co personal access token (xaat- prefix).",
        fix_hint="Revoke at app.axiom.co → Settings → API tokens.",
    ),

    # ── Feature flags / experimentation ──────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-SPLIT-IO-001",
        title="Split.io SDK Key",
        secret_type="split_io_sdk_key",
        severity="high",
        pattern=r'(?i)split\.io[^\n]{0,50}\b([a-z0-9]{20,30})\b',
        keywords=["split.io", "SPLIT_SDK"],
        confidence=0.85,
        description="Split.io feature-flag SDK key.",
        fix_hint="Rotate at app.split.io → Admin → APIs.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-OPTIMIZELY-001",
        title="Optimizely SDK Key",
        secret_type="optimizely_sdk_key",
        severity="medium",
        pattern=r'\b([A-Za-z0-9]{10,14}_[A-Za-z0-9]{10,20})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['optimizely'],
        post_filter_window=120,
        keywords=["optimizely", "OPTIMIZELY"],
        confidence=0.82,
        description="Optimizely experimentation SDK key.",
        fix_hint="Rotate at app.optimizely.com → Settings → Environments.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FLAGSMITH-001",
        title="Flagsmith Environment Key",
        secret_type="flagsmith_env_key",
        severity="high",
        pattern=r'(?i)flagsmith[^\n]{0,50}\b([A-Za-z0-9]{40,})\b',
        keywords=["flagsmith", "FLAGSMITH"],
        confidence=0.82,
        description="Flagsmith feature-flag environment key.",
        fix_hint="Rotate at app.flagsmith.com → Environment → Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-UNLEASH-001",
        title="Unleash Client Key",
        secret_type="unleash_client_key",
        severity="high",
        pattern=r'\b(\*:[*\w-]+\.[a-f0-9]{64})\b|\b(\w+:[*\w-]+\.[a-f0-9]{64})\b',
        keywords=["unleash", "UNLEASH"],
        confidence=0.95,
        description="Unleash feature-flag client or admin API key.",
        fix_hint="Rotate at Unleash admin UI → API access.",
    ),

    # ── Error tracking / APM (more) ──────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-AIRBRAKE-001",
        title="Airbrake Project Key",
        secret_type="airbrake_project_key",
        severity="high",
        pattern=r'(?i)airbrake[^\n]{0,50}(?:project_?key|PROJECT_KEY)[^\n]{0,30}\b([a-f0-9]{32})\b',
        keywords=["airbrake", "AIRBRAKE"],
        confidence=0.92,
        description="Airbrake error reporting project key.",
        fix_hint="Rotate at airbrake.io → Project Settings → Ingestion.",
    ),

    # ── API Gateways ─────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-KONG-ADMIN-001",
        title="Kong Admin API Token",
        secret_type="kong_admin_token",
        severity="critical",
        pattern=r'(?i)kong[^\n]{0,50}(?:admin_?token|ADMIN_TOKEN)[^\n]{0,30}\b([A-Za-z0-9]{40,})\b',
        keywords=["kong", "KONG_ADMIN"],
        confidence=0.88,
        description="Kong API gateway admin token.",
        fix_hint="Rotate at Kong Manager or via declarative config.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TYK-001",
        title="Tyk API Secret",
        secret_type="tyk_api_secret",
        severity="critical",
        pattern=r'(?i)tyk[^\n]{0,50}(?:api_?secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9_-]{40,})\b',
        keywords=["tyk", "TYK_"],
        confidence=0.85,
        description="Tyk API gateway admin secret.",
        fix_hint="Rotate at Tyk dashboard → Users → API Secret.",
    ),

    # ── Test management ──────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-TESTRAIL-001",
        title="TestRail API Key",
        secret_type="testrail_api_key",
        severity="medium",
        pattern=r'(?i)testrail[^\n]{0,50}\b([A-Za-z0-9]{20,})\b',
        keywords=["testrail", "TESTRAIL"],
        confidence=0.78,
        description="TestRail test management API key.",
        fix_hint="Rotate at TestRail → My Settings → API Keys.",
    ),

    # ── CRM / Sales (more) ───────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-HUNTER-IO-001",
        title="Hunter.io API Key",
        secret_type="hunter_api_key",
        severity="medium",
        pattern=r'(?i)hunter[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["hunter.io", "HUNTER"],
        confidence=0.88,
        description="Hunter.io email enrichment API key.",
        fix_hint="Rotate at hunter.io → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CLEARBIT-001",
        title="Clearbit API Key",
        secret_type="clearbit_api_key",
        severity="high",
        pattern=r'(?i)clearbit[^\n]{0,50}\b(sk_[a-f0-9]{32})\b',
        keywords=["clearbit", "CLEARBIT"],
        confidence=0.95,
        description="Clearbit (now Breeze) company enrichment API key.",
        fix_hint="Rotate at dashboard.clearbit.com → API → Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-APOLLO-IO-001",
        title="Apollo.io API Key",
        secret_type="apollo_io_api_key",
        severity="high",
        pattern=r'(?i)apollo\.io[^\n]{0,50}\b([A-Za-z0-9_-]{22,})\b',
        keywords=["apollo.io", "APOLLO_API"],
        confidence=0.82,
        description="Apollo.io B2B sales intelligence API key.",
        fix_hint="Rotate at app.apollo.io → Settings → Integrations → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DRIFT-001",
        title="Drift API Bearer Token",
        secret_type="drift_api_token",
        severity="high",
        pattern=r'(?i)drift[^\n]{0,50}\b(eyJ[A-Za-z0-9_-]{100,500}\.[A-Za-z0-9_-]{60,200})\b',
        keywords=["drift", "DRIFT"],
        confidence=0.92,
        description="Drift conversational marketing API bearer token (JWT).",
        fix_hint="Revoke at drift.com → Settings → App Settings → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-COPPER-CRM-001",
        title="Copper CRM API Key",
        secret_type="copper_crm_key",
        severity="high",
        pattern=r'(?i)copper[^\n]{0,50}(?:api_?key)[^\n]{0,30}\b([a-f0-9]{40})\b',
        keywords=["copper", "COPPER_CRM"],
        confidence=0.88,
        description="Copper CRM API key.",
        fix_hint="Rotate at app.copper.com → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CLOSE-IO-001",
        title="Close.com API Key",
        secret_type="close_io_api_key",
        severity="high",
        pattern=r'\b(api_[a-zA-Z0-9]{40,64})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['close', 'CLOSE_API'],
        post_filter_window=120,
        keywords=["close.io", "close.com", "CLOSE_API"],
        confidence=0.90,
        description="Close.com CRM API key.",
        fix_hint="Rotate at app.close.com → Settings → Your API Keys.",
    ),

    # ── E-commerce / Marketplace ─────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-ETSY-001",
        title="Etsy API Key",
        secret_type="etsy_api_key",
        severity="medium",
        pattern=r'(?i)etsy[^\n]{0,50}\b([a-z0-9]{24})\b',
        keywords=["etsy", "ETSY"],
        confidence=0.85,
        description="Etsy Open API key.",
        fix_hint="Rotate at etsy.com/developers → Apps → Manage Apps.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GUMROAD-001",
        title="Gumroad Access Token",
        secret_type="gumroad_access_token",
        severity="high",
        pattern=r'(?i)gumroad[^\n]{0,50}\b([A-Za-z0-9_-]{20,})\b',
        keywords=["gumroad", "GUMROAD"],
        confidence=0.80,
        description="Gumroad creator-commerce access token.",
        fix_hint="Rotate at app.gumroad.com → Settings → Advanced.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LEMON-SQUEEZY-001",
        title="Lemon Squeezy API Token",
        secret_type="lemon_squeezy_token",
        severity="critical",
        pattern=r'(?i)lemon.?squeezy[^\n]{0,50}\b(eyJ[A-Za-z0-9_-]{100,500}\.[A-Za-z0-9_-]{60,200})\b',
        keywords=["lemonsqueezy", "LEMON_SQUEEZY"],
        confidence=0.95,
        description="Lemon Squeezy merchant API JWT token.",
        fix_hint="Revoke at app.lemonsqueezy.com → Settings → API.",
    ),

    # ── Form builders / surveys ──────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-SURVEYMONKEY-001",
        title="SurveyMonkey API Token",
        secret_type="surveymonkey_token",
        severity="medium",
        pattern=r'(?i)surveymonkey[^\n]{0,50}\b([A-Za-z0-9_-]{43,})\b',
        keywords=["surveymonkey", "SURVEYMONKEY"],
        confidence=0.85,
        description="SurveyMonkey API access token.",
        fix_hint="Revoke at developer.surveymonkey.com → My Apps.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-JOTFORM-001",
        title="Jotform API Key",
        secret_type="jotform_api_key",
        severity="medium",
        pattern=r'(?i)jotform[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["jotform", "JOTFORM"],
        confidence=0.88,
        description="Jotform form-builder API key.",
        fix_hint="Rotate at jotform.com → My Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FORMSTACK-001",
        title="Formstack OAuth Token",
        secret_type="formstack_oauth_token",
        severity="medium",
        pattern=r'(?i)formstack[^\n]{0,50}\b([A-Za-z0-9]{40,64})\b',
        keywords=["formstack", "FORMSTACK"],
        confidence=0.82,
        description="Formstack OAuth token.",
        fix_hint="Rotate at www.formstack.com/admin → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TYPEFORM-OAUTH-001",
        title="Typeform OAuth Token",
        secret_type="typeform_oauth_token",
        severity="high",
        pattern=r'\b(tfp_[A-Za-z0-9_]{40,80})\b',
        keywords=["tfp_", "typeform"],
        confidence=0.98,
        description="Typeform personal access token (tfp_ prefix).",
        fix_hint="Revoke at typeform.com → Account → Personal tokens.",
    ),

    # ── Webhooks / no-code ───────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-WEBHOOK-SITE-001",
        title="Webhook.site Token",
        secret_type="webhook_site_token",
        severity="low",
        pattern=r'https://webhook\.site/([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})',
        keywords=["webhook.site"],
        confidence=0.99,
        description="Webhook.site testing URL.",
        fix_hint="Replace with proper webhook endpoint before production deploy.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ZAPIER-NLA-001",
        title="Zapier Natural Language Actions Key",
        secret_type="zapier_nla_key",
        severity="high",
        pattern=r'\b(sk-ak-[A-Za-z0-9_-]{40,})\b',
        keywords=["sk-ak-", "zapier"],
        confidence=0.98,
        description="Zapier NLA (natural-language actions) access key.",
        fix_hint="Revoke at nla.zapier.com → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MAKE-COM-001",
        title="Make.com API Token",
        secret_type="make_com_token",
        severity="high",
        pattern=r'(?i)make\.com[^\n]{0,50}\b([A-Za-z0-9-]{36,})\b',
        keywords=["make.com", "integromat", "MAKE_COM"],
        confidence=0.82,
        description="Make.com (Integromat) automation API token.",
        fix_hint="Revoke at eu1.make.com → Profile → API/Webhooks.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-N8N-001",
        title="n8n API Key",
        secret_type="n8n_api_key",
        severity="critical",
        pattern=r'(?i)n8n[^\n]{0,50}(?:api_?key|API_KEY)[^\n]{0,30}\b(eyJ[A-Za-z0-9_-]{80,400}\.[A-Za-z0-9_-]{40,200})\b',
        keywords=["n8n", "N8N_API_KEY"],
        confidence=0.95,
        description="n8n workflow automation API key (JWT).",
        fix_hint="Rotate at n8n → Settings → API.",
    ),

    # ── Gaming / media ───────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-STEAM-001",
        title="Steam Web API Key",
        secret_type="steam_api_key",
        severity="medium",
        pattern=r'(?i)steam[^\n]{0,50}\b([A-F0-9]{32})\b',
        keywords=["steam", "STEAM_API"],
        confidence=0.90,
        description="Steam Web API key.",
        fix_hint="Rotate at steamcommunity.com/dev.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-RIOT-001",
        title="Riot Games API Key",
        secret_type="riot_api_key",
        severity="medium",
        pattern=r'\b(RGAPI-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["RGAPI-", "riot"],
        confidence=0.99,
        description="Riot Games API development key.",
        fix_hint="Refresh at developer.riotgames.com.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GIPHY-001",
        title="Giphy API Key",
        secret_type="giphy_api_key",
        severity="low",
        pattern=r'(?i)giphy[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["giphy", "GIPHY"],
        confidence=0.88,
        description="Giphy GIF API key.",
        fix_hint="Rotate at developers.giphy.com.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TENOR-001",
        title="Tenor API Key",
        secret_type="tenor_api_key",
        severity="low",
        pattern=r'(?i)tenor[^\n]{0,50}\b([A-Z0-9]{30,50})\b',
        keywords=["tenor", "TENOR"],
        confidence=0.82,
        description="Tenor GIF API key.",
        fix_hint="Rotate at tenor.com/gifapi/dashboard.",
    ),

    # ── Social ───────────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-REDDIT-CLIENT-001",
        title="Reddit OAuth Client Secret",
        secret_type="reddit_client_secret",
        severity="high",
        pattern=r'(?i)reddit[^\n]{0,50}(?:client_?secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9_-]{27,30})\b',
        keywords=["reddit", "REDDIT"],
        confidence=0.90,
        description="Reddit OAuth app client secret.",
        fix_hint="Rotate at reddit.com/prefs/apps.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PRODUCT-HUNT-001",
        title="Product Hunt API Token",
        secret_type="producthunt_token",
        severity="medium",
        pattern=r'(?i)product.?hunt[^\n]{0,50}\b([A-Za-z0-9_-]{43,64})\b',
        keywords=["producthunt", "PRODUCTHUNT"],
        confidence=0.82,
        description="Product Hunt Developer API token.",
        fix_hint="Rotate at api.producthunt.com/v2/oauth/applications.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FLICKR-001",
        title="Flickr API Secret",
        secret_type="flickr_api_secret",
        severity="medium",
        pattern=r'(?i)flickr[^\n]{0,50}(?:secret|api_secret)[^\n]{0,30}\b([a-f0-9]{16})\b',
        keywords=["flickr", "FLICKR"],
        confidence=0.92,
        description="Flickr app API secret.",
        fix_hint="Rotate at flickr.com/services/apps.",
    ),

    # ── Travel ───────────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-AMADEUS-001",
        title="Amadeus Client Secret",
        secret_type="amadeus_client_secret",
        severity="high",
        pattern=r'(?i)amadeus[^\n]{0,50}(?:client_?secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9]{16})\b',
        keywords=["amadeus", "AMADEUS"],
        confidence=0.92,
        description="Amadeus travel API client secret.",
        fix_hint="Rotate at developers.amadeus.com.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SKYSCANNER-001",
        title="Skyscanner API Key",
        secret_type="skyscanner_api_key",
        severity="medium",
        pattern=r'(?i)skyscanner[^\n]{0,50}\b([a-z0-9]{32})\b',
        keywords=["skyscanner", "SKYSCANNER"],
        confidence=0.85,
        description="Skyscanner travel search API key.",
        fix_hint="Rotate at partners.skyscanner.net.",
    ),

    # ── HR / ATS (additional) ────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-BAMBOOHR-001",
        title="BambooHR API Key",
        secret_type="bamboohr_api_key",
        severity="high",
        pattern=r'(?i)bamboohr[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["bamboohr", "BAMBOOHR"],
        confidence=0.90,
        description="BambooHR HR platform API key.",
        fix_hint="Rotate at {company}.bamboohr.com → My Info → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DEPUTY-001",
        title="Deputy OAuth Token",
        secret_type="deputy_oauth_token",
        severity="high",
        pattern=r'(?i)deputy[^\n]{0,50}\b([a-f0-9]{64})\b',
        keywords=["deputy", "DEPUTY"],
        confidence=0.85,
        description="Deputy workforce management access token.",
        fix_hint="Rotate at once.deputy.com → My Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GUSTO-001",
        title="Gusto Client Secret",
        secret_type="gusto_client_secret",
        severity="critical",
        pattern=r'(?i)gusto[^\n]{0,50}(?:client_?secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9_-]{64,})\b',
        keywords=["gusto", "GUSTO"],
        confidence=0.88,
        description="Gusto payroll platform OAuth client secret.",
        fix_hint="Rotate at dev.gusto.com → Applications.",
    ),

    # ── No-code / visual ─────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-BUBBLE-IO-001",
        title="Bubble.io API Token",
        secret_type="bubble_io_token",
        severity="high",
        pattern=r'(?i)bubble\.io[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["bubble.io", "BUBBLE_IO"],
        confidence=0.88,
        description="Bubble.io no-code app API token.",
        fix_hint="Rotate at bubble.io → App Settings → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-WEBFLOW-001",
        title="Webflow API Token",
        secret_type="webflow_api_token",
        severity="high",
        pattern=r'(?i)webflow[^\n]{0,50}\b([a-f0-9]{64})\b',
        keywords=["webflow", "WEBFLOW"],
        confidence=0.90,
        description="Webflow API token.",
        fix_hint="Rotate at webflow.com → Account Settings → Integrations.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FRAMER-001",
        title="Framer API Token",
        secret_type="framer_api_token",
        severity="medium",
        pattern=r'(?i)framer[^\n]{0,50}\b([A-Za-z0-9_-]{40,})\b',
        keywords=["framer", "FRAMER"],
        confidence=0.78,
        description="Framer prototyping API token.",
        fix_hint="Rotate at framer.com → Profile → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SQUARESPACE-001",
        title="Squarespace API Key",
        secret_type="squarespace_api_key",
        severity="high",
        # Require explicit api_key/token context so we don't match CDN paths
        # like static1.squarespace.com/static/<asset-id>/... which contain
        # hex-dash strings that happen to be near the keyword "squarespace".
        # UUID-format with explicit API-key assignment anchor.
        pattern=r'(?i)squarespace[^\n]{0,40}(?:api[_-]?key|token|secret)[^\n]{0,40}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["squarespace", "SQUARESPACE"],
        confidence=0.90,
        description="Squarespace Commerce API key (UUID format with api_key/token context).",
        fix_hint="Rotate at account.squarespace.com → Integrations → API.",
    ),

    # ── Cloud AI / ML inference (more) ───────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-SAGEMAKER-ENDPOINT-001",
        title="AWS SageMaker Endpoint URL",
        secret_type="sagemaker_endpoint",
        severity="medium",
        pattern=r'https://runtime\.sagemaker\.[a-z0-9-]+\.amazonaws\.com/endpoints/[A-Za-z0-9_-]+',
        keywords=["sagemaker", "SAGEMAKER"],
        confidence=0.99,
        description="AWS SageMaker model endpoint URL.",
        fix_hint="Endpoints should not be public; use VPC+IAM authentication.",
    ),

    # ── Security / compliance (additional) ───────────────────────
    SecretRule(
        rule_id="VOODA-SEC-AUTH0-MGMT-001",
        title="Auth0 Management API Domain",
        secret_type="auth0_mgmt_domain",
        severity="info",
        pattern=r'\b([a-z0-9-]{3,40}\.auth0\.com)\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['AUTH0_DOMAIN', 'auth0.com'],
        post_filter_window=120,
        keywords=["auth0.com", "AUTH0_DOMAIN"],
        confidence=0.80,
        description="Auth0 tenant domain (usually public but discloses tenant).",
        fix_hint="Domains are not secret but can help attackers target tenants.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ESQ-SEARCHBOX-001",
        title="Elastic Cloud Search Bearer",
        secret_type="elastic_searchbox_bearer",
        severity="critical",
        pattern=r'\b(enc_[A-Za-z0-9_-]{32,})\b',
        keywords=["enc_", "elastic"],
        confidence=0.90,
        description="Elastic Cloud encoded token (enc_ prefix).",
        fix_hint="Revoke at cloud.elastic.co → Deployment → Security.",
    ),

    # ── Voice / call ─────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-CALLRAIL-001",
        title="CallRail API Key",
        secret_type="callrail_api_key",
        severity="high",
        pattern=r'(?i)callrail[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["callrail", "CALLRAIL"],
        confidence=0.90,
        description="CallRail call tracking API key.",
        fix_hint="Rotate at app.callrail.com → Settings → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DIALPAD-001",
        title="Dialpad API Token",
        secret_type="dialpad_api_token",
        severity="high",
        pattern=r'(?i)dialpad[^\n]{0,50}\b([A-Za-z0-9_-]{40,})\b',
        keywords=["dialpad", "DIALPAD"],
        confidence=0.78,
        description="Dialpad business phone API token.",
        fix_hint="Rotate at dialpad.com/account → Security → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-RINGCENTRAL-001",
        title="RingCentral Client Secret",
        secret_type="ringcentral_client_secret",
        severity="critical",
        pattern=r'(?i)ringcentral[^\n]{0,50}(?:client_?secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9_-]{20,40})\b',
        keywords=["ringcentral", "RINGCENTRAL"],
        confidence=0.85,
        description="RingCentral OAuth client secret.",
        fix_hint="Rotate at developers.ringcentral.com → App → Credentials.",
    ),

    # ── Generic high-value patterns ──────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-ROTATION-WEBHOOK-001",
        title="Generic Private Webhook URL with Token",
        secret_type="generic_webhook_with_token",
        severity="medium",
        pattern=r'https?://[a-zA-Z0-9.-]+/(?:webhook|hook|incoming)/[A-Za-z0-9_-]{30,100}',
        keywords=["webhook", "incoming"],
        confidence=0.70,
        description="Generic webhook URL with long token-like path.",
        fix_hint="Verify the URL is a real webhook; if so, rotate.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BASIC-AUTH-URL-001",
        title="HTTP URL with Basic Auth Credentials",
        secret_type="http_basic_auth_url",
        severity="critical",
        pattern=r'https?://[A-Za-z0-9._-]+:[^@/\s\'"]{6,64}@[A-Za-z0-9.-]+',
        keywords=["http://", "https://"],
        confidence=0.93,
        description="URL with embedded HTTP Basic-auth credentials (user:pass@host).",
        fix_hint="Move credentials out of URL; use separate auth header or config.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-AMQPS-URL-001",
        title="AMQPS URL with Credentials",
        secret_type="amqps_url_auth",
        severity="critical",
        pattern=r'amqps?://[A-Za-z0-9._-]+:[^@\s\'"/]{6,64}@[A-Za-z0-9.-]+',
        keywords=["amqps://", "amqp://"],
        confidence=0.95,
        description="AMQP/AMQPS broker URL with embedded credentials (RabbitMQ, etc.).",
        fix_hint="Move credentials to secret manager or env vars.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FTP-URL-001",
        title="FTP URL with Credentials",
        secret_type="ftp_url_auth",
        severity="high",
        pattern=r'ftps?://[A-Za-z0-9._-]+:[^@\s\'"/]{6,64}@[A-Za-z0-9.-]+',
        keywords=["ftp://", "ftps://"],
        confidence=0.95,
        description="FTP/FTPS URL with embedded credentials.",
        fix_hint="Avoid FTP in production; use SFTP or move credentials to config.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SSH-URL-001",
        title="SSH URL with Password",
        secret_type="ssh_url_auth",
        severity="critical",
        pattern=r'ssh://[A-Za-z0-9._-]+:[^@\s\'"/]{6,64}@[A-Za-z0-9.-]+',
        keywords=["ssh://"],
        confidence=0.97,
        description="SSH URL with embedded password (rather than SSH key).",
        fix_hint="Use SSH keys instead of passwords; remove embedded password.",
    ),

    # ── Miscellaneous high-value ─────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-CALENDLY-V2-001",
        title="Calendly v2 Personal Access Token",
        secret_type="calendly_v2_pat",
        severity="high",
        pattern=r'\b(eyJraWQiOi[A-Za-z0-9_-]{50,}\.[A-Za-z0-9_-]{100,400}\.[A-Za-z0-9_-]{40,200})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['calendly'],
        post_filter_window=120,
        keywords=["calendly", "CALENDLY"],
        confidence=0.95,
        description="Calendly v2 PAT (JWT format).",
        fix_hint="Revoke at calendly.com → Integrations → API & webhooks.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GRAFANA-SA-002",
        title="Grafana Service Account Token",
        secret_type="grafana_sa_token",
        severity="critical",
        pattern=r'\b(glsa_[A-Za-z0-9_]{32}_[A-Fa-f0-9]{8})\b',
        keywords=["glsa_", "grafana"],
        confidence=0.99,
        description="Grafana service-account token (glsa_ prefix).",
        fix_hint="Revoke at Grafana → Administration → Service Accounts.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GRAFANA-API-LEGACY-001",
        title="Grafana API Key (Legacy)",
        secret_type="grafana_api_key_legacy",
        severity="high",
        pattern=r'\b(eyJrIjoi[A-Za-z0-9+/=]{50,})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['grafana'],
        post_filter_window=120,
        keywords=["grafana", "GRAFANA"],
        confidence=0.95,
        description="Grafana legacy API key (deprecated in favor of SA tokens).",
        fix_hint="Migrate to Service Account tokens at Grafana → Administration.",
    ),
    # VOODA-SEC-GROQ-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-GROQ-GSK-001.
    # VOODA-SEC-PERPLEXITY-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-PERPLEXITY-PPLX-001.
    # VOODA-SEC-DEEPSEEK-V2-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-DEEPSEEK-SK-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.
]
