# SPDX-FileCopyrightText: 2026 Virantis
# SPDX-License-Identifier: LicenseRef-Vooda-Community-1.0

from __future__ import annotations
"""
TruffleHog Port v5 — targeted high-precision additions.

Each rule here has:
  - A strict, provider-specific prefix or cryptographically distinct
    token format (no generic keyword-only patterns)
  - A matching live verification endpoint (paired with Tier 6 verifier
    wave where applicable)
  - Confidence ≥ 0.90 (low FP risk by construction)

Focus: providers that either surfaced during recent benchmark scans
or have well-documented partner-token formats that users actually
hardcode.
"""

from services.secret_scan.detectors.base import SecretRule


RULES: list[SecretRule] = [

    # ── AI / LLM (partner-prefix additions) ──────────────────────
    SecretRule(
        rule_id="VOODA-SEC-ANTHROPIC-SK-001",
        title="Anthropic API Key (sk-ant-)",
        secret_type="anthropic_sk_key",
        severity="critical",
        pattern=r'\b(sk-ant-api03-[A-Za-z0-9_-]{93}AA)\b',
        keywords=["sk-ant-api03-"],
        confidence=0.99,
        description="Anthropic Claude API key (sk-ant-api03- prefix, 108 chars).",
        fix_hint="Revoke at console.anthropic.com → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-ANTHROPIC-ADMIN-001",
        title="Anthropic Admin API Key",
        secret_type="anthropic_admin_key",
        severity="critical",
        pattern=r'\b(sk-ant-admin01-[A-Za-z0-9_-]{80,120})\b',
        keywords=["sk-ant-admin01-"],
        confidence=0.99,
        description="Anthropic admin API key — full org administration access.",
        fix_hint="Revoke at console.anthropic.com → Organization → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-COHERE-PREFIX-001",
        title="Cohere API Key (strict format)",
        secret_type="cohere_strict_key",
        severity="high",
        pattern=r'\b(co_[A-Za-z0-9]{40})\b',
        keywords=["co_", "cohere"],
        confidence=0.95,
        description="Cohere API key (co_ prefix, 43 chars).",
        fix_hint="Revoke at dashboard.cohere.com → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-HUGGINGFACE-WRITE-001",
        title="Hugging Face Write Access Token",
        secret_type="huggingface_write_token",
        severity="critical",
        pattern=r'\b(hf_[A-Za-z0-9]{34,40})\b',
        keywords=["hf_"],
        confidence=0.99,
        description="Hugging Face Hub access token (hf_ prefix).",
        fix_hint="Revoke at huggingface.co → Settings → Access Tokens.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-ELEVENLABS-SK-001",
        title="ElevenLabs API Key (sk_)",
        secret_type="elevenlabs_sk_key",
        severity="high",
        pattern=r'\b(sk_[a-f0-9]{48})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['eleven', 'xi_api'],
        post_filter_window=120,
        keywords=["eleven", "ELEVEN", "xi_api"],
        confidence=0.95,
        description="ElevenLabs API key (sk_ + 48 hex chars).",
        fix_hint="Revoke at elevenlabs.io → Profile → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-MISTRAL-API-001",
        title="Mistral AI API Key",
        secret_type="mistral_api_key_v2",
        severity="high",
        pattern=r'(?i)mistral[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["mistral", "MISTRAL"],
        confidence=0.90,
        description="Mistral AI platform API key.",
        fix_hint="Revoke at console.mistral.ai → API Keys.",
    ),

    # ── Auth / IdP ───────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-WORKOS-API-001",
        title="WorkOS API Key (sk_live_)",
        secret_type="workos_api_key",
        severity="critical",
        pattern=r'\b(sk_live_[A-Za-z0-9_-]{40,80}|sk_test_[A-Za-z0-9_-]{40,80})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['workos'],
        post_filter_window=120,
        keywords=["workos", "WORKOS"],
        confidence=0.95,
        description="WorkOS SSO/directory sync API key.",
        fix_hint="Revoke at dashboard.workos.com → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-STYTCH-001",
        title="Stytch Secret Key",
        secret_type="stytch_secret",
        severity="critical",
        pattern=r'\b(secret-(?:test|live)-[A-Za-z0-9_=-]{40,})\b',
        keywords=["secret-test-", "secret-live-", "stytch"],
        confidence=0.98,
        description="Stytch passwordless auth secret key (secret-test/live prefix).",
        fix_hint="Rotate at stytch.com → Dashboard → Projects.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-KINDE-API-001",
        title="Kinde Management API Secret",
        secret_type="kinde_api_secret",
        severity="critical",
        pattern=r'(?i)kinde[^\n]{0,50}(?:m2m|client_secret)[^\n]{0,30}\b([A-Za-z0-9]{48,})\b',
        keywords=["kinde", "KINDE_M2M", "KINDE_CLIENT_SECRET"],
        confidence=0.88,
        description="Kinde auth management client secret.",
        fix_hint="Rotate at app.kinde.com → Settings → APIs.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FRONTEGG-001",
        title="Frontegg Client Secret",
        secret_type="frontegg_client_secret",
        severity="critical",
        pattern=r'(?i)frontegg[^\n]{0,50}(?:client_?secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9-]{36,})\b',
        keywords=["frontegg", "FRONTEGG"],
        confidence=0.88,
        description="Frontegg authentication client secret.",
        fix_hint="Rotate at Frontegg → Integrations → API.",
    ),

    # ── Database & Data Platforms (additional) ───────────────────
    SecretRule(
        rule_id="VOODA-SEC-DATABRICKS-DAPI-001",
        title="Databricks PAT (dapi prefix)",
        secret_type="databricks_pat_v3",
        severity="critical",
        pattern=r'\b(dapi[a-f0-9]{32}(?:-\d+)?)\b',
        keywords=["dapi"],
        confidence=0.99,
        description="Databricks personal access token (dapi + 32 hex).",
        fix_hint="Revoke at databricks.com → User Settings → Developer → Access tokens.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-CLICKHOUSE-CLOUD-001",
        title="ClickHouse Cloud API Password",
        secret_type="clickhouse_cloud_password",
        severity="critical",
        pattern=r'(?i)clickhouse.?cloud[^\n]{0,60}(?:password|pass|pwd)[^\n]{0,30}\b([A-Za-z0-9@._+-]{16,64})\b',
        keywords=["clickhouse", "CLICKHOUSE"],
        confidence=0.82,
        description="ClickHouse Cloud service password.",
        fix_hint="Rotate at console.clickhouse.cloud → Service → Connection.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-NEON-API-001",
        title="Neon Database API Key",
        secret_type="neon_api_key_v2",
        severity="critical",
        pattern=r'\b(neon_api_[A-Za-z0-9_]{40,80})\b',
        keywords=["neon_api_", "neon"],
        confidence=0.98,
        description="Neon Postgres API key (neon_api_ prefix).",
        fix_hint="Revoke at console.neon.tech → Account Settings → API keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-COCKROACHDB-CLOUD-001",
        title="CockroachDB Cloud API Key",
        secret_type="cockroachdb_api_key",
        severity="critical",
        pattern=r'\b(CCDB1_[A-Za-z0-9_=-]{40,})\b',
        keywords=["CCDB1_", "cockroach"],
        confidence=0.99,
        description="CockroachDB Cloud service account API key (CCDB1_ prefix).",
        fix_hint="Rotate at cockroachlabs.cloud → Access Management.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SUPABASE-PSK-001",
        title="Supabase Service Role Key (JWT role=service_role)",
        secret_type="supabase_service_role_jwt",
        severity="critical",
        pattern=r'\b(eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.[A-Za-z0-9_-]{40,120}\.[A-Za-z0-9_-]{40,})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['supabase', 'service_role'],
        post_filter_window=120,
        keywords=["supabase", "SUPABASE", "service_role"],
        confidence=0.92,
        description="Supabase service_role JWT (bypasses RLS).",
        fix_hint="Rotate at supabase.com → Project Settings → API.",
    ),

    # ── Cloud providers (additional) ─────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-VULTR-API-V2-001",
        title="Vultr API Key",
        secret_type="vultr_v2_api_key",
        severity="critical",
        pattern=r'\b([A-Z0-9]{36})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['vultr'],
        post_filter_window=120,
        keywords=["vultr", "VULTR"],
        confidence=0.92,
        description="Vultr personal API key (36-char uppercase alphanumeric).",
        fix_hint="Rotate at my.vultr.com → Account → API.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-HETZNER-CLOUD-001",
        title="Hetzner Cloud API Token",
        secret_type="hetzner_cloud_token_v2",
        severity="critical",
        pattern=r'(?i)hetzner[^\n]{0,50}\b([A-Za-z0-9]{64})\b',
        keywords=["hetzner", "HETZNER"],
        confidence=0.92,
        description="Hetzner Cloud API token (64-char alphanumeric).",
        fix_hint="Revoke at console.hetzner.cloud → Security → API tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SCALEWAY-API-001",
        title="Scaleway API Secret",
        secret_type="scaleway_api_secret",
        severity="critical",
        pattern=r'(?i)scaleway[^\n]{0,50}(?:secret|SECRET)[^\n]{0,30}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["scaleway", "SCW_SECRET_KEY"],
        confidence=0.93,
        description="Scaleway cloud API secret key (UUID format).",
        fix_hint="Rotate at console.scaleway.com → IAM → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BACKBLAZE-B2-001",
        title="Backblaze B2 Application Key",
        secret_type="backblaze_b2_key",
        severity="critical",
        pattern=r'\b(K[0-9]{3}[a-zA-Z0-9+/]{28,32})\b',
        keywords=["backblaze", "B2_APP_KEY"],
        confidence=0.95,
        description="Backblaze B2 application key (K### prefix).",
        fix_hint="Revoke at secure.backblaze.com → Account → Application Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-LINODE-PAT-001",
        title="Linode Personal Access Token",
        secret_type="linode_pat",
        severity="critical",
        pattern=r'(?i)linode[^\n]{0,50}\b([a-f0-9]{64})\b',
        keywords=["linode", "LINODE_TOKEN"],
        confidence=0.93,
        description="Linode/Akamai Cloud personal access token.",
        fix_hint="Revoke at cloud.linode.com → Profile → API Tokens.",
    ),

    # ── Payment processors (additional) ──────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-ADYEN-API-001",
        title="Adyen API Key",
        secret_type="adyen_api_key",
        severity="critical",
        pattern=r'\b(AQE[A-Za-z0-9+/_-]{60,200})\b',
        keywords=["AQE", "adyen"],
        confidence=0.97,
        description="Adyen merchant API key (AQE prefix).",
        fix_hint="Revoke at ca-live.adyen.com → Developers → API credentials.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-KLARNA-001",
        title="Klarna API Secret",
        secret_type="klarna_api_secret",
        severity="critical",
        pattern=r'(?i)klarna[^\n]{0,50}(?:api_secret|KLARNA_SECRET|password)[^\n]{0,30}\b([A-Za-z0-9]{40,64})\b',
        keywords=["klarna", "KLARNA"],
        confidence=0.88,
        description="Klarna Payments API secret.",
        fix_hint="Rotate at playground.klarna.com → Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BRAINTREE-MERCHANT-001",
        title="Braintree Merchant ID + Key",
        secret_type="braintree_merchant",
        severity="critical",
        pattern=r'\b(access_token\$production\$[a-z0-9]{16}\$[a-f0-9]{32})\b',
        keywords=["access_token$production$", "braintree"],
        confidence=0.99,
        description="Braintree production access token (access_token$production$ format).",
        fix_hint="Revoke at Braintree → Account → API → OAuth Applications.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-SQUARE-ACCESS-V2-001",
        title="Square Access Token (production)",
        secret_type="square_access_token_v2",
        severity="critical",
        pattern=r'\b(EAAAl[A-Za-z0-9_-]{60,140})\b',
        keywords=["EAAAl", "square"],
        confidence=0.98,
        description="Square Production access token (EAAAl prefix).",
        fix_hint="Revoke at developer.squareup.com → Apps.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-PLAID-SECRET-001",
        title="Plaid Secret",
        secret_type="plaid_secret",
        severity="critical",
        pattern=r'(?i)plaid[^\n]{0,50}(?:secret|PLAID_SECRET)[^\n]{0,30}\b([a-f0-9]{30})\b',
        keywords=["plaid", "PLAID_SECRET"],
        confidence=0.93,
        description="Plaid banking API secret.",
        fix_hint="Rotate at dashboard.plaid.com → Team Settings → Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DWOLLA-001",
        title="Dwolla API Key",
        secret_type="dwolla_api_key",
        severity="critical",
        pattern=r'(?i)dwolla[^\n]{0,50}\b([A-Za-z0-9]{50,64})\b',
        keywords=["dwolla", "DWOLLA"],
        confidence=0.85,
        description="Dwolla payment platform API key.",
        fix_hint="Rotate at dashboard.dwolla.com → Applications.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CIRCLE-API-001",
        title="Circle API Key (USDC payments)",
        secret_type="circle_api_key",
        severity="critical",
        pattern=r'\b(SAND_API_KEY:[A-Za-z0-9]{40}:[a-f0-9]{32}|LIVE_API_KEY:[A-Za-z0-9]{40}:[a-f0-9]{32})\b',
        keywords=["SAND_API_KEY:", "LIVE_API_KEY:", "circle"],
        confidence=0.99,
        description="Circle USDC payments API key.",
        fix_hint="Rotate at app.circle.com → Developer → API Keys.",
        case_sensitive=True,
    ),

    # ── Observability / Monitoring (additional) ──────────────────
    SecretRule(
        rule_id="VOODA-SEC-DATADOG-APP-V2-001",
        title="Datadog Application Key",
        secret_type="datadog_app_key_v2",
        severity="critical",
        pattern=r'(?i)(?:dd[_-]?app[_-]?key|DD_APPLICATION_KEY)[^\n]{0,30}[:=\s]+\b([a-f0-9]{40})\b',
        keywords=["DD_APPLICATION_KEY", "DD_APP_KEY", "datadog"],
        confidence=0.95,
        description="Datadog application key (40-char hex) with explicit key-name context.",
        fix_hint="Revoke at app.datadoghq.com → Organization Settings → Application Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SUMOLOGIC-ACCESS-001",
        title="Sumo Logic Access Key",
        secret_type="sumologic_access_key",
        severity="critical",
        pattern=r'(?i)sumo(?:logic)?[^\n]{0,50}(?:access[_-]?key|ACCESS_KEY)[^\n]{0,30}\b([A-Za-z0-9]{64})\b',
        keywords=["sumologic", "SUMOLOGIC", "SUMO_ACCESS_KEY"],
        confidence=0.92,
        description="Sumo Logic access key (paired with access ID).",
        fix_hint="Rotate at service.sumologic.com → Preferences → Access Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HONEYCOMB-INGEST-001",
        title="Honeycomb Ingest Key",
        secret_type="honeycomb_ingest_key",
        severity="high",
        pattern=r'\b(hc[a-z]{2,3}ic_[a-z0-9]{58})\b',
        keywords=["hcaic_", "hcbic_", "honeycomb"],
        confidence=0.98,
        description="Honeycomb.io ingest-key (hcXXic_ prefix).",
        fix_hint="Revoke at honeycomb.io → Environment Settings → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-HONEYCOMB-CONFIG-001",
        title="Honeycomb Configuration Key",
        secret_type="honeycomb_config_key",
        severity="critical",
        pattern=r'\b(hc[a-z]{2,3}kc_[a-z0-9]{58})\b',
        keywords=["hcaikc_", "hcbikc_"],
        confidence=0.98,
        description="Honeycomb.io configuration key — broader scope than ingest.",
        fix_hint="Revoke at honeycomb.io → Team Settings → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-LOGZIO-TOKEN-001",
        title="Logz.io Shipping Token",
        secret_type="logzio_token_v2",
        severity="high",
        pattern=r'(?i)logz\.?io[^\n]{0,50}\b([A-Za-z]{32})\b',
        keywords=["logz.io", "LOGZIO_SHIPPING_TOKEN"],
        confidence=0.90,
        description="Logz.io log shipping token.",
        fix_hint="Rotate at app.logz.io → Settings → Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CHRONOSPHERE-001",
        title="Chronosphere API Token",
        secret_type="chronosphere_token",
        severity="critical",
        pattern=r'(?i)chronosphere[^\n]{0,50}\b([A-Za-z0-9]{40,})\b',
        keywords=["chronosphere", "CHRONOSPHERE"],
        confidence=0.85,
        description="Chronosphere observability platform API token.",
        fix_hint="Rotate via Chronosphere admin → API keys.",
    ),

    # ── Email / SMS (additional) ─────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-MAILERSEND-001",
        title="MailerSend API Token",
        secret_type="mailersend_token",
        severity="high",
        pattern=r'\b(mlsn\.[a-f0-9]{60,80})\b',
        keywords=["mlsn."],
        confidence=0.99,
        description="MailerSend API token (mlsn. prefix).",
        fix_hint="Revoke at app.mailersend.com → Tokens.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-SENDINBLUE-V3-001",
        title="Sendinblue/Brevo v3 API Key",
        secret_type="brevo_v3_key",
        severity="critical",
        pattern=r'\b(xkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16})\b',
        keywords=["xkeysib-", "brevo", "sendinblue"],
        confidence=0.99,
        description="Brevo (formerly Sendinblue) v3 API key.",
        fix_hint="Revoke at app.brevo.com → SMTP & API → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-CUSTOMER-IO-001",
        title="Customer.io API Key",
        secret_type="customerio_api_key",
        severity="high",
        pattern=r'(?i)customer\.?io[^\n]{0,50}(?:api_?key|CIO_API)[^\n]{0,30}\b([a-f0-9]{20})\b',
        keywords=["customer.io", "CIO_API_KEY", "customerio"],
        confidence=0.93,
        description="Customer.io tracking API key.",
        fix_hint="Rotate at fly.customer.io → Settings → Workspace Settings → API Credentials.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-INFOBIP-001",
        title="Infobip API Key",
        secret_type="infobip_api_key",
        severity="high",
        pattern=r'\b(App [A-Za-z0-9]{32}-[a-f0-9]{12})\b',
        keywords=["App ", "infobip"],
        confidence=0.95,
        description="Infobip CPaaS API key (App prefix format).",
        fix_hint="Revoke at portal.infobip.com → Developers → API keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-COURIER-001",
        title="Courier API Key",
        secret_type="courier_api_key",
        severity="high",
        pattern=r'(?i)courier[^\n]{0,50}(?:auth_?token|API_KEY)[^\n]{0,30}\b(pk_prod_[A-Z0-9]{40,}|pk_dev_[A-Z0-9]{40,})\b',
        keywords=["pk_prod_", "pk_dev_", "courier"],
        confidence=0.96,
        description="Courier multi-channel notification API key.",
        fix_hint="Rotate at app.courier.com → Settings → API Keys.",
    ),

    # ── DevOps / Infrastructure (additional) ─────────────────────
    SecretRule(
        rule_id="VOODA-SEC-PULUMI-V2-001",
        title="Pulumi Access Token (v2)",
        secret_type="pulumi_access_token_v2",
        severity="critical",
        pattern=r'\b(pul-[a-f0-9]{40})\b',
        keywords=["pul-", "pulumi"],
        confidence=0.99,
        description="Pulumi cloud access token (pul- prefix).",
        fix_hint="Revoke at app.pulumi.com → Settings → Access Tokens.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-VAGRANT-CLOUD-001",
        title="Vagrant Cloud Token",
        secret_type="vagrant_cloud_token",
        severity="high",
        pattern=r'(?i)vagrant[_-]?cloud[^\n]{0,50}\b([A-Za-z0-9]{40,})\b',
        keywords=["vagrantcloud", "vagrant_cloud", "VAGRANT_CLOUD"],
        confidence=0.85,
        description="HashiCorp Vagrant Cloud access token.",
        fix_hint="Rotate at app.vagrantup.com → Account → Security → Authentication Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TERRAFORM-CLOUD-V2-001",
        title="Terraform Cloud Token (atlasv1)",
        secret_type="terraform_cloud_token_v2",
        severity="critical",
        pattern=r'\b([A-Za-z0-9]{14}\.atlasv1\.[A-Za-z0-9_-]{60,70})\b',
        keywords=["atlasv1", "terraform"],
        confidence=0.99,
        description="Terraform Cloud / HCP Terraform user or team token.",
        fix_hint="Revoke at app.terraform.io → User Settings → Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SENTRY-AUTH-001",
        title="Sentry Auth Token (sntrys_)",
        secret_type="sentry_auth_token",
        severity="critical",
        pattern=r'\b(sntrys_[A-Za-z0-9_]{100,240})\b',
        keywords=["sntrys_"],
        confidence=0.99,
        description="Sentry org auth token (sntrys_ prefix).",
        fix_hint="Revoke at sentry.io → Settings → Auth Tokens.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-SENTRY-USER-001",
        title="Sentry User Auth Token (sntryu_)",
        secret_type="sentry_user_auth_token",
        severity="critical",
        pattern=r'\b(sntryu_[A-Za-z0-9]{60,64})\b',
        keywords=["sntryu_"],
        confidence=0.99,
        description="Sentry user auth token (sntryu_ prefix).",
        fix_hint="Revoke at sentry.io → Settings → Account → User Auth Tokens.",
        case_sensitive=True,
    ),

    # ── SaaS productivity (additional) ───────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-CALENDLY-PAT-001",
        title="Calendly Personal Access Token",
        secret_type="calendly_pat_v2",
        severity="high",
        pattern=r'\b(eyJraWQiOi[A-Za-z0-9_-]{60,}\.[A-Za-z0-9_-]{80,300}\.[A-Za-z0-9_-]{40,120})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['calendly'],
        post_filter_window=120,
        keywords=["calendly", "CALENDLY"],
        confidence=0.95,
        description="Calendly personal access token (JWT with kid header).",
        fix_hint="Revoke at calendly.com → Integrations → API & Webhooks.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MIRO-001",
        title="Miro OAuth Access Token",
        secret_type="miro_oauth_token",
        severity="high",
        pattern=r'(?i)miro[^\n]{0,50}\b([A-Za-z0-9_-]{40,64})\b',
        keywords=["miro", "MIRO"],
        confidence=0.82,
        description="Miro collaboration platform OAuth access token.",
        fix_hint="Revoke at miro.com → Account → Apps.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LOOM-001",
        title="Loom API Token",
        secret_type="loom_api_token",
        severity="medium",
        pattern=r'(?i)loom[^\n]{0,50}(?:api_?token|LOOM_TOKEN)[^\n]{0,30}\b([A-Za-z0-9_-]{40,})\b',
        keywords=["loom", "LOOM_TOKEN"],
        confidence=0.85,
        description="Loom video recording API token.",
        fix_hint="Rotate at loom.com → Settings → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-NOTION-INTEG-001",
        title="Notion Integration Secret (secret_ prefix)",
        secret_type="notion_integration_secret",
        severity="high",
        pattern=r'\b(secret_[A-Za-z0-9]{43})\b',
        keywords=["secret_", "notion"],
        confidence=0.95,
        description="Notion internal integration token (secret_ + 43 chars).",
        fix_hint="Revoke at notion.so/my-integrations.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-NOTION-PUBLIC-001",
        title="Notion Public Integration Token (ntn_ prefix)",
        secret_type="notion_public_integration",
        severity="critical",
        pattern=r'\b(ntn_[A-Za-z0-9]{45})\b',
        keywords=["ntn_"],
        confidence=0.99,
        description="Notion public integration token (ntn_ prefix).",
        fix_hint="Revoke at notion.so/my-integrations → Integration → Secrets.",
        case_sensitive=True,
    ),

    # ── HR / Payroll ─────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-RIPPLING-001",
        title="Rippling API Token",
        secret_type="rippling_api_token",
        severity="critical",
        pattern=r'(?i)rippling[^\n]{0,50}(?:api_?token|API_TOKEN)[^\n]{0,30}\b([A-Za-z0-9_-]{40,})\b',
        keywords=["rippling", "RIPPLING"],
        confidence=0.85,
        description="Rippling HR platform API token.",
        fix_hint="Rotate at app.rippling.com → Integrations → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DEEL-001",
        title="Deel API Key",
        secret_type="deel_api_key",
        severity="critical",
        pattern=r'(?i)deel[^\n]{0,50}(?:api_?key|DEEL_API)[^\n]{0,30}\b([A-Za-z0-9_-]{40,})\b',
        keywords=["deel", "DEEL_API"],
        confidence=0.82,
        description="Deel global payroll API key.",
        fix_hint="Rotate at app.deel.com → Settings → Integrations.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ADP-001",
        title="ADP API Credentials",
        secret_type="adp_api_secret",
        severity="critical",
        pattern=r'(?i)adp[^\n]{0,50}(?:client_?secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9-]{36})\b',
        keywords=["adp", "ADP"],
        confidence=0.85,
        description="ADP workforce/payroll API client secret.",
        fix_hint="Rotate at ADP developer portal.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PAYCHEX-001",
        title="Paychex API Secret",
        secret_type="paychex_api_secret",
        severity="critical",
        pattern=r'(?i)paychex[^\n]{0,50}(?:secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9_-]{32,})\b',
        keywords=["paychex", "PAYCHEX"],
        confidence=0.85,
        description="Paychex payroll API secret.",
        fix_hint="Rotate at developer.paychex.com.",
    ),

    # ── CRM / Sales (additional) ─────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-SALESFORCE-TOKEN-001",
        title="Salesforce OAuth Access Token",
        secret_type="salesforce_oauth_token",
        severity="critical",
        pattern=r'\b(00D[A-Za-z0-9]{12,15}![A-Za-z0-9._]{60,200})\b',
        keywords=["00D", "salesforce", "SFDC"],
        confidence=0.97,
        description="Salesforce OAuth access token (00D org ID + ! + signature).",
        fix_hint="Revoke at Salesforce → Setup → App Manager → Connected Apps.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HUBSPOT-PAT-001",
        title="HubSpot Private App Access Token",
        secret_type="hubspot_private_app_token",
        severity="critical",
        pattern=r'\b(pat-na1-[a-f0-9-]{36}|pat-eu1-[a-f0-9-]{36})\b',
        keywords=["pat-na1-", "pat-eu1-", "hubspot"],
        confidence=0.99,
        description="HubSpot private app access token (pat-na1/eu1- prefix).",
        fix_hint="Revoke at HubSpot → Settings → Integrations → Private Apps.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-OUTREACH-001",
        title="Outreach API Token",
        secret_type="outreach_api_token",
        severity="high",
        pattern=r'(?i)outreach[^\n]{0,50}\b([A-Za-z0-9]{64})\b',
        keywords=["outreach", "OUTREACH"],
        confidence=0.80,
        description="Outreach sales engagement API token.",
        fix_hint="Rotate at outreach.io → Settings → API Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GONG-001",
        title="Gong API Access Key",
        secret_type="gong_api_key",
        severity="high",
        pattern=r'(?i)gong[^\n]{0,50}(?:access_?key|API_KEY)[^\n]{0,30}\b([A-Za-z0-9+/=]{40,})\b',
        keywords=["gong", "GONG"],
        confidence=0.82,
        description="Gong revenue intelligence API access key.",
        fix_hint="Rotate at gong.io → Company Settings → Ecosystem → API.",
    ),

    # ── E-commerce (additional) ──────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-SHOPIFY-PARTNER-001",
        title="Shopify Partner Token (prtapi_ prefix)",
        secret_type="shopify_partner_token",
        severity="critical",
        pattern=r'\b(prtapi_[a-f0-9]{32})\b',
        keywords=["prtapi_"],
        confidence=0.99,
        description="Shopify Partner API token (prtapi_ prefix).",
        fix_hint="Rotate at Shopify Partners → API clients.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-BIGCOMMERCE-V3-001",
        title="BigCommerce Store API Token",
        secret_type="bigcommerce_store_token",
        severity="critical",
        pattern=r'(?i)bigcommerce[^\n]{0,50}(?:access_?token|AUTH_TOKEN)[^\n]{0,30}\b([a-z0-9]{31})\b',
        keywords=["bigcommerce", "BIGCOMMERCE"],
        confidence=0.88,
        description="BigCommerce store-level API access token.",
        fix_hint="Revoke at BigCommerce → Advanced Settings → API Accounts.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-WOOCOMMERCE-PAIR-001",
        title="WooCommerce REST API Key Pair",
        secret_type="woocommerce_cs_key",
        severity="critical",
        pattern=r'\b(cs_[a-f0-9]{40})\b',
        keywords=["cs_", "woocommerce", "WOO_"],
        confidence=0.95,
        description="WooCommerce REST API consumer secret (cs_ + 40 hex).",
        fix_hint="Revoke at WooCommerce → WP Admin → Settings → Advanced → REST API.",
        case_sensitive=True,
    ),

    # ── Analytics / Marketing (additional) ───────────────────────
    SecretRule(
        rule_id="VOODA-SEC-MIXPANEL-SA-001",
        title="Mixpanel Service Account Secret",
        secret_type="mixpanel_sa_secret",
        severity="high",
        pattern=r'(?i)mixpanel[^\n]{0,50}(?:service_?account|SERVICE_ACCOUNT)[^\n]{0,30}\b([a-f0-9]{32})\b',
        keywords=["mixpanel", "MIXPANEL_SA"],
        confidence=0.90,
        description="Mixpanel service account secret.",
        fix_hint="Rotate at mixpanel.com → Project Settings → Service Accounts.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-AMPLITUDE-SECRET-001",
        title="Amplitude API Secret Key",
        secret_type="amplitude_secret_key",
        severity="critical",
        pattern=r'(?i)amplitude[^\n]{0,60}(?:secret|API_SECRET)[^\n]{0,30}\b([a-f0-9]{32})\b',
        keywords=["amplitude", "AMPLITUDE_API_SECRET"],
        confidence=0.92,
        description="Amplitude analytics secret key (full R/W access).",
        fix_hint="Rotate at analytics.amplitude.com → Project Settings → General.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MAPBOX-SECRET-001",
        title="Mapbox Secret Token",
        secret_type="mapbox_sk_token",
        severity="critical",
        pattern=r'\b(sk\.eyJ[A-Za-z0-9_-]{60,300}\.[A-Za-z0-9_-]{40,100})\b',
        keywords=["sk.eyJ", "mapbox"],
        confidence=0.99,
        description="Mapbox secret access token (sk. prefix, JWT format).",
        fix_hint="Revoke at account.mapbox.com → Access tokens.",
        case_sensitive=True,
    ),

    # ── Content / CDN (additional) ───────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-CLOUDFLARE-WORKERS-001",
        title="Cloudflare Workers Token",
        secret_type="cloudflare_workers_token",
        severity="critical",
        pattern=r'(?i)cloudflare[^\n]{0,50}(?:workers|WORKER)[^\n]{0,30}\b([A-Za-z0-9_-]{40})\b',
        keywords=["cloudflare", "CF_API_TOKEN", "workers"],
        confidence=0.88,
        description="Cloudflare Workers scoped API token.",
        fix_hint="Revoke at dash.cloudflare.com → My Profile → API Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FASTLY-API-001",
        title="Fastly API Token",
        secret_type="fastly_api_token",
        severity="critical",
        pattern=r'(?i)fastly[^\n]{0,50}(?:api_?token|FASTLY_API_KEY)[^\n]{0,30}\b([A-Za-z0-9_-]{32})\b',
        keywords=["fastly", "FASTLY_API_KEY"],
        confidence=0.92,
        description="Fastly CDN API token.",
        fix_hint="Revoke at manage.fastly.com → Account → API Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BUNNY-CDN-001",
        title="Bunny.net CDN API Key",
        secret_type="bunny_cdn_key",
        severity="critical",
        pattern=r'(?i)bunny[^\n]{0,50}(?:api_?key|AccessKey)[^\n]{0,30}\b([a-f0-9-]{36,64})\b',
        keywords=["bunny", "BUNNY_API_KEY"],
        confidence=0.90,
        description="Bunny.net CDN API access key.",
        fix_hint="Rotate at dash.bunny.net → API.",
    ),

    # ── Notifications / Chat ─────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-DISCORD-WEBHOOK-001",
        title="Discord Webhook URL",
        secret_type="discord_webhook_url",
        severity="high",
        pattern=r'https://discord(?:app)?\.com/api/webhooks/\d{17,19}/[A-Za-z0-9_-]{60,80}',
        keywords=["discord.com/api/webhooks", "discordapp.com/api/webhooks"],
        confidence=0.99,
        description="Discord webhook URL (full bypass of auth for posting).",
        fix_hint="Delete at Discord → Server Settings → Integrations → Webhooks.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MSTEAMS-WEBHOOK-001",
        title="Microsoft Teams Webhook URL",
        secret_type="teams_webhook_url",
        severity="high",
        pattern=r'https://[a-zA-Z0-9-]+\.webhook\.office\.com/webhookb2/[a-f0-9-]{36}@[a-f0-9-]{36}/IncomingWebhook/[a-f0-9]{32}/[a-f0-9-]{36}',
        keywords=["webhook.office.com"],
        confidence=0.99,
        description="Microsoft Teams incoming webhook URL.",
        fix_hint="Delete at Teams → Connectors → Incoming Webhook.",
    ),
    # VOODA-SEC-SLACK-WEBHOOK-002 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-SLACK-WEBHOOK-001
    # (the lower-number id preserved for backwards compatibility).
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.
    SecretRule(
        rule_id="VOODA-SEC-PAGERDUTY-ROUTING-001",
        title="PagerDuty Events Integration Key",
        secret_type="pagerduty_integration_key",
        severity="high",
        pattern=r'(?i)(?:pagerduty|PAGERDUTY)[^\n]{0,50}(?:integration_?key|ROUTING_KEY)[^\n]{0,30}\b([a-f0-9]{32})\b',
        keywords=["pagerduty", "PAGERDUTY", "ROUTING_KEY"],
        confidence=0.93,
        description="PagerDuty Events API v2 integration/routing key.",
        fix_hint="Rotate at pagerduty.com → Services → Integrations.",
    ),

    # ── Security scanners (meta) ─────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-GITGUARDIAN-SERVICE-001",
        title="GitGuardian Service Account Token",
        secret_type="gitguardian_service_token",
        severity="critical",
        pattern=r'(?i)gitguardian[^\n]{0,50}(?:service_?account|SA_TOKEN)[^\n]{0,30}\b([A-Za-z0-9]{60,80})\b',
        keywords=["gitguardian", "GITGUARDIAN_SA"],
        confidence=0.90,
        description="GitGuardian service account API token.",
        fix_hint="Revoke at dashboard.gitguardian.com → Settings → Service Accounts.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SNYK-ORG-001",
        title="Snyk Org API Token",
        secret_type="snyk_org_api_token",
        severity="critical",
        pattern=r'(?i)snyk[^\n]{0,60}(?:token|API_TOKEN)[^\n]{0,30}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["snyk", "SNYK_API_TOKEN"],
        confidence=0.93,
        description="Snyk organization API token (UUID).",
        fix_hint="Revoke at app.snyk.io → Account Settings → API Token.",
    ),

    # ── Web3 (additional) ───────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-ALCHEMY-URL-001",
        title="Alchemy RPC URL with API Key",
        secret_type="alchemy_rpc_url",
        severity="critical",
        pattern=r'https://[a-z0-9-]+\.(?:g|dashboard)\.alchemy\.com/v2/([A-Za-z0-9_-]{32,40})',
        keywords=["alchemy.com"],
        confidence=0.99,
        description="Alchemy Web3 RPC URL with embedded API key.",
        fix_hint="Rotate at dashboard.alchemy.com → Apps → View Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-INFURA-URL-001",
        title="Infura Project URL with ID",
        secret_type="infura_project_url",
        severity="critical",
        pattern=r'https://[a-z-]+\.infura\.io/v3/([a-f0-9]{32})',
        keywords=["infura.io"],
        confidence=0.99,
        description="Infura Web3 RPC URL with embedded project ID.",
        fix_hint="Rotate at app.infura.io → Settings → Projects.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-QUICKNODE-URL-001",
        title="QuickNode Endpoint URL with Auth",
        secret_type="quicknode_url",
        severity="critical",
        pattern=r'https://[a-z0-9.-]{10,80}\.quiknode\.pro/[a-f0-9]{32,64}',
        keywords=["quiknode.pro"],
        confidence=0.99,
        description="QuickNode Web3 RPC URL with embedded auth token.",
        fix_hint="Rotate at quicknode.com → Endpoints → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ETHERSCAN-CONTEXT-001",
        title="Etherscan API Key (strict uppercase)",
        secret_type="etherscan_strict_key",
        severity="medium",
        pattern=r'\b([A-Z0-9]{34})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['etherscan'],
        post_filter_window=120,
        keywords=["etherscan", "ETHERSCAN"],
        confidence=0.92,
        description="Etherscan blockchain explorer API key (34-char uppercase).",
        fix_hint="Rotate at etherscan.io → API Keys.",
        case_sensitive=True,
    ),

    # ── Utility / miscellaneous high-value ───────────────────────
    SecretRule(
        rule_id="VOODA-SEC-DOPPLER-SA-001",
        title="Doppler Service Account Token (dp.sa.)",
        secret_type="doppler_service_account_token",
        severity="critical",
        pattern=r'\b(dp\.sa\.[A-Za-z0-9._-]{40,60})\b',
        keywords=["dp.sa."],
        confidence=0.99,
        description="Doppler service account token (dp.sa. prefix).",
        fix_hint="Revoke at dashboard.doppler.com → Access → Service Accounts.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-DOPPLER-CT-001",
        title="Doppler CLI Token (dp.ct.)",
        secret_type="doppler_cli_token",
        severity="critical",
        pattern=r'\b(dp\.ct\.[A-Za-z0-9._-]{40,60})\b',
        keywords=["dp.ct."],
        confidence=0.99,
        description="Doppler CLI login token (dp.ct. prefix).",
        fix_hint="Run `doppler logout` to invalidate; also rotate at dashboard.doppler.com.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-FLY-MACAROON-001",
        title="Fly.io Macaroon Token (FlyV1)",
        secret_type="fly_macaroon",
        severity="critical",
        pattern=r'\b(FlyV1 [A-Za-z0-9_/=,-]{200,})\b',
        keywords=["FlyV1"],
        confidence=0.99,
        description="Fly.io macaroon API token (FlyV1 prefix).",
        fix_hint="Revoke via `fly tokens revoke` or web UI.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-AWS-TEMP-CRED-001",
        title="AWS Temporary Session Token",
        secret_type="aws_session_token_ctx",
        severity="critical",
        pattern=r'\b(FQoGZXIv[A-Za-z0-9+/=]{100,}|FwoGZXIv[A-Za-z0-9+/=]{100,}|IQoJb3JpZ2lu[A-Za-z0-9+/=]{100,})\b',
        keywords=["FQoGZXIv", "FwoGZXIv", "IQoJb3JpZ2lu"],
        confidence=0.99,
        description="AWS STS temporary session token (multiple STS prefixes).",
        fix_hint="Session tokens expire but rotate access key pair if leaked.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-GCP-API-AIZA-001",
        title="Google Cloud API Key",
        secret_type="gcp_api_key",
        severity="critical",
        pattern=r'\b(AIza[0-9A-Za-z_-]{35})\b',
        keywords=["AIza"],
        confidence=0.99,
        description="Google Cloud API key (AIza prefix + 35 chars).",
        fix_hint="Restrict/rotate at console.cloud.google.com → APIs & Services → Credentials.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-GITHUB-APP-PRIVATE-001",
        title="GitHub App Private Key (PEM)",
        secret_type="github_app_private_key",
        severity="critical",
        # Body cap shrunk from {200,4000} → {200,1000} for re2
        # compatibility (Option B-2, 2026-05-24).  Same tradeoff as
        # VOODA-SEC-VONAGE-APP-001 — RSA-4096 PEM bodies (~3.3 KB)
        # are NOT caught by this specific rule after the change.
        # Keyword pre-filter still surfaces them to generic-PEM
        # detection paths.  Tracked as B-2-followup for an extension
        # that uses a post-match Python expander to handle large
        # bodies without losing secret_hash uniqueness.
        pattern=r'-----BEGIN (?:RSA )?PRIVATE KEY-----[\s\S]{200,1000}-----END (?:RSA )?PRIVATE KEY-----',
        keywords=["BEGIN PRIVATE KEY", "BEGIN RSA PRIVATE KEY"],
        confidence=0.95,
        description="PEM-format private key (GitHub App, Vonage, SSH, etc.).",
        fix_hint="Rotate the key at the provider; never commit to source.",
        multiline=True,
    ),

    # ── AI/ML (additional providers) ─────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-OPENAI-ADMIN-001",
        title="OpenAI Admin Key (sk-admin-)",
        secret_type="openai_admin_key",
        severity="critical",
        pattern=r'\b(sk-admin-[A-Za-z0-9_-]{40,100})\b',
        keywords=["sk-admin-"],
        confidence=0.99,
        description="OpenAI admin API key — full org administration.",
        fix_hint="Revoke at platform.openai.com → Organization → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-TOGETHER-AI-001",
        title="Together AI API Key",
        secret_type="together_ai_api_key",
        severity="high",
        pattern=r'\b([a-f0-9]{64})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['together'],
        post_filter_window=120,
        keywords=["together", "TOGETHER_API"],
        confidence=0.90,
        description="Together AI inference API key (64-char hex).",
        fix_hint="Revoke at api.together.ai → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FIREWORKS-AI-V2-001",
        title="Fireworks AI Key (fw_)",
        secret_type="fireworks_ai_key",
        severity="high",
        pattern=r'\b(fw_[A-Za-z0-9]{20,40})\b',
        keywords=["fw_", "fireworks"],
        confidence=0.98,
        description="Fireworks.ai inference API key (fw_ prefix).",
        fix_hint="Revoke at fireworks.ai → Account → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-GROQ-GSK-001",
        title="Groq API Key (gsk_)",
        secret_type="groq_gsk_key",
        severity="high",
        pattern=r'\b(gsk_[A-Za-z0-9]{52})\b',
        keywords=["gsk_", "groq"],
        confidence=0.99,
        description="Groq LLM inference API key (gsk_ prefix).",
        fix_hint="Revoke at console.groq.com → API Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-PERPLEXITY-PPLX-001",
        title="Perplexity API Key (pplx-)",
        secret_type="perplexity_api_key",
        severity="high",
        pattern=r'\b(pplx-[A-Za-z0-9]{48,64})\b',
        keywords=["pplx-", "perplexity"],
        confidence=0.99,
        description="Perplexity AI API key (pplx- prefix).",
        fix_hint="Revoke at perplexity.ai → Settings → API.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-DEEPSEEK-SK-001",
        title="DeepSeek API Key (sk-)",
        secret_type="deepseek_sk_key",
        severity="high",
        pattern=r'\b(sk-[a-f0-9]{32})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['deepseek'],
        post_filter_window=120,
        keywords=["deepseek", "DEEPSEEK"],
        confidence=0.92,
        description="DeepSeek API key (sk- + 32 hex chars with context).",
        fix_hint="Rotate at platform.deepseek.com → API Keys.",
    ),

    # ── Security threat intel (additional) ───────────────────────
    SecretRule(
        rule_id="VOODA-SEC-VIRUSTOTAL-V3-001",
        title="VirusTotal API Key",
        secret_type="virustotal_api_key",
        severity="high",
        pattern=r'(?i)(?:virustotal|VT_API)[^\n]{0,50}\b([a-f0-9]{64})\b',
        keywords=["virustotal", "VT_API_KEY"],
        confidence=0.95,
        description="VirusTotal threat intelligence API key (64-char hex).",
        fix_hint="Revoke at virustotal.com → Profile → API Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SHODAN-001",
        title="Shodan API Key",
        secret_type="shodan_api_key",
        severity="high",
        pattern=r'(?i)shodan[^\n]{0,50}\b([a-zA-Z0-9]{32})\b',
        keywords=["shodan", "SHODAN_API_KEY"],
        confidence=0.92,
        description="Shodan internet search API key.",
        fix_hint="Rotate at account.shodan.io.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-URLSCAN-001",
        title="urlscan.io API Key",
        secret_type="urlscan_api_key",
        severity="medium",
        pattern=r'(?i)urlscan[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["urlscan", "URLSCAN_API_KEY"],
        confidence=0.93,
        description="urlscan.io URL scanning API key.",
        fix_hint="Revoke at urlscan.io → Account → API Keys.",
    ),
]
