# SPDX-FileCopyrightText: 2026 Virantis
# SPDX-License-Identifier: LicenseRef-Vooda-Community-1.0

from __future__ import annotations
"""
TruffleHog Port v2 — Wave 2 expansion to 100 additional providers.

This file adds coverage for the long-tail providers that Stage 1 didn't
touch: threat-intel APIs, financial data, weather, translation, headless
CMS, identity verification, more AI/LLM providers, and additional cloud
hosts. Every rule targets a format with a provider-specific prefix or
keyword context so precision stays high.
"""

from services.secret_scan.detectors.base import SecretRule


RULES: list[SecretRule] = [

    # ── AI / LLM (long tail) ─────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-AI21-001",
        title="AI21 Labs API Key",
        secret_type="ai21_api_key",
        severity="high",
        pattern=r'(?i)ai21[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["ai21", "AI21"],
        confidence=0.88,
        description="AI21 Labs API key (Jurassic language models).",
        fix_hint="Revoke at studio.ai21.com → Account → API Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GOOGLE-AI-STUDIO-001",
        title="Google AI Studio (Gemini) API Key",
        secret_type="google_ai_studio_key",
        severity="high",
        pattern=r'\b(AIza[0-9A-Za-z_-]{35})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['gemini', 'GOOGLE_AI_STUDIO', 'GenerativeAI'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["gemini", "GEMINI", "GOOGLE_AI_STUDIO", "GenerativeAI"],
        confidence=0.90,
        description="Google AI Studio / Gemini API key (AIza… with context).",
        fix_hint="Revoke at aistudio.google.com → Get API key.",
    ),
    # VOODA-SEC-FIREWORKS-AI-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-FIREWORKS-AI-V2-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.
    SecretRule(
        rule_id="VOODA-SEC-NOVITA-AI-001",
        title="Novita AI API Key",
        secret_type="novita_api_key",
        severity="high",
        pattern=r'\b(novita_[A-Za-z0-9_-]{32,64})\b',
        keywords=["novita_", "novita"],
        confidence=0.96,
        description="Novita.ai inference API key.",
        fix_hint="Revoke at novita.ai → Settings → Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DEEPL-FREE-001",
        title="DeepL Free API Key",
        secret_type="deepl_free_key",
        severity="medium",
        pattern=r'\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}:fx)\b',
        keywords=["deepl", ":fx", "DEEPL"],
        confidence=0.99,
        description="DeepL free-tier API key (ends with :fx).",
        fix_hint="Revoke at deepl.com → Account → DeepL API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DEEPL-PRO-001",
        title="DeepL Pro API Key",
        secret_type="deepl_pro_key",
        severity="high",
        pattern=r'\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['deepl'],
        post_filter_window=100,
        keywords=["deepl", "DEEPL"],
        confidence=0.92,
        description="DeepL Pro API key.",
        fix_hint="Revoke at deepl.com → Account → DeepL API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-RUNWAY-001",
        title="RunwayML API Key",
        secret_type="runway_api_key",
        severity="high",
        pattern=r'\b(key_[a-f0-9]{48})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['runway'],
        post_filter_window=120,
        keywords=["runway", "RUNWAY"],
        confidence=0.92,
        description="RunwayML video generation API key.",
        fix_hint="Revoke at runwayml.com → Account → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ELEVENLABS-001",
        title="ElevenLabs API Key",
        secret_type="elevenlabs_api_key",
        severity="high",
        pattern=r'\b(xi_[a-f0-9]{32,48}|sk_[a-f0-9]{48})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['eleven', 'XI_API'],
        post_filter_window=120,
        keywords=["elevenlabs", "ELEVEN", "XI_API"],
        confidence=0.90,
        description="ElevenLabs text-to-speech API key.",
        fix_hint="Revoke at elevenlabs.io → Profile → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CHARACTER-AI-001",
        title="Character.AI Token",
        secret_type="character_ai_token",
        severity="medium",
        pattern=r'(?i)character\.?ai[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["character.ai", "CHARACTER_AI"],
        confidence=0.85,
        description="Character.AI session token.",
        fix_hint="Re-authenticate at character.ai and revoke session.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SUNO-001",
        title="Suno AI API Key",
        secret_type="suno_api_key",
        severity="medium",
        pattern=r'(?i)suno[^\n]{0,50}\b([A-Za-z0-9_-]{32,64})\b',
        keywords=["suno", "SUNO"],
        confidence=0.82,
        description="Suno AI music generation API key.",
        fix_hint="Revoke at suno.com → Settings → API Access.",
    ),

    # ── Financial Data APIs ──────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-POLYGON-IO-001",
        title="Polygon.io API Key",
        secret_type="polygon_io_key",
        severity="high",
        pattern=r'(?i)polygon\.?io[^\n]{0,50}\b([A-Za-z0-9_]{32})\b',
        keywords=["polygon.io", "POLYGON"],
        confidence=0.88,
        description="Polygon.io stock market data API key.",
        fix_hint="Revoke at polygon.io → Account → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ALPHAVANTAGE-001",
        title="Alpha Vantage API Key",
        secret_type="alphavantage_api_key",
        severity="medium",
        pattern=r'(?i)alpha.?vantage[^\n]{0,50}\b([A-Z0-9]{16})\b',
        keywords=["alphavantage", "ALPHAVANTAGE"],
        confidence=0.90,
        description="Alpha Vantage financial data API key.",
        fix_hint="Request new at alphavantage.co.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FINNHUB-001",
        title="Finnhub API Key",
        secret_type="finnhub_api_key",
        severity="medium",
        pattern=r'(?i)finnhub[^\n]{0,50}\b([a-z0-9]{40})\b',
        keywords=["finnhub", "FINNHUB"],
        confidence=0.90,
        description="Finnhub stock market API key.",
        fix_hint="Revoke at finnhub.io → Dashboard → API Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TIINGO-001",
        title="Tiingo API Key",
        secret_type="tiingo_api_key",
        severity="medium",
        pattern=r'(?i)tiingo[^\n]{0,50}\b([a-f0-9]{40})\b',
        keywords=["tiingo", "TIINGO"],
        confidence=0.90,
        description="Tiingo financial data API key.",
        fix_hint="Revoke at tiingo.com → Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-OPENEXCHANGE-001",
        title="OpenExchangeRates App ID",
        secret_type="openexchange_app_id",
        severity="medium",
        pattern=r'(?i)openexchangerates[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["openexchangerates", "OXR", "OPENEXCHANGE"],
        confidence=0.92,
        description="OpenExchangeRates FX API App ID.",
        fix_hint="Revoke at openexchangerates.org → Account → App IDs.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FIXER-IO-001",
        title="Fixer.io Access Key",
        secret_type="fixer_api_key",
        severity="medium",
        pattern=r'(?i)fixer[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["fixer.io", "FIXER"],
        confidence=0.88,
        description="Fixer.io currency API access key.",
        fix_hint="Revoke at fixer.io → Account → API Access Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CURRENCYLAYER-001",
        title="CurrencyLayer API Key",
        secret_type="currencylayer_api_key",
        severity="medium",
        pattern=r'(?i)currencylayer[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["currencylayer", "CURRENCYLAYER"],
        confidence=0.88,
        description="CurrencyLayer exchange-rate API key.",
        fix_hint="Revoke at currencylayer.com → Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-COINMARKETCAP-001",
        title="CoinMarketCap API Key",
        secret_type="coinmarketcap_api_key",
        severity="medium",
        pattern=r'\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['coinmarketcap', 'CMC_API'],
        post_filter_window=120,
        keywords=["coinmarketcap", "COINMARKETCAP", "CMC_API"],
        confidence=0.92,
        description="CoinMarketCap cryptocurrency data API key.",
        fix_hint="Revoke at coinmarketcap.com → Account → API.",
    ),
    # VOODA-SEC-ETHERSCAN-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-ETHERSCAN-CONTEXT-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.
    SecretRule(
        rule_id="VOODA-SEC-ALCHEMY-001",
        title="Alchemy API Key",
        secret_type="alchemy_api_key",
        severity="high",
        pattern=r'(?i)alchemy[^\n]{0,50}\b([A-Za-z0-9_-]{32})\b',
        keywords=["alchemy", "ALCHEMY"],
        confidence=0.85,
        description="Alchemy Web3 API key.",
        fix_hint="Rotate at dashboard.alchemy.com.",
    ),

    # ── Weather APIs ─────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-OPENWEATHER-001",
        title="OpenWeather API Key",
        secret_type="openweather_api_key",
        severity="low",
        pattern=r'(?i)openweather[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["openweather", "OPENWEATHER", "OWM_API"],
        confidence=0.88,
        description="OpenWeatherMap API key.",
        fix_hint="Rotate at openweathermap.org → API keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-WEATHERAPI-001",
        title="WeatherAPI.com Key",
        secret_type="weatherapi_key",
        severity="low",
        pattern=r'(?i)weatherapi[^\n]{0,50}\b([a-f0-9]{31})\b',
        keywords=["weatherapi", "WEATHERAPI"],
        confidence=0.87,
        description="WeatherAPI.com API key.",
        fix_hint="Rotate at weatherapi.com → My Account.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TOMORROWIO-001",
        title="Tomorrow.io API Key",
        secret_type="tomorrow_io_key",
        severity="low",
        pattern=r'(?i)tomorrow\.io[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["tomorrow.io", "TOMORROW_IO"],
        confidence=0.88,
        description="Tomorrow.io (formerly Climacell) weather API key.",
        fix_hint="Rotate at app.tomorrow.io → Development → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-VISUALCROSSING-001",
        title="VisualCrossing Weather Key",
        secret_type="visualcrossing_key",
        severity="low",
        pattern=r'(?i)visualcrossing[^\n]{0,50}\b([A-Z0-9]{25})\b',
        keywords=["visualcrossing", "VISUALCROSSING"],
        confidence=0.85,
        description="VisualCrossing weather API key.",
        fix_hint="Rotate at visualcrossing.com → Account.",
    ),

    # ── Maps / Geo ───────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-HERE-MAPS-001",
        title="HERE Maps API Key",
        secret_type="here_maps_api_key",
        severity="medium",
        pattern=r'(?i)here[_-]?(?:maps?|api)[^\n]{0,50}\b([A-Za-z0-9_-]{43})\b',
        keywords=["here-api", "HERE_API", "here.com"],
        confidence=0.88,
        description="HERE Maps location services API key.",
        fix_hint="Revoke at developer.here.com → Projects.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TOMTOM-001",
        title="TomTom API Key",
        secret_type="tomtom_api_key",
        severity="medium",
        pattern=r'(?i)tomtom[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["tomtom", "TOMTOM"],
        confidence=0.88,
        description="TomTom Maps API key.",
        fix_hint="Revoke at developer.tomtom.com → My Account.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-OPENCAGE-001",
        title="OpenCage Geocoder Key",
        secret_type="opencage_api_key",
        severity="low",
        pattern=r'(?i)opencage[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["opencage", "OPENCAGE"],
        confidence=0.88,
        description="OpenCage geocoding API key.",
        fix_hint="Rotate at opencagedata.com → Dashboard → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LOCATIONIQ-001",
        title="LocationIQ Access Token",
        secret_type="locationiq_token",
        severity="low",
        pattern=r'\b(pk\.[a-f0-9]{32})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['locationiq'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["locationiq", "LOCATIONIQ"],
        confidence=0.93,
        description="LocationIQ geocoding access token.",
        fix_hint="Rotate at locationiq.com → Dashboard → Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-POSITIONSTACK-001",
        title="Positionstack API Key",
        secret_type="positionstack_key",
        severity="low",
        pattern=r'(?i)positionstack[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["positionstack", "POSITIONSTACK"],
        confidence=0.88,
        description="Positionstack forward/reverse geocoding API key.",
        fix_hint="Rotate at positionstack.com → Dashboard → API Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-IPSTACK-001",
        title="IPStack API Key",
        secret_type="ipstack_api_key",
        severity="low",
        pattern=r'(?i)ipstack[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["ipstack", "IPSTACK"],
        confidence=0.88,
        description="IPStack geolocation API key.",
        fix_hint="Rotate at ipstack.com → Dashboard → API Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-IPGEOLOCATION-001",
        title="IPGeolocation.io API Key",
        secret_type="ipgeolocation_api_key",
        severity="low",
        pattern=r'(?i)ipgeolocation[^\n]{0,50}\b([A-Za-z0-9]{32})\b',
        keywords=["ipgeolocation", "IPGEOLOCATION"],
        confidence=0.87,
        description="IPGeolocation.io geolocation API key.",
        fix_hint="Rotate at ipgeolocation.io → Dashboard.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MAXMIND-001",
        title="MaxMind License Key",
        secret_type="maxmind_license_key",
        severity="medium",
        pattern=r'(?i)maxmind[^\n]{0,50}\b([A-Za-z0-9_]{16,})\b',
        keywords=["maxmind", "MAXMIND", "GEOIP_LICENSE"],
        confidence=0.85,
        description="MaxMind GeoIP database license key.",
        fix_hint="Rotate at maxmind.com → Account → Manage License Keys.",
    ),

    # ── Security / Threat Intel ──────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-VIRUSTOTAL-001",
        title="VirusTotal API Key",
        secret_type="virustotal_api_key",
        severity="high",
        pattern=r'(?i)virustotal[^\n]{0,50}\b([a-f0-9]{64})\b',
        keywords=["virustotal", "VIRUSTOTAL", "VT_API_KEY"],
        confidence=0.95,
        description="VirusTotal threat intelligence API key.",
        fix_hint="Revoke at virustotal.com → Profile → API Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CENSYS-ID-001",
        title="Censys API ID",
        secret_type="censys_api_id",
        severity="high",
        pattern=r'\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['censys'],
        post_filter_window=120,
        keywords=["censys", "CENSYS"],
        confidence=0.90,
        description="Censys search API ID (paired with secret).",
        fix_hint="Rotate at censys.io → Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CENSYS-SECRET-001",
        title="Censys API Secret",
        secret_type="censys_api_secret",
        severity="critical",
        pattern=r'\b([A-Za-z0-9]{32})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['censys.*secret'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["censys", "CENSYS_API_SECRET"],
        confidence=0.85,
        description="Censys search API secret (paired with ID).",
        fix_hint="Rotate at censys.io → Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ABUSEIPDB-001",
        title="AbuseIPDB API Key",
        secret_type="abuseipdb_api_key",
        severity="medium",
        pattern=r'(?i)abuseipdb[^\n]{0,50}\b([a-f0-9]{80})\b',
        keywords=["abuseipdb", "ABUSEIPDB"],
        confidence=0.90,
        description="AbuseIPDB threat intelligence API key.",
        fix_hint="Rotate at abuseipdb.com → Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HIBP-001",
        title="HaveIBeenPwned API Key",
        secret_type="hibp_api_key",
        severity="medium",
        pattern=r'\b(hibp_[a-f0-9]{32})\b|(?i:haveibeenpwned)[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["hibp", "haveibeenpwned", "HIBP"],
        confidence=0.92,
        description="HaveIBeenPwned breach data API key.",
        fix_hint="Revoke at haveibeenpwned.com → API key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GREYNOISE-001",
        title="GreyNoise API Key",
        secret_type="greynoise_api_key",
        severity="high",
        pattern=r'(?i)greynoise[^\n]{0,50}\b([A-Za-z0-9]{40})\b',
        keywords=["greynoise", "GREYNOISE"],
        confidence=0.88,
        description="GreyNoise IP intelligence API key.",
        fix_hint="Revoke at viz.greynoise.io → My Profile → API Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CROWDSTRIKE-001",
        title="CrowdStrike Falcon API Client Secret",
        secret_type="crowdstrike_client_secret",
        severity="critical",
        pattern=r'(?i)crowdstrike[^\n]{0,50}(?:client_?secret|secret)[^\n]{0,30}\b([A-Za-z0-9]{40})\b',
        keywords=["crowdstrike", "CROWDSTRIKE"],
        confidence=0.92,
        description="CrowdStrike Falcon platform API client secret.",
        fix_hint="Rotate at falcon.crowdstrike.com → Support → API clients.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SECURITYSCORECARD-001",
        title="SecurityScorecard API Token",
        secret_type="securityscorecard_token",
        severity="high",
        pattern=r'(?i)securityscorecard[^\n]{0,50}\b([A-Za-z0-9]{64})\b',
        keywords=["securityscorecard", "SECURITYSCORECARD"],
        confidence=0.88,
        description="SecurityScorecard risk ratings API token.",
        fix_hint="Revoke at platform.securityscorecard.io → My Settings → API.",
    ),

    # ── Identity Verification / KYC ──────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-PERSONA-001",
        title="Persona API Key",
        secret_type="persona_api_key",
        severity="critical",
        pattern=r'\b(persona_[a-zA-Z0-9_]{20,})\b|\b(sk_live_[A-Za-z0-9]{20,})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['persona'],
        post_filter_window=120,
        keywords=["persona", "PERSONA", "withpersona"],
        confidence=0.90,
        description="Persona identity verification API key.",
        fix_hint="Revoke at withpersona.com → Account → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ONFIDO-001",
        title="Onfido API Token",
        secret_type="onfido_api_token",
        severity="critical",
        pattern=r'\b(api_[a-z_]*(?:live|sandbox|test)\.[A-Za-z0-9_-]{40,})\b',
        keywords=["api_live.", "api_sandbox.", "onfido", "ONFIDO"],
        confidence=0.97,
        description="Onfido identity verification API token.",
        fix_hint="Revoke at onfido.com → Developer Settings → API Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-VERIFF-001",
        title="Veriff API Key",
        secret_type="veriff_api_key",
        severity="critical",
        pattern=r'(?i)veriff[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["veriff", "VERIFF"],
        confidence=0.92,
        description="Veriff identity verification API key.",
        fix_hint="Rotate at station.veriff.com → Integrations → API Key.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-JUMIO-001",
        title="Jumio API Token",
        secret_type="jumio_api_token",
        severity="critical",
        pattern=r'(?i)jumio[^\n]{0,50}\b([a-f0-9-]{32,48})\b',
        keywords=["jumio", "JUMIO"],
        confidence=0.85,
        description="Jumio identity verification API token.",
        fix_hint="Rotate via Jumio support.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SUMSUB-001",
        title="Sumsub API Key",
        secret_type="sumsub_api_key",
        severity="critical",
        pattern=r'\b(sbx:[A-Za-z0-9_-]{30,}|prd:[A-Za-z0-9_-]{30,})\b',
        keywords=["sumsub", "SUMSUB", "sbx:", "prd:"],
        confidence=0.92,
        description="Sumsub KYC API key (sbx: or prd: prefix).",
        fix_hint="Rotate at cockpit.sumsub.com → Dev Space → API Keys.",
    ),

    # ── Headless CMS / Content ───────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-SANITY-IO-001",
        title="Sanity.io Auth Token",
        secret_type="sanity_auth_token",
        severity="high",
        pattern=r'\b(sk[A-Za-z0-9]{80,200})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['sanity'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["sanity", "SANITY"],
        confidence=0.92,
        description="Sanity.io content lake auth token.",
        fix_hint="Revoke at sanity.io → Manage → API → Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PRISMIC-001",
        title="Prismic Access Token",
        secret_type="prismic_access_token",
        severity="high",
        pattern=r'\b(MC[A-Za-z0-9_-]{40,100})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['prismic'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["prismic", "PRISMIC"],
        confidence=0.92,
        description="Prismic headless CMS access token.",
        fix_hint="Rotate at prismic.io → Settings → API & Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-STRAPI-001",
        title="Strapi Admin API Token",
        secret_type="strapi_api_token",
        severity="critical",
        pattern=r'(?i)strapi[^\n]{0,50}(?:token|TOKEN)[^\n]{0,30}\b([A-Fa-f0-9]{64,})\b',
        keywords=["strapi", "STRAPI"],
        confidence=0.90,
        description="Strapi admin API token.",
        fix_hint="Rotate at Strapi admin → Settings → API Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HYGRAPH-001",
        title="Hygraph (GraphCMS) Auth Token",
        secret_type="hygraph_token",
        severity="high",
        pattern=r'(?i)(?:hygraph|graphcms)[^\n]{0,50}\b(eyJ[A-Za-z0-9_-]{100,500}\.[A-Za-z0-9_-]{60,200})\b',
        keywords=["hygraph", "graphcms", "HYGRAPH"],
        confidence=0.95,
        description="Hygraph (formerly GraphCMS) permanent auth token.",
        fix_hint="Revoke at hygraph.com → Project Settings → API Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DATOCMS-001",
        title="DatoCMS API Token",
        secret_type="datocms_api_token",
        severity="high",
        pattern=r'(?i)datocms[^\n]{0,50}\b([a-f0-9]{32,64})\b',
        keywords=["datocms", "DATOCMS"],
        confidence=0.88,
        description="DatoCMS API token.",
        fix_hint="Rotate at datocms.com → Settings → API Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-GHOST-ADMIN-001",
        title="Ghost Admin API Key",
        secret_type="ghost_admin_key",
        severity="critical",
        pattern=r'\b([a-f0-9]{24}:[a-f0-9]{64})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['ghost'],
        post_filter_window=120,
        keywords=["ghost", "GHOST_ADMIN_API"],
        confidence=0.95,
        description="Ghost CMS Admin API key (id:secret format).",
        fix_hint="Rotate at Ghost → Integrations.",
    ),

    # ── E-commerce ───────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-BIGCOMMERCE-001",
        title="BigCommerce Access Token",
        secret_type="bigcommerce_access_token",
        severity="critical",
        pattern=r'(?i)bigcommerce[^\n]{0,50}\b([a-z0-9]{40,64})\b',
        keywords=["bigcommerce", "BIGCOMMERCE"],
        confidence=0.85,
        description="BigCommerce store access token.",
        fix_hint="Rotate at BigCommerce Control Panel → Advanced Settings → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-WOOCOMMERCE-CK-001",
        title="WooCommerce Consumer Key",
        secret_type="woocommerce_ck",
        severity="high",
        pattern=r'\b(ck_[a-f0-9]{40})\b',
        keywords=["ck_", "woocommerce", "WOOCOMMERCE"],
        confidence=0.95,
        description="WooCommerce REST API consumer key.",
        fix_hint="Revoke at WooCommerce → Settings → Advanced → REST API.",
    ),
    # VOODA-SEC-WOOCOMMERCE-CS-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-WOOCOMMERCE-PAIR-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.
    SecretRule(
        rule_id="VOODA-SEC-MEDUSA-001",
        title="Medusa API Token",
        secret_type="medusa_api_token",
        severity="critical",
        pattern=r'(?i)medusa[^\n]{0,50}(?:token|api_key)[^\n]{0,30}\b([A-Za-z0-9_-]{32,64})\b',
        keywords=["medusa", "MEDUSA"],
        confidence=0.85,
        description="Medusa e-commerce admin API token.",
        fix_hint="Rotate at Medusa admin → Settings → Users.",
    ),

    # ── Cloud (additional) ───────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-IBM-CLOUD-IAM-001",
        title="IBM Cloud IAM API Key",
        secret_type="ibm_cloud_iam_key",
        severity="critical",
        pattern=r'(?i)ibmcloud[^\n]{0,50}\b([A-Za-z0-9_-]{44})\b|\b([A-Za-z0-9_-]{44})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['ibmcloud'],
        post_filter_window=120,
        keywords=["ibmcloud", "IBM_CLOUD", "IC_API_KEY"],
        confidence=0.88,
        description="IBM Cloud IAM API key.",
        fix_hint="Revoke at cloud.ibm.com → Manage → Access → API keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-ORACLE-OCI-001",
        title="Oracle Cloud OCI API Key Fingerprint",
        secret_type="oracle_oci_fingerprint",
        severity="critical",
        pattern=r'\b([0-9a-f]{2}(?::[0-9a-f]{2}){15})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['oci', 'ORACLE', 'oracle.com'],
        post_filter_window=120,
        keywords=["oci", "ORACLE", "oracle.com"],
        confidence=0.90,
        description="Oracle Cloud Infrastructure API key fingerprint.",
        fix_hint="Rotate at cloud.oracle.com → Identity → User.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TENCENT-001",
        title="Tencent Cloud SecretId",
        secret_type="tencent_secret_id",
        severity="critical",
        pattern=r'\b(AKID[A-Za-z0-9]{32})\b',
        keywords=["AKID", "tencent", "TENCENT"],
        confidence=0.98,
        description="Tencent Cloud API Secret ID (AKID prefix).",
        fix_hint="Rotate at console.cloud.tencent.com → Access Management.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-YANDEX-CLOUD-001",
        title="Yandex Cloud IAM Token",
        secret_type="yandex_cloud_iam",
        severity="critical",
        pattern=r'\b(t1\.[A-Za-z0-9_-]{300,500}\.[A-Za-z0-9_-]{100,})\b',
        keywords=["t1.", "yandex", "YANDEX_CLOUD"],
        confidence=0.93,
        description="Yandex Cloud IAM bearer token.",
        fix_hint="Rotate via yc iam create-token or console.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-UPCLOUD-001",
        title="UpCloud Account Credentials",
        secret_type="upcloud_password",
        severity="high",
        pattern=r'(?i)upcloud[^\n]{0,50}(?:password|pass)[^\n]{0,30}\b([^\s\'"]{8,40})\b',
        keywords=["upcloud", "UPCLOUD"],
        confidence=0.80,
        description="UpCloud account password.",
        fix_hint="Rotate at hub.upcloud.com → Account → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-EXOSCALE-001",
        title="Exoscale API Key",
        secret_type="exoscale_api_key",
        severity="critical",
        pattern=r'\b(EXO[A-Z0-9]{18,24})\b',
        keywords=["EXO", "exoscale", "EXOSCALE"],
        confidence=0.95,
        description="Exoscale cloud API key (EXO prefix).",
        fix_hint="Rotate at portal.exoscale.com → IAM Access Keys.",
        case_sensitive=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-CIVO-001",
        title="Civo API Key",
        secret_type="civo_api_key",
        severity="critical",
        pattern=r'(?i)civo[^\n]{0,50}\b([A-Za-z0-9]{50,})\b',
        keywords=["civo", "CIVO"],
        confidence=0.82,
        description="Civo cloud API key.",
        fix_hint="Rotate at dashboard.civo.com → Account → API.",
    ),

    # ── Auth / Identity (more) ───────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-DESCOPE-001",
        title="Descope Project Management Key",
        secret_type="descope_management_key",
        severity="critical",
        pattern=r'\b(K2[A-Za-z0-9]{40,80})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['descope'],
        post_filter_window=120,
        post_filter_direction='both',
        keywords=["descope", "DESCOPE"],
        confidence=0.90,
        description="Descope authentication management key.",
        fix_hint="Revoke at app.descope.com → Applications → Management Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-KINDE-001",
        title="Kinde Client Secret",
        secret_type="kinde_client_secret",
        severity="critical",
        pattern=r'(?i)kinde[^\n]{0,50}(?:secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9]{48,})\b',
        keywords=["kinde", "KINDE"],
        confidence=0.88,
        description="Kinde Auth client secret.",
        fix_hint="Rotate at Kinde → Application Settings → Client secret.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-FUSIONAUTH-001",
        title="FusionAuth API Key",
        secret_type="fusionauth_api_key",
        severity="critical",
        pattern=r'(?i)fusionauth[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["fusionauth", "FUSIONAUTH"],
        confidence=0.92,
        description="FusionAuth administrator API key.",
        fix_hint="Rotate at FusionAuth admin → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SUPERTOKENS-001",
        title="SuperTokens API Key",
        secret_type="supertokens_api_key",
        severity="critical",
        pattern=r'(?i)supertokens[^\n]{0,50}\b([A-Za-z0-9]{32,64})\b',
        keywords=["supertokens", "SUPERTOKENS"],
        confidence=0.85,
        description="SuperTokens core API key.",
        fix_hint="Rotate at supertokens.com → Dashboard.",
    ),

    # ── Observability (more) ─────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-INSTANA-001",
        title="Instana Agent Key",
        secret_type="instana_agent_key",
        severity="high",
        pattern=r'(?i)instana[^\n]{0,50}(?:agent_key|AGENT_KEY)[^\n]{0,30}\b([A-Za-z0-9_-]{20,64})\b',
        keywords=["instana", "INSTANA_AGENT"],
        confidence=0.90,
        description="Instana APM agent key.",
        fix_hint="Rotate at Instana UI → Settings → Agent.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-APPSIGNAL-001",
        title="AppSignal Push API Key",
        secret_type="appsignal_push_api_key",
        severity="medium",
        pattern=r'(?i)appsignal[^\n]{0,50}\b([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\b',
        keywords=["appsignal", "APPSIGNAL"],
        confidence=0.92,
        description="AppSignal push API key.",
        fix_hint="Rotate at appsignal.com → App Settings → Push API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SCOUT-APM-001",
        title="Scout APM Access Key",
        secret_type="scout_apm_key",
        severity="medium",
        pattern=r'(?i)(?:scout_?apm|SCOUTAPM)[^\n]{0,50}\b([A-Za-z0-9]{16,32})\b',
        keywords=["scoutapm", "SCOUTAPM", "scout_apm"],
        confidence=0.85,
        description="Scout APM instrumentation key.",
        fix_hint="Rotate at scoutapp.com → Integrations.",
    ),

    # ── Communication (more) ─────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-BANDWIDTH-V2-001",
        title="Bandwidth v2 API Token",
        secret_type="bandwidth_v2_token",
        severity="high",
        pattern=r'(?i)bandwidth[^\n]{0,50}\b([A-Za-z0-9]{64})\b',
        keywords=["bandwidth", "BANDWIDTH"],
        confidence=0.85,
        description="Bandwidth v2 API user token.",
        fix_hint="Rotate at dashboard.bandwidth.com → Security.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MESSAGEBIRD-001",
        title="MessageBird Access Key",
        secret_type="messagebird_access_key",
        severity="high",
        pattern=r'(?i)messagebird[^\n]{0,50}\b([A-Za-z0-9]{25})\b',
        keywords=["messagebird", "MESSAGEBIRD"],
        confidence=0.88,
        description="MessageBird SMS/Voice access key.",
        fix_hint="Rotate at dashboard.messagebird.com → Developers → API Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CLICKATELL-001",
        title="Clickatell SMS API Key",
        secret_type="clickatell_api_key",
        severity="high",
        pattern=r'(?i)clickatell[^\n]{0,50}\b([A-Za-z0-9_-]{100,})\b',
        keywords=["clickatell", "CLICKATELL"],
        confidence=0.85,
        description="Clickatell SMS gateway API key.",
        fix_hint="Rotate at clickatell.com → Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-INFOBIP-002",
        title="Infobip API Key",
        secret_type="infobip_api_key",
        severity="high",
        pattern=r'(?i)infobip[^\n]{0,50}\b([a-f0-9]{32}-[a-f0-9]{12})\b',
        keywords=["infobip", "INFOBIP"],
        confidence=0.92,
        description="Infobip CPaaS API key.",
        fix_hint="Rotate at portal.infobip.com → My account → API Keys.",
    ),

    # ── Video / Media ────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-MUX-001",
        title="Mux Access Token",
        secret_type="mux_access_token",
        severity="critical",
        pattern=r'(?i)mux[^\n]{0,50}(?:token_id|access_token)[^\n]{0,30}\b([a-f0-9-]{24,40})\b',
        keywords=["mux", "MUX_TOKEN"],
        confidence=0.88,
        description="Mux video platform access token.",
        fix_hint="Rotate at dashboard.mux.com → Settings → API Access Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-WISTIA-001",
        title="Wistia Access Token",
        secret_type="wistia_access_token",
        severity="medium",
        pattern=r'(?i)wistia[^\n]{0,50}\b([a-f0-9]{64})\b',
        keywords=["wistia", "WISTIA"],
        confidence=0.90,
        description="Wistia video hosting access token.",
        fix_hint="Rotate at wistia.com → Account → API Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LIVEKIT-001",
        title="LiveKit API Key",
        secret_type="livekit_api_key",
        severity="high",
        pattern=r'\b(API[A-Za-z0-9]{10,16})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['livekit'],
        post_filter_window=120,
        keywords=["livekit", "LIVEKIT", "LK_API"],
        confidence=0.90,
        description="LiveKit real-time video API key (API prefix).",
        fix_hint="Rotate at livekit.io → Project → Keys.",
    ),

    # ── Database / ETL ───────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-FIVETRAN-001",
        title="Fivetran API Key",
        secret_type="fivetran_api_key",
        severity="critical",
        pattern=r'(?i)fivetran[^\n]{0,50}\b([a-zA-Z0-9]{24})\b',
        keywords=["fivetran", "FIVETRAN"],
        confidence=0.85,
        description="Fivetran data pipeline API key.",
        fix_hint="Rotate at fivetran.com → Settings → API Config.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HIGHTOUCH-001",
        title="Hightouch API Key",
        secret_type="hightouch_api_key",
        severity="high",
        pattern=r'\b(ht_[A-Za-z0-9]{40,})\b',
        keywords=["ht_", "hightouch"],
        confidence=0.93,
        description="Hightouch reverse ETL API key.",
        fix_hint="Rotate at app.hightouch.com → Settings → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-DBT-CLOUD-001",
        title="dbt Cloud API Token",
        secret_type="dbt_cloud_token",
        severity="critical",
        pattern=r'\b(dbtp_[A-Za-z0-9]{40,})\b',
        keywords=["dbtp_", "dbt_cloud", "DBT_CLOUD"],
        confidence=0.98,
        description="dbt Cloud service token.",
        fix_hint="Revoke at cloud.getdbt.com → Account Settings → Service Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SINGLESTORE-001",
        title="SingleStore Management API Key",
        secret_type="singlestore_api_key",
        severity="critical",
        pattern=r'(?i)singlestore[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["singlestore", "SINGLESTORE"],
        confidence=0.88,
        description="SingleStore (formerly MemSQL) Cloud API key.",
        fix_hint="Rotate at portal.singlestore.com → Access.",
    ),

    # ── Monitoring / Uptime ──────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-BETTERUPTIME-001",
        title="Better Uptime Token",
        secret_type="betteruptime_token",
        severity="medium",
        pattern=r'(?i)better.?uptime[^\n]{0,50}\b([A-Za-z0-9]{43,45})\b',
        keywords=["betteruptime", "BETTERUPTIME"],
        confidence=0.88,
        description="Better Uptime monitoring API token.",
        fix_hint="Rotate at betterstack.com → Team API tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PINGDOM-001",
        title="Pingdom API Key",
        secret_type="pingdom_api_key",
        severity="medium",
        pattern=r'(?i)pingdom[^\n]{0,50}\b([A-Za-z0-9]{32,64})\b',
        keywords=["pingdom", "PINGDOM"],
        confidence=0.85,
        description="Pingdom uptime monitoring API key.",
        fix_hint="Rotate at pingdom.com → Integrations → API.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-UPTIMEROBOT-001",
        title="UptimeRobot API Key",
        secret_type="uptimerobot_api_key",
        severity="medium",
        pattern=r'\b(u[0-9]{6,}-[A-Za-z0-9]{32})\b|\b(m[0-9]{6,}-[A-Za-z0-9]{32})\b',
        keywords=["uptimerobot", "UPTIMEROBOT"],
        confidence=0.98,
        description="UptimeRobot main/monitor-specific API key.",
        fix_hint="Revoke at uptimerobot.com → My Settings → API Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CHECKLY-001",
        title="Checkly API Key",
        secret_type="checkly_api_key",
        severity="medium",
        pattern=r'(?i)checkly[^\n]{0,50}\b([a-f0-9]{32})\b',
        keywords=["checkly", "CHECKLY"],
        confidence=0.88,
        description="Checkly synthetic monitoring API key.",
        fix_hint="Rotate at app.checklyhq.com → Account Settings → API Keys.",
    ),

    # ── GraphQL / API Tools ──────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-APOLLO-STUDIO-001",
        title="Apollo Studio API Key",
        secret_type="apollo_studio_key",
        severity="high",
        pattern=r'\b(service:[A-Za-z0-9_-]+:[A-Za-z0-9_-]{16,32}|user:gh\.[A-Za-z0-9_-]+:[A-Za-z0-9_-]+)\b',
        keywords=["service:", "apollo", "APOLLO_KEY"],
        confidence=0.90,
        description="Apollo Studio / Apollo GraphOS API key.",
        fix_hint="Revoke at studio.apollographql.com → API keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-HASURA-ADMIN-001",
        title="Hasura Admin Secret",
        secret_type="hasura_admin_secret",
        severity="critical",
        pattern=r'(?i)hasura[^\n]{0,50}(?:admin_?secret|ADMIN_SECRET)[^\n]{0,30}\b([A-Za-z0-9_-]{20,64})\b',
        keywords=["hasura", "HASURA_GRAPHQL_ADMIN_SECRET"],
        confidence=0.90,
        description="Hasura GraphQL admin secret.",
        fix_hint="Rotate env var HASURA_GRAPHQL_ADMIN_SECRET in Hasura config.",
    ),

    # ── Storage / Backup ─────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-STORJ-001",
        title="Storj Access Grant",
        secret_type="storj_access_grant",
        severity="critical",
        pattern=r'\b(13[a-zA-Z0-9]{250,500})\b',
        keywords=["storj", "STORJ"],
        confidence=0.88,
        description="Storj decentralized storage access grant.",
        fix_hint="Revoke at storj.io → Access → Manage.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-WASABI-001",
        title="Wasabi Hot Cloud Storage Key",
        secret_type="wasabi_access_key",
        severity="critical",
        pattern=r'(?i)wasabi[^\n]{0,50}\b([A-Z0-9]{20})\b',
        keywords=["wasabi", "WASABI"],
        confidence=0.85,
        description="Wasabi S3-compatible storage access key.",
        fix_hint="Rotate at console.wasabisys.com → Access Keys.",
    ),

    # ── Dev Platforms / Hosting (more) ────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-RAILWAY-001",
        title="Railway API Token",
        secret_type="railway_api_token",
        severity="critical",
        pattern=r'(?i)railway[^\n]{0,50}\b([a-f0-9-]{36})\b',
        keywords=["railway", "RAILWAY_TOKEN"],
        confidence=0.93,
        description="Railway deployment platform API token.",
        fix_hint="Revoke at railway.app → Account → Tokens.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-KOYEB-001",
        title="Koyeb API Token",
        secret_type="koyeb_api_token",
        severity="critical",
        pattern=r'(?i)koyeb[^\n]{0,50}\b([a-zA-Z0-9_-]{64,})\b',
        keywords=["koyeb", "KOYEB"],
        confidence=0.85,
        description="Koyeb serverless platform API token.",
        fix_hint="Rotate at app.koyeb.com → API credentials.",
    ),
    # VOODA-SEC-FLY-API-V2-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-FLY-MACAROON-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.

    # ── Testing / QA ─────────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-SAUCE-LABS-001",
        title="Sauce Labs Access Key",
        secret_type="saucelabs_access_key",
        severity="high",
        pattern=r'(?i)sauce.?labs[^\n]{0,60}(?:access.?key|ACCESS_KEY)[^\n]{0,30}\b([a-f0-9-]{36})\b',
        keywords=["saucelabs", "SAUCELABS", "SAUCE_ACCESS_KEY"],
        confidence=0.92,
        description="Sauce Labs cross-browser testing access key.",
        fix_hint="Rotate at app.saucelabs.com → Account → User Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-LAMBDATEST-001",
        title="LambdaTest Access Key",
        secret_type="lambdatest_access_key",
        severity="high",
        pattern=r'(?i)lambdatest[^\n]{0,60}\b([A-Za-z0-9]{20,40})\b',
        keywords=["lambdatest", "LAMBDATEST"],
        confidence=0.85,
        description="LambdaTest cross-browser testing access key.",
        fix_hint="Rotate at accounts.lambdatest.com → Profile → Security.",
    ),

    # ── Search / Vector DBs ──────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-WEAVIATE-001",
        title="Weaviate Cloud API Key",
        secret_type="weaviate_api_key",
        severity="critical",
        pattern=r'(?i)weaviate[^\n]{0,50}\b([A-Za-z0-9_-]{32,64})\b',
        keywords=["weaviate", "WEAVIATE"],
        confidence=0.85,
        description="Weaviate vector database API key.",
        fix_hint="Rotate at console.weaviate.cloud.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-QDRANT-001",
        title="Qdrant Cloud API Key",
        secret_type="qdrant_api_key",
        severity="critical",
        pattern=r'(?i)qdrant[^\n]{0,50}\b([A-Za-z0-9_-]{43,100})\b',
        keywords=["qdrant", "QDRANT"],
        confidence=0.82,
        description="Qdrant vector DB cluster API key.",
        fix_hint="Rotate at cloud.qdrant.io → Clusters → Access.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CHROMA-001",
        title="Chroma Cloud API Key",
        secret_type="chroma_api_key",
        severity="critical",
        pattern=r'(?i)chroma[^\n]{0,50}\b(ck-[A-Za-z0-9_-]{40,})\b',
        keywords=["ck-", "chroma"],
        confidence=0.95,
        description="Chroma vector DB cloud API key (ck- prefix).",
        fix_hint="Rotate at trychroma.com → Settings.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-MEILISEARCH-001",
        title="Meilisearch Master Key",
        secret_type="meilisearch_master_key",
        severity="critical",
        pattern=r'(?i)meilisearch[^\n]{0,50}(?:master|admin|API_KEY)[^\n]{0,30}\b([A-Za-z0-9_-]{43,128})\b',
        keywords=["meilisearch", "MEILI_MASTER_KEY"],
        confidence=0.88,
        description="Meilisearch master or admin API key.",
        fix_hint="Rotate at meilisearch.com → Project → Settings → API keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-TYPESENSE-001",
        title="Typesense API Key",
        secret_type="typesense_api_key",
        severity="high",
        pattern=r'(?i)typesense[^\n]{0,50}\b([A-Za-z0-9]{32,64})\b',
        keywords=["typesense", "TYPESENSE"],
        confidence=0.85,
        description="Typesense search API key.",
        fix_hint="Rotate at cloud.typesense.org → Cluster Access.",
    ),

    # ── Misc high-value ──────────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-POSTGRESS-CONN-PGPASS-001",
        title="PostgreSQL .pgpass Line",
        secret_type="postgres_pgpass",
        severity="critical",
        pattern=r'^[A-Za-z0-9.*_-]+:[0-9*]+:[A-Za-z0-9._*-]+:[A-Za-z0-9._*-]+:([^\s#][^\n]{5,64})$',
        keywords=[":5432:", ":5433:", ".pgpass"],
        confidence=0.80,
        description="Postgres .pgpass-format password line.",
        fix_hint="Remove .pgpass contents from source; use env vars or secret manager.",
        multiline=True,
    ),
    SecretRule(
        rule_id="VOODA-SEC-TWILIO-API-KEY-SK-001",
        title="Twilio API Key (SK prefix)",
        secret_type="twilio_api_key_sk",
        severity="critical",
        pattern=r'\b(SK[a-f0-9]{32})\b',
        keywords=["SK", "twilio"],
        confidence=0.98,
        description="Twilio API key SID (SK prefix, 34 chars total).",
        fix_hint="Revoke at console.twilio.com → Account → API Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-CLOUDFLARE-WORKERS-KV-001",
        title="Cloudflare Workers KV Namespace ID",
        secret_type="cloudflare_workers_kv_id",
        severity="medium",
        pattern=r'\b([a-f0-9]{32})\b',
        # 2-pass: lookahead → post_filter_* (Option B-1 codemod, 2026-05-24).
        post_filter_keywords=['workers.*kv', 'KV_NAMESPACE', 'namespace_id'],
        post_filter_window=120,
        keywords=["workers_kv", "KV_NAMESPACE", "cloudflare"],
        confidence=0.82,
        description="Cloudflare Workers KV namespace identifier.",
        fix_hint="Namespace IDs are not strictly secret but can disclose infra.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-BREW-PACKAGECLOUD-001",
        title="PackageCloud API Token",
        secret_type="packagecloud_token",
        severity="high",
        pattern=r'(?i)packagecloud[^\n]{0,50}\b([a-f0-9]{40,64})\b',
        keywords=["packagecloud", "PACKAGECLOUD"],
        confidence=0.85,
        description="PackageCloud package registry token.",
        fix_hint="Rotate at packagecloud.io → User Settings → API Token.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-PERSONA-SK-LIVE-001",
        title="Persona Live Secret Key",
        secret_type="persona_live_key",
        severity="critical",
        pattern=r'\b(persona_sandbox_[A-Za-z0-9_]{40,}|persona_production_[A-Za-z0-9_]{40,})\b',
        keywords=["persona_sandbox_", "persona_production_"],
        confidence=0.99,
        description="Persona identity verification API key (prefixed form).",
        fix_hint="Revoke at withpersona.com → API settings.",
    ),
    # VOODA-SEC-PULUMI-BACKEND-001 removed 2026-05-22 (Track-A Phase 5, Option A).
    # Exact-pattern duplicate consolidated into VOODA-SEC-PULUMI-V2-001.
    # See services/secret_scan/detectors/registry.py:RULE_ID_ALIASES.
    SecretRule(
        rule_id="VOODA-SEC-VAULT-TOKEN-HVB-001",
        title="HashiCorp Vault Batch Token (hvb.)",
        secret_type="vault_batch_token",
        severity="critical",
        pattern=r'\b(hvb\.[A-Za-z0-9_-]{80,200})\b',
        keywords=["hvb.", "VAULT_TOKEN"],
        confidence=0.98,
        description="HashiCorp Vault batch token (hvb. prefix).",
        fix_hint="Revoke via vault token revoke.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-VAULT-TOKEN-HVR-001",
        title="HashiCorp Vault Recovery Token (hvr.)",
        secret_type="vault_recovery_token",
        severity="critical",
        pattern=r'\b(hvr\.[A-Za-z0-9_-]{80,200})\b',
        keywords=["hvr.", "VAULT_RECOVERY"],
        confidence=0.99,
        description="HashiCorp Vault recovery token (hvr. prefix).",
        fix_hint="Revoke via vault token revoke.",
    ),

    # ── WebhookAPI ──────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-GOOGLE-CHAT-WEBHOOK-001",
        title="Google Chat Webhook URL",
        secret_type="google_chat_webhook_url",
        severity="high",
        pattern=r'https://chat\.googleapis\.com/v1/spaces/[A-Za-z0-9_-]+/messages\?key=[A-Za-z0-9_-]+&token=[A-Za-z0-9_-]+',
        keywords=["chat.googleapis.com"],
        confidence=0.99,
        description="Google Chat incoming webhook URL.",
        fix_hint="Delete at Google Chat → Space → Manage webhooks.",
    ),

    # ── Billing / Accounting ─────────────────────────────────────
    SecretRule(
        rule_id="VOODA-SEC-QUICKBOOKS-001",
        title="QuickBooks OAuth Client Secret",
        secret_type="quickbooks_client_secret",
        severity="critical",
        pattern=r'(?i)quickbooks[^\n]{0,60}(?:client_?secret|SECRET)[^\n]{0,30}\b([A-Za-z0-9]{32})\b',
        keywords=["quickbooks", "QUICKBOOKS"],
        confidence=0.90,
        description="QuickBooks OAuth 2.0 client secret.",
        fix_hint="Rotate at developer.intuit.com → My Apps → Keys.",
    ),
    SecretRule(
        rule_id="VOODA-SEC-SAGE-001",
        title="Sage API Key",
        secret_type="sage_api_key",
        severity="high",
        pattern=r'(?i)(?:sage.?one|sage.?accounting)[^\n]{0,50}\b([A-Za-z0-9]{32,64})\b',
        keywords=["sageone", "sage_accounting", "SAGE_API"],
        confidence=0.82,
        description="Sage One / Sage Accounting API key.",
        fix_hint="Rotate at sage.com → Developer Portal.",
    ),
]
